// Shop data — fetched from the Shopify Storefront API at BUILD time and
// normalized for the PLP (/shop/) and PDP (/shop/<handle>/) pages.
// The token is the PUBLIC publishable Storefront token (safe to embed).
// This replaces the old build-shop.py + products.json flow: the shop now
// re-syncs automatically on every build/deploy.

const SHOP = 'officialdancingbanana.myshopify.com';
const TOKEN = '1032480366b6bf67760ba73ace4fe0f8';
const API = `https://${SHOP}/api/2024-10/graphql.json`;
export const SITE = 'https://trymstene.com';

// @inContext(country: US) → prices come back in USD, the shop's main display
// currency (most traffic is international/US; Shopify still charges each buyer
// their own market currency at checkout).
const QUERY = `query @inContext(country: US) { products(first: 50) { edges { node {
  handle title descriptionHtml productType
  featuredImage { url altText }
  images(first: 30) { edges { node { url altText } } }
  options { name values }
  priceRange { minVariantPrice { amount currencyCode } maxVariantPrice { amount currencyCode } }
  variants(first: 120) { edges { node { id title availableForSale price { amount currencyCode } selectedOptions { name value } image { url altText } } } }
} } } }`;

// ---- colour name -> swatch hex ----
// REAL Printful catalog hexes (Gildan 18500 hoodie + 5000 tee — /products/146,438),
// so the swatch matches the garment. Add new colours here as products are added;
// an unmapped name falls back to grey (a visible signal that it needs adding).
const COLOR_HEX = {
  ash: '#dedede', azalea: '#ff9faf', black: '#0b0b0b', 'brown savana': '#9f8971',
  'carolina blue': '#8db7f6', charcoal: '#534e4a', 'dark chocolate': '#35241b',
  'dark heather': '#47484d', 'forest green': '#222e1f', gold: '#ffaf24',
  'graphite heather': '#686868', 'heather sport dark navy': '#515a6e',
  heliconia: '#f63880', 'indigo blue': '#395d82', 'irish green': '#1d9345',
  'light blue': '#a1c5e1', 'light pink': '#f3d4e3', maroon: '#47171c',
  'military green': '#7e8560', navy: '#131928', orange: '#ff5723',
  purple: '#4a1c7d', red: '#da0a1a', royal: '#1d50a4', sand: '#e7d3b3',
  'sport grey': '#9b969c', white: '#ffffff', natural: '#efe7d2',
};
export const colorHex = (name) => COLOR_HEX[(name || '').trim().toLowerCase()] || '#cccccc';

// ---- size ordering ----
const SIZE_RANK = { XXS: -1, XS: 0, S: 1, M: 2, L: 3, XL: 4, '2XL': 5, XXL: 5, '3XL': 6, XXXL: 6, '4XL': 7, '5XL': 8, '6XL': 9 };
const sizeRank = (s) => (s.toUpperCase() in SIZE_RANK ? SIZE_RANK[s.toUpperCase()] : 50);

export const money = (amount, cur) => {
  const n = parseFloat(amount);
  try {
    return new Intl.NumberFormat('en-US', { style: 'currency', currency: cur, maximumFractionDigits: Number.isInteger(n) ? 0 : 2 }).format(n); // $27, not USD 27.00
  } catch (e) { return `${cur} ${Number.isInteger(n) ? n : n.toFixed(2)}`; }
};

const plain = (html) =>
  (html || '').replace(/<br\s*\/?>/g, ' ').replace(/<[^>]+>/g, '')
    .replace(/&amp;/g, '&').replace(/&quot;/g, '"').replace(/&#39;/g, "'")
    .replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/\s+/g, ' ').trim();

export function firstSentence(html, limit = 140) {
  const t = plain(html);
  let s = t.split(/(?<=[.!?])\s/)[0] || t;
  if (s.length > limit) s = s.slice(0, limit).replace(/\s+\S*$/, '') + '…';
  return s;
}

// ---- size guides: REAL Printful catalog measurements ----
// Data = src/data/size-guides.json, generated by tools/build-size-guides.py
// (re-run it + add the catalog id below when a new garment joins the shop).
import GUIDES from '../data/size-guides.json';

const GUIDE_MATCH = [ // Shopify title substring -> Printful catalog id
  ['classic tee', '438'],
  ['hoodie', '146'],
  ['crop top', '200'],
  ['short sleeve', '108'],
];
export function guideFor(title) {
  const t = (title || '').toLowerCase();
  const hit = GUIDE_MATCH.find(([sub]) => t.includes(sub));
  return hit ? GUIDES[hit[1]] : null;
}

const esc = (s) => String(s == null ? '' : s).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));

// "28" / "33.07" / "38–41" (inches) -> pretty inch + cm strings
const prettyIn = (v) => String(v).replace(/\d+(\.\d+)?/g, (n) => String(Math.round(parseFloat(n) * 10) / 10));
const toCm = (v) => String(v).replace(/\d+(\.\d+)?/g, (n) => String(Math.round(parseFloat(n) * 2.54)));

// Returns the table HTML, or null when the product has no chart (the PDP then
// hides the whole size-guide section — no "contact me for a chart" nonsense).
export function sizeTableHtml(m) {
  const g = guideFor(m.title);
  if (!g || !m.sizes.length) return null;
  const rows = m.sizes.filter((s) => s in g.rows);
  if (!rows.length) return null;
  const head = g.cols.map((c) => `<th>${esc(c)}</th>`).join('');
  const body = rows.map((s) => {
    const cells = [`<td><b>${esc(s)}</b></td>`];
    for (const v of g.rows[s]) {
      cells.push(`<td><span data-unit="in">${esc(prettyIn(v))}"</span><span data-unit="cm" style="display:none">${esc(toCm(v))} cm</span></td>`);
    }
    return `<tr>${cells.join('')}</tr>`;
  }).join('');
  return (
    '<div class="size-toggle" role="group" aria-label="Units">' +
    '<button data-unit="in" aria-pressed="true">inches</button>' +
    '<button data-unit="cm" aria-pressed="false">cm</button></div>' +
    `<table class="size-table"><caption>${esc(g.note)}</caption>` +
    `<thead><tr><th>Size</th>${head}</tr></thead><tbody>${body}</tbody></table>`
  );
}

// ---- normalize a Shopify product node ----
function model(node) {
  const handle = node.handle;
  const title = node.title;
  const descHtml = node.descriptionHtml || '';
  const images = node.images.edges.map((e) => e.node.url);
  const featured = (node.featuredImage && node.featuredImage.url) || images[0] || '';
  const opts = {};
  (node.options || []).forEach((o) => { opts[o.name] = o.values; });

  const variants = node.variants.edges.map((e) => {
    const v = e.node;
    const so = {};
    (v.selectedOptions || []).forEach((x) => { so[x.name] = x.value; });
    return {
      id: v.id, color: so.Color || '', size: so.Size || '',
      price: parseFloat(v.price.amount), cur: v.price.currencyCode,
      available: !!v.availableForSale, image: (v.image && v.image.url) || featured,
    };
  });

  let colors = (opts.Color || []).filter((c) => variants.some((v) => v.color === c));
  if (!colors.length) colors = [...new Set(variants.map((v) => v.color).filter(Boolean))];
  const sizes = [...new Set(variants.map((v) => v.size).filter(Boolean))].sort((a, b) => sizeRank(a) - sizeRank(b));

  const colorImage = {};
  for (const c of colors) {
    const hit = variants.find((v) => v.color === c && v.image);
    colorImage[c] = (hit && hit.image) || featured;
  }

  // key EVERY variant by color||size (either dimension may be empty '' for
  // products that only have sizes, only colours, or a single variant) — else
  // size-only / single-variant products (poster, mug, tote) get no buyable map.
  const vmap = {};
  for (const v of variants) vmap[`${v.color}||${v.size}`] = v;

  const prices = variants.map((v) => v.price);
  const cur = variants.length ? variants[0].cur : 'NOK';

  return {
    handle, title, descHtml, featured, images, colors, sizes, colorImage, vmap, variants, cur,
    pmin: prices.length ? Math.min(...prices) : 0,
    pmax: prices.length ? Math.max(...prices) : 0,
    url: `${SITE}/shop/${handle}/`,
  };
}

// Products that must NOT get a PLP card / PDP page: custom products are only
// purchasable through the make-a-banana builder (which attaches the design) —
// a bare PDP would let people buy them with no design attached.
// ⚠️ EVERY custom builder product added to Shopify needs its handle here, or it
// leaks into the official shop grid (the magnet did — Trym caught it live,
// broken image and all, since custom products have no Shopify product photos).
const BUILDER_ONLY = new Set(['custom-banana-sticker', 'custom-banana-magnet']);

let _cache;
export async function getProducts() {
  if (_cache) return _cache;
  const res = await fetch(API, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'X-Shopify-Storefront-Access-Token': TOKEN },
    body: JSON.stringify({ query: QUERY }),
  });
  if (!res.ok) throw new Error(`Shopify Storefront API ${res.status} at build time`);
  const json = await res.json();
  const nodes = (((json.data || {}).products || {}).edges || []).map((e) => e.node);
  _cache = nodes.filter((n) => !BUILDER_ONLY.has(n.handle)).map(model);
  return _cache;
}
