// Custom-sticker BRAIN, shared by the builder (make-a-banana) and the custom
// product PDP (make-a-banana/sticker) so the design → mockup → print → checkout
// pipeline lives in ONE place. Config drift here = a broken sale, so both pages
// import these — never re-declare them. Framework-free; imports the engine.
import {
  GLASSES, HAT_BY_ID, EXTRA_DEFS, EFFECTS, NFRAMES,
  drawComposite as engineDraw,
} from './banana-engine.js';
import PRODUCTS from '../../shared/products.js';

// Shared store wiring — the SAME store + worker fulfil every custom product;
// only the variant changes per product (see shared/products.js). Storefront
// token is PUBLIC (safe to embed). See memory: sticker-flow.
export const SHOP = {
  workerBase: 'https://banana-sticker.trymstene.workers.dev',
  shopDomain: 'officialdancingbanana.myshopify.com',
  storefrontToken: '1032480366b6bf67760ba73ace4fe0f8',
};
export { PRODUCTS };
export function getProduct(key) { return PRODUCTS.find((p) => p.key === key) || null; }

// Back-compat: the sticker as a flat config. The builder's localized-price
// fetch + its (now-dormant) modal still import STICKER; new multi-product code
// uses SHOP + getProduct() instead.
export const STICKER = { ...SHOP, variantGid: (getProduct('sticker') || {}).shopifyVariantGid };

// What the visitor will actually pay — the static fallback; localizedPrice()
// overwrites it with exactly what checkout charges in the visitor's currency.
export const PRICE = { amount: 14.99, currency: 'USD' };

// ---- design serialization -------------------------------------------------
// Parse a builder share-link (URLSearchParams) into a render state. URL-only:
// the PDP always arrives with the whole design in the query string. Mirrors
// the builder's load() so a link renders identically on both pages.
export function parseDesign(p) {
  const state = { bg: 'transparent', top: '', bottom: '', glasses: 'none', hat: 'none', extras: {}, effect: 'none', frame: 0 };
  if (p.get('bg')) state.bg = p.get('bg');
  state.top = p.get('t') || ''; state.bottom = p.get('b') || '';
  const g = p.get('g'); state.glasses = GLASSES.some(([v]) => v === g) ? g : (g ? 'shades' : 'none'); // old classic/cool links → shades
  const h = p.get('h'); state.hat = HAT_BY_ID[h] ? h : 'none';
  (p.get('ex') || '').split('.').forEach((id) => { if (EXTRA_DEFS.some((d) => d.id === id)) state.extras[id] = true; });
  if (p.get('mu') === '1') state.extras.mustache = true; // legacy params
  if (p.get('bt') === '1') state.extras.bowtie = true;
  const e = p.get('e') || p.get('m'); // old m=disco links still work
  if (EFFECTS.some(([v]) => v === e)) state.effect = e;
  const f = parseInt(p.get('f'), 10); if (f >= 0 && f < NFRAMES) state.frame = f;
  return state;
}

// client moderation gate — the shared FAMILY FILTER (LDNOOBW wordlists +
// leetspeak/boundary matching, generated by tools/build-family-filter.py).
// Still blunt on purpose; the last gate on prints is Trym approving every
// Printful draft, and on gallery items his Banana Mail review.
import { textClean } from './family-filter.js';
export function captionsClean(state) {
  return textClean((state.top || '') + ' ' + (state.bottom || ''));
}

// short human/analytics fingerprint of a design
export function designStr(state) {
  const ex = Object.keys(state.extras).filter((k) => state.extras[k]).join('+') || 'none';
  return [state.hat, state.glasses, ex, state.effect, state.bg].join('|');
}

// draw this state's outfit'd banana (the engine takes explicit outfit args)
export function composite(ctx, W, idx, state, o = {}) {
  return engineDraw(ctx, W, idx, {
    hat: state.hat, glasses: state.glasses, extras: state.extras,
    top: state.top, bottom: state.bottom, ...o,
  });
}

// ---- pixel helpers (trim transparent designs to their content) ------------
export function bboxOf(framesData, W) {
  let minX = W, minY = W, maxX = 0, maxY = 0, found = false;
  for (const data of framesData) for (let y = 0; y < W; y++) for (let x = 0; x < W; x++) {
    if (data[(y * W + x) * 4 + 3] > 16) { found = true; if (x < minX) minX = x; if (x > maxX) maxX = x; if (y < minY) minY = y; if (y > maxY) maxY = y; }
  }
  if (!found) return { x: 0, y: 0, w: W, h: W };
  return { x: minX, y: minY, w: maxX - minX + 1, h: maxY - minY + 1 };
}
export function pad(bb, W) {
  const p = Math.round(Math.max(bb.w, bb.h) * 0.04);
  const x = Math.max(0, bb.x - p), y = Math.max(0, bb.y - p);
  return { x, y, w: Math.min(W - x, bb.w + p * 2), h: Math.min(W - y, bb.h + p * 2) };
}
export function crop(cv, bb) {
  const o = document.createElement('canvas'); o.width = bb.w; o.height = bb.h;
  o.getContext('2d').drawImage(cv, bb.x, bb.y, bb.w, bb.h, 0, 0, bb.w, bb.h); return o;
}

// ---- die-cut sticker rules ------------------------------------------------
// A transparent sticker is DIE-CUT along the artwork outline, so anything
// floating free of the banana can't exist on one physical piece: captions cut
// into a separate island, and confetti/sparkle cut into a scatter of specks.
// So on a die-cut we drop both; a SQUARE (background) sticker keeps everything.
// (disco stays — it just recolours the banana, no floating bits.)
export const stickerCaptions = (state) => state.bg !== 'transparent';
export const stickerEffect = (state) =>
  (state.bg === 'transparent' && (state.effect === 'confetti' || state.effect === 'sparkle')) ? 'none' : state.effect;

// ---- the print file (what actually gets printed) --------------------------
// Two sticker styles (Trym's call): TRANSPARENT bg → trimmed transparent PNG
// so Printful DIE-CUTS along the outline; a COLOURED bg → the full square.
// APPAREL (product.options set, e.g. the tee): always a trimmed transparent
// PNG — the DTG print is the design itself on the garment, so the bg square
// never prints, and captions + confetti/sparkle DO print (no die-cut
// constraint to cut them loose).
// Captions bake into the print via the engine's Anton-first font stack. Anton is
// self-hosted, so it must be DECODED before any (sync) print/mockup render or the
// buyer's OS fallback font gets baked into a real product. Await this in every
// async order/preview path before rendering. No-op once cached.
export async function ensureCaptionFont(state) {
  if (typeof document === 'undefined' || !document.fonts) return;
  const text = (((state && state.top) || '') + ((state && state.bottom) || '')).toUpperCase() || 'A';
  try { await document.fonts.load('64px "Anton"', text); } catch (e) {}
}

export function renderPrintFile(state, product = null) {
  if (product && product.options) return renderApparelPrint(state);
  const W = 2048;
  const cv = document.createElement('canvas'); cv.width = W; cv.height = W; const ctx = cv.getContext('2d');
  composite(ctx, W, state.frame, state, {
    bg: state.bg, captions: stickerCaptions(state), effect: stickerEffect(state),
    hue: state.effect === 'disco' ? (360 * state.frame / NFRAMES) : 0,
  });
  if (state.bg === 'transparent') {
    const data = ctx.getImageData(0, 0, W, W).data;
    return crop(cv, pad(bboxOf([data], W), W));
  }
  return cv;
}

// APPAREL print file: the design deliberately PLACED inside the full 12″×16″
// DTG area (3:4 canvas) — Printful prints the file as the whole area, so the
// transparent margins here ARE the real-world print size and position. The
// design caps at ~76% of the area width (≈9″ on the chest) and starts ~9%
// down (≈1.4″ below the collar seam) — Trym: the fill-the-area default sat
// huge and right at the neck opening. The PDP mockup draws this same canvas,
// so what you see is what prints.
export function renderApparelPrint(state, W = 2048) {
  const H = Math.round(W * (16 / 12));
  // render + trim the raw design first
  const raw = document.createElement('canvas'); raw.width = W; raw.height = W;
  const rctx = raw.getContext('2d');
  composite(rctx, W, state.frame, state, {
    bg: 'transparent', captions: !!(state.top || state.bottom), effect: state.effect,
    hue: state.effect === 'disco' ? (360 * state.frame / NFRAMES) : 0,
  });
  const data = rctx.getImageData(0, 0, W, W).data;
  let trimmed = crop(raw, pad(bboxOf([data], W), W));
  // a TOP caption inherits the meme layout's top-edge position, leaving a big
  // empty gap above the banana — on a chest that parks the text at the collar
  // (Trym: "i wouldnt order that"). Close the gap into a tight lockup. Skipped
  // for confetti/sparkle (their specks live in that gap by design).
  if (state.top && state.effect !== 'confetti' && state.effect !== 'sparkle') {
    trimmed = tightenTopGap(trimmed);
  }
  // place it in the print area: capped size, BOTTOM-ANCHORED at the 73% line
  // (Trym's call: keep the motive as far down as possible so all the slack
  // becomes clearance between the neck edge and the top of the design — a
  // max-height design now starts 13% down the area (≈2″ below the collar
  // seam) instead of 7%, and shorter designs sit even lower, mid-chest)
  const cv = document.createElement('canvas'); cv.width = W; cv.height = H;
  const ctx = cv.getContext('2d');
  const s = Math.min((W * 0.74) / trimmed.width, (H * 0.60) / trimmed.height);
  const dw = trimmed.width * s, dh = trimmed.height * s;
  ctx.imageSmoothingEnabled = false;
  ctx.drawImage(trimmed, (W - dw) / 2, H * 0.73 - dh, dw, dh);
  return cv;
}

// If the artwork's FIRST content band (the top caption) is separated from the
// rest by a fully-transparent gap, shrink that gap to ~3% of the height.
function tightenTopGap(cv) {
  const w = cv.width, h = cv.height;
  const d = cv.getContext('2d').getImageData(0, 0, w, h).data;
  const rowEmpty = (y) => {
    for (let x = 0; x < w; x++) if (d[(y * w + x) * 4 + 3] > 16) return false;
    return true;
  };
  let y = 0;
  while (y < h && rowEmpty(y)) y++;          // leading padding
  let bandEnd = y;
  while (bandEnd < h && !rowEmpty(bandEnd)) bandEnd++; // first band (the caption)
  let gapEnd = bandEnd;
  while (gapEnd < h && rowEmpty(gapEnd)) gapEnd++;     // the gap below it
  const gap = gapEnd - bandEnd;
  const keep = Math.round(h * 0.03);
  if (gapEnd >= h || gap <= keep) return cv; // no lower band, or already tight
  const out = document.createElement('canvas');
  out.width = w; out.height = h - (gap - keep);
  const ctx = out.getContext('2d');
  ctx.drawImage(cv, 0, 0, w, bandEnd, 0, 0, w, bandEnd);
  ctx.drawImage(cv, 0, gapEnd, w, h - gapEnd, 0, bandEnd + keep, w, h - gapEnd);
  return out;
}

// ---- product MOCKUP (what the buyer sees) ---------------------------------
// die-cut white contour for transparent designs, rounded white square for
// coloured ones. product='magnet' adds a grey depth band = visible thickness.
// style='tee' composites the design onto a real per-colour MODEL PHOTO
// (Printful catalog shots in /assets/tee/, preloaded by the PDP and passed as
// opts.photo) — same photo-mockup feel as the official shop. Without a photo
// (builder tiles, photo still loading) it falls back to the chunky pixel tee.
export function makeStickerMockup(state, design, size = 900, style = 'sticker', opts = {}) {
  if (style === 'tee') {
    return (opts.photo && opts.photo.complete && opts.photo.naturalWidth)
      ? makeTeePhotoMockup(design, size, opts.photo, opts.quad)
      : makeTeeMockup(design, size, opts.colorHex || '#ffffff');
  }
  const cv = document.createElement('canvas'); cv.width = size; cv.height = size;
  const ctx = cv.getContext('2d');
  ctx.fillStyle = '#e8e4da'; ctx.fillRect(0, 0, size, size); // paper backdrop
  const margin = size * 0.14;
  const s = Math.min((size - 2 * margin) / design.width, (size - 2 * margin) / design.height);
  const dw = design.width * s, dh = design.height * s;
  const dx = (size - dw) / 2, dy = (size - dh) / 2;
  const border = size * 0.02; // the white kiss-cut edge
  const thick = style === 'magnet' ? size * 0.022 : 0; // magnets show visible depth

  if (state.bg === 'transparent') {
    const sil = document.createElement('canvas'); sil.width = size; sil.height = size;
    const sctx = sil.getContext('2d');
    sctx.drawImage(design, dx, dy, dw, dh);
    sctx.globalCompositeOperation = 'source-in';
    sctx.fillStyle = '#fff'; sctx.fillRect(0, 0, size, size);
    const outline = document.createElement('canvas'); outline.width = size; outline.height = size;
    const octx = outline.getContext('2d');
    for (let k = 0; k < 24; k++) {
      const a = (k / 24) * 2 * Math.PI;
      octx.drawImage(sil, Math.cos(a) * border, Math.sin(a) * border);
    }
    octx.drawImage(sil, 0, 0);
    if (thick) {
      const dark = document.createElement('canvas'); dark.width = size; dark.height = size;
      const dctx = dark.getContext('2d');
      dctx.drawImage(outline, 0, 0);
      dctx.globalCompositeOperation = 'source-in';
      dctx.fillStyle = '#c7c1b4'; dctx.fillRect(0, 0, size, size);
      ctx.drawImage(dark, thick, thick);
    }
    ctx.save();
    ctx.shadowColor = 'rgba(17,17,17,0.28)'; ctx.shadowBlur = size * 0.03; ctx.shadowOffsetY = size * 0.012;
    ctx.drawImage(outline, 0, 0);
    ctx.restore();
    ctx.drawImage(outline, 0, 0);
    ctx.drawImage(design, dx, dy, dw, dh);
  } else {
    const r = size * 0.035;
    if (thick) {
      ctx.save(); ctx.fillStyle = '#c7c1b4';
      ctx.beginPath(); ctx.roundRect(dx - border + thick, dy - border + thick, dw + 2 * border, dh + 2 * border, r); ctx.fill();
      ctx.restore();
    }
    ctx.save();
    ctx.shadowColor = 'rgba(17,17,17,0.28)'; ctx.shadowBlur = size * 0.03; ctx.shadowOffsetY = size * 0.012;
    ctx.fillStyle = '#fff';
    ctx.beginPath(); ctx.roundRect(dx - border, dy - border, dw + 2 * border, dh + 2 * border, r); ctx.fill();
    ctx.restore();
    ctx.save();
    ctx.beginPath(); ctx.roundRect(dx, dy, dw, dh, r * 0.5); ctx.clip();
    ctx.drawImage(design, dx, dy, dw, dh);
    ctx.restore();
  }
  return cv;
}

// photo mockup: the design composited onto the model's chest. The Printful
// catalog shots share one shoot, so the chest quad (fractions of the photo)
// holds across every colour. Square canvas, photo letterboxed on white.
function makeTeePhotoMockup(design, size, photo, quad) {
  const cv = document.createElement('canvas'); cv.width = size; cv.height = size;
  const ctx = cv.getContext('2d');
  ctx.fillStyle = '#fff'; ctx.fillRect(0, 0, size, size);
  const iw = photo.naturalWidth, ih = photo.naturalHeight;
  const s = Math.min(size / iw, size / ih);
  const pw = iw * s, ph = ih * s;
  const px = (size - pw) / 2, py = (size - ph) / 2;
  ctx.drawImage(photo, px, py, pw, ph);
  // the full 12″×16″ DTG print AREA as it sits on this shoot's shirt — the
  // design canvas (renderApparelPrint) is that whole area incl. margins, so
  // drawing it here previews the exact physical print size and position.
  // Quads are per shoot (each mockup style frames the shirt differently).
  const q = quad || TEE_QUADS.woman;
  const zw = q.w * pw;
  const zh = zw * (16 / 12);
  const ds = Math.min(zw / design.width, zh / design.height);
  const dw = design.width * ds, dh = design.height * ds;
  ctx.drawImage(design, px + q.cx * pw - dw / 2, py + q.top * ph, dw, dh);
  return cv;
}

// print-area quads (fractions of each photo) — hand-tuned per mockup shoot
export const TEE_QUADS = {
  woman: { cx: 0.500, top: 0.355, w: 0.250 },
  man:   { cx: 0.500, top: 0.355, w: 0.250 },
  flat:  { cx: 0.500, top: 0.205, w: 0.420 },
};

// the pixel tee: a step-polygon t-shirt on a 24-unit grid, filled with the
// chosen garment colour, black pixel outline (the site's art language), a
// simple shade under collar + hem, and the design scaled onto the chest.
function makeTeeMockup(design, size, colorHex) {
  const cv = document.createElement('canvas'); cv.width = size; cv.height = size;
  const ctx = cv.getContext('2d');
  ctx.fillStyle = '#e8e4da'; ctx.fillRect(0, 0, size, size); // same paper backdrop
  const u = size / 24;
  // step-polygon outline (u-grid points), drawn clockwise from left collar
  const pts = [
    [8, 3], [9.6, 3], [10.4, 4.4], [13.6, 4.4], [14.4, 3], [16, 3], // collar notch
    [21.5, 5.4], [23, 9], [19.2, 10.8], [18.4, 9.4],                // right sleeve
    [18.4, 20.6], [5.6, 20.6],                                      // hem
    [5.6, 9.4], [4.8, 10.8], [1, 9], [2.5, 5.4],                    // left sleeve
  ];
  const path = () => {
    ctx.beginPath();
    pts.forEach(([x, y], i) => (i ? ctx.lineTo(x * u, y * u) : ctx.moveTo(x * u, y * u)));
    ctx.closePath();
  };
  // soft drop shadow, then fill + chunky outline
  ctx.save();
  ctx.shadowColor = 'rgba(17,17,17,0.25)'; ctx.shadowBlur = size * 0.025; ctx.shadowOffsetY = size * 0.012;
  path(); ctx.fillStyle = colorHex; ctx.fill();
  ctx.restore();
  path(); ctx.fillStyle = colorHex; ctx.fill();
  path(); ctx.lineWidth = Math.max(3, u * 0.28); ctx.strokeStyle = '#141310'; ctx.stroke();
  // collar band + hem shade (a slightly darker/lighter tint of the garment)
  const shade = (hex, f) => {
    const n = parseInt(hex.slice(1), 16);
    const ch = (v) => Math.max(0, Math.min(255, Math.round(v * f)));
    return `rgb(${ch(n >> 16)},${ch((n >> 8) & 255)},${ch(n & 255)})`;
  };
  ctx.fillStyle = shade(colorHex, colorHex.toLowerCase() === '#ffffff' ? 0.88 : 0.78);
  ctx.beginPath(); // collar band follows the notch
  ctx.moveTo(9.6 * u, 3 * u); ctx.lineTo(10.4 * u, 4.4 * u); ctx.lineTo(13.6 * u, 4.4 * u);
  ctx.lineTo(14.4 * u, 3 * u); ctx.lineTo(13.9 * u, 3 * u); ctx.lineTo(13.25 * u, 3.9 * u);
  ctx.lineTo(10.75 * u, 3.9 * u); ctx.lineTo(10.1 * u, 3 * u); ctx.closePath(); ctx.fill();
  ctx.fillRect(5.6 * u, 20.1 * u, 12.8 * u, 0.5 * u); // hem
  // the design on the chest — fit inside a 9.4u x 9.6u print zone
  const zw = 9.4 * u, zh = 9.6 * u;
  const s = Math.min(zw / design.width, zh / design.height);
  const dw = design.width * s, dh = design.height * s;
  ctx.drawImage(design, (size - dw) / 2, 6.6 * u + (zh - dh) / 2, dw, dh);
  return cv;
}

// ---- live price -----------------------------------------------------------
// Ask Shopify the CURRENT price so badges track price edits without a site
// build. Pinned to the US market since the 15 Jul USD cutover — the store
// sells in USD everywhere, so geolocating (@inContext with the visitor's
// country) showed Shopify's auto-converted local currency ("kr 146") on the
// sticker tile while every static price said "$14.99". One store, one price.
// Returns { display, amount, currency } or null on any failure.
export async function localizedPrice(product = getProduct('sticker')) {
  try {
    if (!product || !product.shopifyVariantGid) return null;
    const res = await fetch('https://' + SHOP.shopDomain + '/api/2024-10/graphql.json', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'X-Shopify-Storefront-Access-Token': SHOP.storefrontToken },
      body: JSON.stringify({
        query: 'query($id: ID!, $country: CountryCode!) @inContext(country: $country) { node(id: $id) { ... on ProductVariant { price { amount currencyCode } } } }',
        variables: { id: product.shopifyVariantGid, country: 'US' },
      }),
    }).then((r) => r.json());
    const p = res && res.data && res.data.node && res.data.node.price;
    if (!p) return null;
    PRICE.amount = parseFloat(p.amount); PRICE.currency = p.currencyCode;
    // en-US formatting so the dynamic price matches the site's static "$14.99"
    // style in every visitor locale; cents show only when they carry meaning
    // ($14.99 keeps its psychology, a rounded $15.00 shows as $15)
    const display = new Intl.NumberFormat('en-US', {
      style: 'currency', currency: p.currencyCode,
      currencyDisplay: 'narrowSymbol', trailingZeroDisplay: 'stripIfInteger',
    }).format(PRICE.amount);
    return { display, amount: PRICE.amount, currency: PRICE.currency };
  } catch (e) { return null; }
}

// ---- checkout -------------------------------------------------------------
// Upload the print PNG to the Worker (→ R2), then create a Shopify cart with
// the design attached as line-item attributes. Returns the checkoutUrl (the
// caller redirects). Throws on any failure so the caller can recover the UI.
export async function uploadAndCheckout(printCanvas, product = getProduct('sticker'), selection = null) {
  if (!product || !product.shopifyVariantGid) throw new Error('product not available for sale');
  const blob = await new Promise((r) => printCanvas.toBlob(r, 'image/png'));
  if (!blob) throw new Error('render failed: toBlob returned null'); // iOS under memory pressure does this silently
  const up = await fetch(SHOP.workerBase + '/upload', { method: 'POST', headers: { 'Content-Type': 'image/png' }, body: blob });
  if (!up.ok) throw new Error('upload failed: ' + up.status);
  const { key, url } = await up.json();

  const attributes = [
    { key: '_design_key', value: key },   // machine-readable, hidden in checkout
    { key: '_product', value: product.key }, // fulfilment mapping (temp variants have unknown ids)
    { key: 'Design', value: url },        // visible link so the customer sees THEIR banana
  ];
  if (selection && product.options) {
    // apparel: colour + size ride as attributes on the ONE Shopify variant.
    // Price-neutral (all colour/size combos cost the same), so the worker can
    // trust them to pick the Printful variant. Visible copies for the human.
    const colorDef = product.options.colors.find((c) => c.id === selection.color) || product.options.colors[0];
    const size = product.options.sizes.includes(selection.size) ? selection.size : 'M';
    attributes.push(
      { key: '_color', value: colorDef.id },
      { key: '_size', value: size },
      { key: 'Color', value: colorDef.label },
      { key: 'Size', value: size },
    );
  }

  // Per-order product first: the worker mints a disposable variant wearing THIS
  // design as its image, so checkout shows the buyer's actual banana. Any
  // failure (worker unconfigured, Admin API hiccup) falls back to the shared
  // variant — checkout must never break over a thumbnail.
  let merchandiseId = product.shopifyVariantGid;
  try {
    const co = await fetch(SHOP.workerBase + '/checkout', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ key, product: product.key }),
    });
    if (co.ok) {
      const j = await co.json();
      if (j && j.variantGid) merchandiseId = j.variantGid;
    }
  } catch (e) {}

  const mutation = 'mutation($lines: [CartLineInput!]!) { cartCreate(input: { lines: $lines }) { cart { checkoutUrl } userErrors { message } } }';
  const res = await fetch('https://' + SHOP.shopDomain + '/api/2024-10/graphql.json', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'X-Shopify-Storefront-Access-Token': SHOP.storefrontToken },
    body: JSON.stringify({
      query: mutation,
      variables: { lines: [{ merchandiseId, quantity: 1, attributes }] },
    }),
  });
  const data = await res.json();
  const checkout = data && data.data && data.data.cartCreate && data.data.cartCreate.cart && data.data.cartCreate.cart.checkoutUrl;
  if (!checkout) throw new Error('cart failed: ' + JSON.stringify(data));
  return { checkoutUrl: checkout, key, url };
}
