// Banana rave worker — the realtime dance floor.
//
// The trick that makes this nearly free: the dance itself needs ZERO server
// traffic. Every banana on Earth dances in phase off the wall clock
// (t = Date.now() % cycle). The server only does PRESENCE: who's on the
// floor (outfit ids + join time) and the occasional emote. A rave is,
// technically, a chat room where nobody talks.
//
// Moderation surface: ONE field, defended in depth (17 Jul — Trym's ONE-
// identity call: the pass name shows on the floor too). Outfits validate
// against id allowlists, emotes are a fixed set, and the NAME passes the
// family filter + Trym's strike list at the door (sanitizeName) — a name
// that fails simply doesn't travel; the banana wears its outfit-name.
// Admin: GET /names?key= (ledger of names seen + live + strikes) and
// POST /strike?key= {t, remove?} — the quick swipe; scrubs the live floor.
//
// Cost guardrails: WebSocket hibernation (idle connections ≈ free), room cap,
// per-connection emote throttle, Origin allowlist. Free plan fails closed.
//
// Routes:
//   GET /ws      upgrade → the room ("main-floor")
//   GET /count   current floor count (for the homepage proof-of-life later)

// the park's weed lattice — generated by tools/build-park-scene.py
import { WEED_GRID, BORDER_SPOTS_N, ALGAE_SPOTS, BIRD_SPOTS_N } from './park-weed-grid.js';

// ALLOWLISTS-START — GENERATED by tools/build-worker-allowlists.mjs from
// src/data/wearables.js (the single-source manifest). NEVER edit by hand:
// rerun the script after any wearable change, then deploy this worker.
// raveOnly items (beer/cone/vinyl/broom) are server-granted and excluded
// so sanitize strips them from client outfits.
const HAT_IDS = ['none', 'party', 'crown', 'tophat', 'cowboy', 'viking', 'sombrero', 'halo', 'beanieprop', 'backwardscap', 'gradcap', 'tricorn', 'jester', 'friedegg', 'pigeon', 'arrowthru', 'fishbowl', 'devilhorns', 'nightcap', 'djheadphones', 'duckhat', 'melticecream', 'watermelonhat', 'buckethat', 'snailhat', 'squidhat'];
const DROP_IDS = ['djheadphones'];
const SHADE_IDS = ['none', 'shades', 'dwi', 'hearts', 'visor', 'threed', 'potter', 'nerd', 'monocle', 'groucho', 'eyepatch', 'googlyeyes', 'cucumbers', 'snorkelmask'];
const EXTRA_IDS = ['mustache', 'fatstache', 'bowtie', 'necktie', 'goldchain', 'scarf', 'coneofshame', 'lifering', 'nightshirt', 'flamingoring', 'medal', 'sneakers', 'sneakersblue', 'sneakersgold', 'skates', 'clownshoes', 'cowboyboots', 'discoboots', 'ledsneakers', 'flamekicks', 'flippers', 'sockssandals', 'boombox', 'mug', 'trophy', 'boingball', 'balloons', 'rubberchicken', 'bigfish', 'protestsign', 'candle', 'balloondog', 'plushbanana', 'potato', 'cactuspot', 'glowstick', 'goldbanana'];
// ALLOWLISTS-END
const EFFECT_IDS = ['none', 'disco', 'sparkle', 'confetti'];
const EMOTES = ['heart', 'confetti', 'banana', 'fire']; // fire = stage members only
const ROOM_CAP = 200;
const STAGE_CAP = 8;                  // spots on the line behind the DJ
const STAGE_MIN_MS = 5 * 60 * 1000;   // survive 5 min on the floor → the stage opens (keep in sync with STAGE_UNLOCK_MS in banana-rave.js)
// HAPPY HOUR — same wall-clock windows as the client (keep in sync with banana-rave.js).
// One beer per window, first claim wins; the beer lives in outfit.extras but is
// SERVER-GRANTED only ('beer' is deliberately NOT in EXTRA_IDS → sanitize strips it).
const HAPPY_PERIOD = 300_000, HAPPY_LEN = 40_000, HAPPY_OFFSET = 120_000;
function happyWindow(now) {
  const ph = (((now - HAPPY_OFFSET) % HAPPY_PERIOD) + HAPPY_PERIOD) % HAPPY_PERIOD;
  return ph < HAPPY_LEN ? Math.floor((now - HAPPY_OFFSET) / HAPPY_PERIOD) : -1;
}
// THE LOST VINYL — courier quest (keep schedule + spot math in sync with banana-rave.js):
// spawns every 7 min at a clock-seeded spot, first banana to reach it carries it,
// delivering to the stage edge buys the whole floor a bonus drop.
const VINYL_PERIOD = 420_000, VINYL_WAIT = 180_000, VINYL_OFFSET = 210_000;
function vinylWindow(now) {
  const ph = (((now - VINYL_OFFSET) % VINYL_PERIOD) + VINYL_PERIOD) % VINYL_PERIOD;
  return ph < VINYL_WAIT ? Math.floor((now - VINYL_OFFSET) / VINYL_PERIOD) : -1;
}
function seedRand(n) {
  let x = Math.imul(n ^ 0x9e3779b9, 0x85ebca6b);
  x = Math.imul(x ^ (x >>> 13), 0xc2b2ae35);
  x ^= x >>> 16;
  return (x >>> 0) / 4294967296;
}

// ═══════════════════════════════════════════════════════════════════════════
// 🌦 THE WEATHER CLOCK — a PURE FUNCTION OF TIME. No state, no cron, no sync
// message: the client renders from it and the ParkRoom charges health from it,
// and they agree because they run the same arithmetic over the same clock.
// (The coin-window pattern, one level up.)
// ⚠️⚠️ MIRRORED VERBATIM IN src/lib/world.js — CHANGE BOTH OR NEITHER.
//
// ⚠️ EVENTS PER DAY, NOT DICE PER WINDOW. Rolling weather every 20 minutes is
// 72 draws a day, so even a 5% chance compounds to near-certainty and hand-
// watering dies no matter how short the watering window is. The window length
// was never the lever — the SHAPE of the rain is. Each DAY seeds its events,
// so weather comes in FRONTS: dry days, changeable days, wet days, and real dry
// stretches between them. Those dry stretches are why watering still matters.
//
// Simulated over 730 days before shipping (tools note, 30 Jul):
//   heavy rain every 2.9 days · storms every 17.1 days
//   drizzle on screen 7.3% of the time · heavy 0.49% · storm 0.04%
// You will rarely catch a storm live — but you will often walk into what it
// did, because the wreckage stays until somebody clears it. That asymmetry is
// the design, not a side effect.
const WEATHER_SALT = 0x7a1e;
const WEATHER_DAY_MS = 86400000;
const WEATHER_MINS = { drizzle: [30, 62], heavy: [15, 26], storm: [8, 13] };

// one day of weather, from its day index alone
function weatherDay(d) {
  const r = seedRand(WEATHER_SALT + d * 7919);
  const kind = r < 0.45 ? 'dry' : r < 0.80 ? 'changeable' : 'wet';
  const nDrizzle = kind === 'dry' ? 1 : kind === 'changeable' ? 3 : 4;
  const heavy = kind === 'wet' ? 1
    : (kind === 'changeable' && seedRand(WEATHER_SALT + d * 401) < 0.40 ? 1 : 0);
  const storm = kind === 'wet' && seedRand(WEATHER_SALT + d * 613) < 0.30 ? 1 : 0;
  const types = [];
  for (let i = 0; i < nDrizzle; i++) types.push('drizzle');
  for (let i = 0; i < heavy; i++) types.push('heavy');
  for (let i = 0; i < storm; i++) types.push('storm');
  const n = types.length, out = [];
  for (let i = 0; i < n; i++) {
    const type = types[i], [lo, hi] = WEATHER_MINS[type];
    const ms = Math.round((lo + seedRand(WEATHER_SALT + d * 313 + i * 53) * (hi - lo)) * 60000);
    // one slot each, so two events can never overlap
    const slot = WEATHER_DAY_MS / n;
    const at = Math.floor(i * slot + seedRand(WEATHER_SALT + d * 131 + i * 17) * Math.max(0, slot - ms));
    out.push({ type, at, ms });
  }
  return out.sort((a, b) => a.at - b.at);
}

// what is falling at t? → { type:'clear'|'drizzle'|'heavy'|'storm', since, left }
function weatherAt(t) {
  const d = Math.floor(t / WEATHER_DAY_MS);
  const inDay = t - d * WEATHER_DAY_MS;
  for (const e of weatherDay(d)) {
    if (inDay >= e.at && inDay < e.at + e.ms) {
      return { type: e.type, since: inDay - e.at, left: e.at + e.ms - inDay };
    }
  }
  return { type: 'clear', since: 0, left: 0 };
}

// every event that STARTED in (from, to] — the ParkRoom walks this on its lazy
// read, so weather nobody was present for still lands
function weatherBetween(from, to) {
  const out = [];
  for (let d = Math.floor(from / WEATHER_DAY_MS); d <= Math.floor(to / WEATHER_DAY_MS); d++) {
    for (const e of weatherDay(d)) {
      const at = d * WEATHER_DAY_MS + e.at;
      if (at > from && at <= to) out.push({ type: e.type, at, ms: e.ms });
    }
  }
  return out.sort((a, b) => a.at - b.at);
}
function vinylSpot(w) {
  let x = 12 + seedRand(0x5eed + w * 2) * 70;
  let y = 26 + seedRand(0x5eed + w * 2 + 1) * 46; // open floor only — high spawns near the stage edge were unreachable on iOS
  if (x < 36 && y > 66) y -= 30;
  return { x, y };
}
// HOT SAUCE — a bottle on the open floor every 4 min; grabbing it grants a timed
// flame-trail fx. fx is SERVER-GRANTED like the beer: clients only render what
// the roster says, so effects can't be spoofed.
const SAUCE_PERIOD = 180_000, SAUCE_WAIT = 100_000, SAUCE_OFFSET = 60_000;
function sauceWindow(now) {
  const ph = (((now - SAUCE_OFFSET) % SAUCE_PERIOD) + SAUCE_PERIOD) % SAUCE_PERIOD;
  return ph < SAUCE_WAIT ? Math.floor((now - SAUCE_OFFSET) / SAUCE_PERIOD) : -1;
}
function sauceSpot(w) {
  let x = 12 + seedRand(0xf1a5 + w * 2) * 70;
  let y = 26 + seedRand(0xf1a5 + w * 2 + 1) * 46;
  if (x < 36 && y > 66) y -= 30;
  return { x, y };
}
// THE GOLDEN BANANA — a rare drop (~every 30 min); the finder mints a patch and
// the whole floor gets a confetti party. A moment, not a power-up.
const GOLD_PERIOD = 1_800_000, GOLD_WAIT = 240_000, GOLD_OFFSET = 660_000;
function goldWindow(now) {
  const ph = (((now - GOLD_OFFSET) % GOLD_PERIOD) + GOLD_PERIOD) % GOLD_PERIOD;
  return ph < GOLD_WAIT ? Math.floor((now - GOLD_OFFSET) / GOLD_PERIOD) : -1;
}
function goldSpot(w) {
  let x = 12 + seedRand(0x601d + w * 2) * 70;
  let y = 26 + seedRand(0x601d + w * 2 + 1) * 46;
  if (x < 36 && y > 66) y -= 30;
  return { x, y };
}
// THE CONVEYOR — one unified item stream so the floor is NEVER dead (Trym's
// low-traffic brief: solo visitors need a constant chase). A new item every 75s
// at a clock-seeded spot; the type comes from the same seed. Effect items ride
// the fx system; snacks (candy/pizza/balloon) are pure chase + client-side chain.
// items live FIVE SECONDS on the floor (Trym: reflex, not patience) — the
// client shows/poofs at 5s; the server window carries 1.5s latency grace
const ITEM_PERIOD = 75_000, ITEM_WAIT = 6_500, ITEM_OFFSET = 15_000;
function itemWindow(now) {
  const ph = (((now - ITEM_OFFSET) % ITEM_PERIOD) + ITEM_PERIOD) % ITEM_PERIOD;
  return ph < ITEM_WAIT ? Math.floor((now - ITEM_OFFSET) / ITEM_PERIOD) : -1;
}
function itemSpot(w) {
  let x = 12 + seedRand(0x17e6 + w * 2) * 70;
  let y = 26 + seedRand(0x17e6 + w * 2 + 1) * 46;
  if (x < 36 && y > 66) y -= 30;
  return { x, y };
}
function itemType(w) { // keep weights in sync with banana-rave.js
  const r = seedRand(0x7ab1e + w);
  // 22 kinds — classics keep a slight edge; the R4.5 six close the table
  return r < 0.08 ? 'sauce' : r < 0.15 ? 'zap' : r < 0.22 ? 'fizz'
    : r < 0.28 ? 'candy' : r < 0.34 ? 'pizza' : r < 0.40 ? 'balloon'
    : r < 0.45 ? 'shard' : r < 0.50 ? 'cone' : r < 0.55 ? 'popper'
    : r < 0.59 ? 'remote' : r < 0.63 ? 'kazoo' : r < 0.67 ? 'glitter'
    : r < 0.71 ? 'phone' : r < 0.75 ? 'cube' : r < 0.78 ? 'pizzabox'
    : r < 0.81 ? 'wand' : r < 0.85 ? 'boots' : r < 0.88 ? 'gel'
    : r < 0.91 ? 'sparkler' : r < 0.94 ? 'magnet' : r < 0.97 ? 'vhs' : 'star';
}
const ITEM_FX = { // all rendering is client-side; the server only stamps fx ids
  sauce: 'flames', zap: 'zap', fizz: 'fizz', balloon: 'balloon',
  shard: 'prism', cone: 'cone', popper: 'popper', remote: 'fog', kazoo: 'notes',
  glitter: 'glitter', phone: 'flash', cube: 'slide', wand: 'bubbles',
  boots: 'boots', gel: 'wobble', sparkler: 'sparkler', magnet: 'magnet', vhs: 'vhs', star: 'conga',
  // the snacks wear their dinner now (Trym round 2): held pizza props + the
  // sugar shakes; pizzabox still pays its jelly client-side on top
  pizza: 'slice', pizzabox: 'box', candy: 'sugar',
};
// BARTY'S SPECIALS — between happy hours a rotating cocktail lands on the counter;
// first banana at the bar drinks it and wears its effect for a while.
const SPECIAL_PERIOD = 300_000, SPECIAL_LEN = 35_000, SPECIAL_OFFSET = 270_000;
const COCKTAILS = ['daiquiri', 'fizz', 'espresso', 'lagoon', 'colada', 'margarita', 'champagne', 'milkshake', 'jellyshot', 'water']; // keep in sync with banana-rave.js
function specialWindow(now) {
  const ph = (((now - SPECIAL_OFFSET) % SPECIAL_PERIOD) + SPECIAL_PERIOD) % SPECIAL_PERIOD;
  return ph < SPECIAL_LEN ? Math.floor((now - SPECIAL_OFFSET) / SPECIAL_PERIOD) : -1;
}
// effects are MOMENTS, not outfits — 10s baseline with the item menu cycling
// (Trym's call; was 150s/60s). Clients also cap at first sight (capFx).
// Trym's juice pass: the crowd favourites earn longer runs (keep in sync
// with banana-rave.js FX_DUR — the client cap clamps to the same table).
const FX_MS = 10_000;
const FX_DUR = { cone: 30_000, balloon: 20_000, zap: 20_000, conga: 15_000, boots: 15_000, magnet: 12_000, sparkler: 12_000, fog: 20_000 };
const fxLen = (id) => FX_DUR[id] || FX_MS;

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const room = env.RAVE.get(env.RAVE.idFromName('main-floor'));
    if (url.pathname === '/ws') {
      const allowed = (env.ALLOWED_ORIGIN || '').split(',').map((s) => s.trim());
      if (!allowed.includes(request.headers.get('Origin') || '')) {
        return new Response('forbidden', { status: 403 });
      }
      return room.fetch(request);
    }
    // 🌳 the PARK outside the stand — its own tiny room (S5): presence +
    // positions + outfits only, none of the floor's event machinery
    if (url.pathname === '/park') {
      const allowed = (env.ALLOWED_ORIGIN || '').split(',').map((s) => s.trim());
      if (!allowed.includes(request.headers.get('Origin') || '')) {
        return new Response('forbidden', { status: 403 });
      }
      return env.PARK.get(env.PARK.idFromName('the-park')).fetch(request);
    }
    // 🏖 BANANA BAY — same deal, its own room
    if (url.pathname === '/beach') {
      const allowed = (env.ALLOWED_ORIGIN || '').split(',').map((s) => s.trim());
      if (!allowed.includes(request.headers.get('Origin') || '')) {
        return new Response('forbidden', { status: 403 });
      }
      return env.BEACH.get(env.BEACH.idFromName('banana-bay')).fetch(request);
    }
    // the Banana Mail rave-names desk (browser fetches from trymstene.com)
    if (url.pathname === '/names' || url.pathname === '/strike') {
      const allowed = (env.ALLOWED_ORIGIN || '').split(',').map((s) => s.trim());
      const origin = request.headers.get('Origin') || '';
      const cors = {
        'Access-Control-Allow-Origin': allowed.includes(origin) ? origin : 'https://trymstene.com',
        'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
        'Access-Control-Allow-Headers': 'content-type',
        'Cache-Control': 'no-store',
        'Content-Type': 'application/json',
      };
      if (request.method === 'OPTIONS') return new Response(null, { headers: cors });
      const res = await room.fetch(new Request('https://room' + url.pathname + url.search, {
        method: request.method,
        body: request.method === 'POST' ? await request.text() : undefined,
      }));
      let payload = await res.text();
      // the Names desk covers the WHOLE world: fold the park + beach live rosters
      // into `live` (their names already ride the shared ledger via /ingest)
      if (url.pathname === '/names' && res.ok) {
        try {
          const data = JSON.parse(payload);
          for (const [ns, id] of [[env.PARK, 'the-park'], [env.BEACH, 'banana-bay']]) {
            try {
              const rr = await ns.get(ns.idFromName(id)).fetch(new Request('https://room/rosternames'));
              const jj = await rr.json();
              if (Array.isArray(jj.names)) data.live = [...(data.live || []), ...jj.names];
            } catch (e) {}
          }
          payload = JSON.stringify(data);
        } catch (e) {}
      }
      return new Response(payload, { status: res.status, headers: cors });
    }
    if (url.pathname === '/count') {
      const res = await room.fetch(new Request('https://room/count'));
      return new Response(await res.text(), {
        headers: { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*', 'Cache-Control': 'no-store' },
      });
    }
    if (url.pathname === '/park-count') { // the HQ world desk's park headcount
      const res = await env.PARK.get(env.PARK.idFromName('the-park')).fetch(new Request('https://room/count'));
      return new Response(await res.text(), {
        headers: { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*', 'Cache-Control': 'no-store' },
      });
    }
    // 🌱 THE PARK GARDEN (P3b) — browser fetches from trymstene.com; the
    // /names CORS pattern, forwarded to the ParkRoom's /garden routes
    if (url.pathname === '/park-garden' || url.pathname.startsWith('/park-garden/')) {
      const allowed = (env.ALLOWED_ORIGIN || '').split(',').map((s) => s.trim());
      const origin = request.headers.get('Origin') || '';
      const cors = {
        'Access-Control-Allow-Origin': allowed.includes(origin) ? origin : 'https://trymstene.com',
        'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
        'Access-Control-Allow-Headers': 'content-type',
        'Cache-Control': 'no-store',
        'Content-Type': 'application/json',
      };
      if (request.method === 'OPTIONS') return new Response(null, { headers: cors });
      // ⚠️ the SEARCH goes through too — a GET read carries ?pass= so the
      // room can hand back what the compost owes that grower (see RIPE_TTL).
      const sub = url.pathname.replace('/park-garden', '/garden') + url.search;
      const res = await env.PARK.get(env.PARK.idFromName('the-park')).fetch(new Request('https://room' + sub, {
        method: request.method,
        body: request.method === 'POST' ? await request.text() : undefined,
      }));
      return new Response(await res.text(), { status: res.status, headers: cors });
    }
    if (url.pathname === '/beach-count') { // …and its beach headcount
      const res = await env.BEACH.get(env.BEACH.idFromName('banana-bay')).fetch(new Request('https://room/count'));
      return new Response(await res.text(), {
        headers: { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*', 'Cache-Control': 'no-store' },
      });
    }
    return new Response('not found', { status: 404 });
  },
};

function sanitizeOutfit(o) {
  o = o && typeof o === 'object' ? o : {};
  const extras = {};
  EXTRA_IDS.forEach((id) => { if (o.extras && o.extras[id] === true) extras[id] = true; });
  return {
    hat: HAT_IDS.includes(o.hat) ? o.hat : 'none',
    glasses: SHADE_IDS.includes(o.glasses) ? o.glasses : 'none',
    extras,
    effect: EFFECT_IDS.includes(o.effect) ? o.effect : 'none',
    // 'c' = a caught COMMUNITY catalog item (worker-share catalog/items.json).
    // Format-validated only: spectators render it from the public manifest, so
    // an unknown id simply draws nothing — bounded string, no art risk here.
    ...(/^c_[a-f0-9]{6,32}$/.test(o.c || '') ? { c: o.c } : {}),
  };
}

// THE FAMILY FILTER (server copy — floor names the client can't sneak past).
// AUTO-PATCHED by tools/build-family-filter.py between the markers below;
// same lists + matching as src/lib/family-filter.js. Never edit by hand.
// FAMILY-FILTER-START
const F_WORDS = new Set('acrotomophilia|anal|anilingus|anus|arsehole|ass|asshole|assmunch|autoerotic|babeland|bangbros|bangbus|bareback|barenaked|bastard|bastardo|bastinado|bbw|bdsm|beaner|beaners|beastiality|bestiality|bimbos|birdlock|blowjob|blumpkin|bollocks|bondage|boner|boob|boobs|bukkake|bulldyke|bunghole|busty|butt|buttcheeks|butthole|camgirl|camslut|carpetmuncher|cialis|circlejerk|clit|clitoris|cock|cocks|coon|coons|coprolagnia|coprophilia|cornhole|creampie|cum|cumming|cumshot|cumshots|cunnilingus|darkie|daterape|deepthroat|dendrophilia|dick|dildo|dingleberries|dingleberry|doggiestyle|doggystyle|dolcett|domination|dominatrix|dommes|dritt|drittsekk|dvda|ecchi|ejaculation|erotic|erotism|escort|eunuch|faen|fag|fanken|fecal|felch|fellatio|feltch|femdom|figging|fingerbang|fingering|fisting|fitte|footjob|forbanna|forbannet|frotting|fudgepacker|futanari|føkk|føkka|føkkings|gangbang|genitals|goatcx|goatse|gokkun|goodpoop|goregasm|grope|guro|handjob|hardcore|helvete|helvetet|hentai|homoerotic|honkey|hooker|hore|horny|humping|incest|intercourse|jailbait|jigaboo|jiggaboo|jiggerboo|jizz|juggs|kike|kinbaku|kinkster|kinky|kneppe|knobbing|kuk|kukene|kuker|livesex|lolita|lovemaking|masturbate|masturbating|masturbation|milf|mong|morraknuller|morrapuler|muffdiving|nambla|nawashi|nazi|negro|neonazi|nimphomania|nipple|nipples|nsfw|nude|nudity|nutten|nympho|nymphomania|octopussy|omorashi|orgasm|orgy|paedophile|paki|pakkis|panties|panty|pedobear|pedophile|pegging|penis|pikey|pikk|pissing|pisspig|playboy|pokker|ponyplay|poof|poon|poontang|poopchute|pthc|pubes|punany|pussy|queaf|queef|quim|raghead|rape|raping|rapist|rectum|retard|rimjob|rimming|ræva|ræven|sadism|santorum|satan|scat|schlong|scissoring|semen|sex|sexcam|sexo|sexual|sexuality|sexually|sexy|shemale|shibari|shota|shrimping|sinnsykt|skeet|skitt|slanteye|slut|smut|snatch|snowballing|sodomize|sodomy|sotrør|spastic|spic|splooge|spooge|spunk|stapikk|stapikkene|stapikker|strapon|strappado|suck|sucks|svartheiteste|swastika|swinger|threesome|throating|thumbzilla|tit|tits|titties|titty|topless|tosser|towelhead|tranny|tribadism|tubgirl|tushy|twat|twink|twinkie|undressing|upskirt|urophilia|vagina|viagra|vibrator|vorarephilia|voyeur|voyeurweb|voyuer|vulva|wank|wetback|worldsex|xxx|yaoi|yiffy|zoophilia|🖕'.split('|'));
const F_PHRASES = 'alabamahotpocket|alaskanpipeline|autoerotic|babybatter|babyjuice|ballgag|ballgravy|ballkicking|balllicking|ballsack|ballsucking|barelylegal|beavercleaver|beaverlips|bigblack|bigbreasts|bigknockers|bigtits|blackcock|blondeaction|blondeonblondeaction|blowjob|blowyourload|bluewaffle|bootycall|brownshowers|brunetteaction|bulletvibe|bunghole|cameltoe|carpetmuncher|chocolaterosebuds|clevelandsteamer|cloverclamps|daterape|deepthroat|dirtypillows|dirtysanchez|doggiestyle|doggystyle|dogstyle|donkeypunch|doubledong|doublepenetration|dpaction|dryhump|eatmyass|faenihelvete|femalesquirting|footfetish|fudgepacker|fyfaen|gangbang|gaysex|giantcock|girlon|girlontop|girlscup|girlsgonewild|goddamn|goldenshower|googirl|groupsex|gspot|handjob|hardcore|hotcarl|hotchick|howtokill|howtomurder|hugefat|jackoff|jailbait|jellydonut|jerkoff|leatherrestraint|leatherstraightjacket|lemonparty|makemecome|malesquirting|menageatrois|missionaryposition|moundofvenus|mrhands|muffdiver|nignog|nsfwimages|onecuptwogirls|oneguyonejar|phonesex|pisspig|pleasurechest|polesmoker|poopchute|princealbertpiercing|ragingboner|reversecowgirl|rosypalm|rosypalmandhersisters|rustytrombone|shavedbeaver|shavedpussy|sploogemoose|spreadlegs|strapon|stripclub|styledoggy|suicidegirls|sultrywomen|taintedlove|tastemy|teabagging|tiedup|tightwhite|tongueina|tubgirl|twogirlsonecup|urethraplay|venusmound|violetwand|wetdream|whitepower|wrappingmen|wrinkledstarfish|yellowshowers'.split('|');
const F_STEMS = 'nigg|fagg|cunt|whore|hitler|jævl|jævel|fuck|shit|bitch|porn'.split('|');
// FAMILY-FILTER-END
const F_LEET = { '0': 'o', '1': 'i', '3': 'e', '4': 'a', '5': 's', '7': 't', '8': 'b', '@': 'a', '$': 's', '!': 'i' };
const F_MARKS = new RegExp('[' + String.fromCharCode(768) + '-' + String.fromCharCode(879) + ']', 'g');
function dirty(s) {
  let base = String(s || '').toLowerCase();
  try { base = base.normalize('NFD').replace(F_MARKS, ''); } catch (e) {}
  base = base.replace(/[0134578@$!]/g, (c) => F_LEET[c] || c);
  const squeezed = base.replace(/(.)\1{2,}/g, '$1');
  for (const v of (base === squeezed ? [base] : [base, squeezed])) {
    const collapsed = v.replace(/[^a-zæø]/g, '');
    if (F_STEMS.some((w) => collapsed.includes(w))) return true;
    if (F_PHRASES.some((p) => collapsed.includes(p))) return true;
    const toks = v.split(/[^a-zæø]+/).filter(Boolean);
    for (const tok of toks) { if (F_WORDS.has(tok)) return true; }
    let run = '';
    for (let i = 0; i <= toks.length; i++) {
      const t = toks[i];
      if (t && t.length === 1) { run += t; continue; }
      if (run.length >= 3 && (F_WORDS.has(run) || F_STEMS.some((w) => run.includes(w)))) return true;
      run = '';
    }
  }
  return false;
}

// strike-list matching key: lowercase, de-accent, de-leet, letters only —
// so a struck fragment catches respellings of the same stunt
function normName(s) {
  let b = String(s || '').toLowerCase();
  try { b = b.normalize('NFD').replace(F_MARKS, ''); } catch (e) {}
  return b.replace(/[0134578@$!]/g, (c) => F_LEET[c] || c).replace(/[^a-zæø]/g, '');
}

// ONE identity (Trym's call, 17 Jul): the pass name shows on the floor too.
// Defense in depth: family filter + Trym's strike list; a name that fails
// either simply doesn't travel — the banana falls back to its outfit-name.
function sanitizeName(s, strikes) {
  s = String(s || '').split('').filter((c) => {
    const k = c.charCodeAt(0);
    return k >= 32 && k !== 127;
  }).join('').trim().slice(0, 24);
  if (!s) return '';
  if (dirty(s)) return '';
  const n = normName(s);
  if (strikes.some((k) => n.includes(k))) return '';
  return s;
}

export class RaveRoom {
  constructor(state, env) {
    this.state = state;
    this.env = env; // RAVE_KEY gates the names/strike admin endpoints
    // auto-respond to pings without waking the object (hibernation-friendly)
    this.state.setWebSocketAutoResponse(
      new WebSocketRequestResponsePair('{"t":"ping"}', '{"t":"pong"}')
    );
  }

  // GHOST REAPER (12 Jul — Trym saw his own iOS zombie twice on the floor):
  // iOS drops the goodbye close-frame on quick reloads/backgrounding, so dead
  // sessions linger in the roster. Liveness = the hibernation auto-response
  // timestamp (every client pings ~30s; the runtime stamps it WITHOUT waking
  // us) — so pocket-AFK farmers stay safe and no client change is needed.
  reapStale() {
    const now = Date.now();
    for (const ws of this.state.getWebSockets()) {
      let last = 0;
      try {
        const t = this.state.getWebSocketAutoResponseTimestamp(ws);
        if (t) last = t.getTime();
      } catch (e) {}
      let a = null;
      try { a = ws.deserializeAttachment(); } catch (e) {}
      if (a && a.joined > last) last = a.joined; // fresh sockets haven't pinged yet
      if (last && now - last > 120_000) { // 4 missed pings = dead
        // close() is async — the socket stays in getWebSockets() this tick, so
        // mark the attachment dead and roster()/count filter it out NOW
        if (a) { a.dead = true; try { ws.serializeAttachment(a); } catch (e) {} }
        try { ws.close(1011, 'stale'); } catch (e) {}
        if (a) this.broadcast({ t: 'leave', id: a.id }, ws);
      }
    }
  }

  async fetch(request) {
    const url = new URL(request.url);
    if (url.pathname === '/count') {
      this.reapStale(); // the homepage door polls this — free periodic sweeps
      return new Response(JSON.stringify({ count: this.roster().length }));
    }
    // ---- Banana Mail's rave-names desk (key-gated; fails closed until Trym
    // sets the RAVE_KEY secret) ---------------------------------------------
    if (url.pathname === '/names' || url.pathname === '/strike') {
      const key = url.searchParams.get('key') || '';
      if (!this.env || !this.env.RAVE_KEY || key !== this.env.RAVE_KEY) {
        return new Response(JSON.stringify({ error: 'forbidden' }), { status: 403 });
      }
      const strikes = (await this.state.storage.get('nameStrikes')) || [];
      if (url.pathname === '/strike' && request.method === 'POST') {
        let b = {};
        try { b = JSON.parse(await request.text()); } catch (e) {}
        const frag = normName(String(b.t || '')).slice(0, 24);
        if (frag.length < 2) return new Response(JSON.stringify({ error: 'too short' }), { status: 400 });
        const next = b.remove
          ? strikes.filter((s) => s !== frag)
          : [...new Set([...strikes, frag])].slice(-200);
        await this.state.storage.put('nameStrikes', next);
        if (!b.remove) this.scrubName(frag); // the QUICK SWIPE: live floor scrub
        return new Response(JSON.stringify({ ok: true, strikes: next }));
      }
      const seen = (await this.state.storage.get('namesBySid')) || {};
      const names = Object.values(seen).sort((a, b) => b.at - a.at).map((u) => ({
        n: u.name, at: u.at, count: u.n || 1,
        vars: (u.vars || []).filter((v) => normName(v) !== normName(u.name)).slice(0, 5),
      }));
      const live = this.roster().filter((a) => a.name).map((a) => a.name);
      return new Response(JSON.stringify({ live, names, strikes }));
    }
    // internal (park + beach report every name they see here, so the Banana HQ
    // Names desk aggregates the WHOLE world in one ledger): apply the shared
    // strike list, record for the ledger, hand back the clean name (empty = struck)
    if (url.pathname === '/ingest' && request.method === 'POST') {
      let b = {};
      try { b = JSON.parse(await request.text()); } catch (e) {}
      const sid = typeof b.sid === 'string' ? b.sid.slice(0, 24) : '';
      const strikes = (await this.state.storage.get('nameStrikes')) || [];
      const name = sanitizeName(b.name, strikes);
      if (sid && name) this.recordName(sid, name);
      return new Response(JSON.stringify({ name: name || '' }));
    }
    if (request.headers.get('Upgrade') !== 'websocket') {
      return new Response('expected websocket', { status: 426 });
    }
    this.reapStale(); // ghosts must never hold seats against the cap
    if (this.roster().length >= ROOM_CAP) {
      return new Response('floor full', { status: 503 });
    }
    const pair = new WebSocketPair();
    this.state.acceptWebSocket(pair[1]);
    return new Response(null, { status: 101, webSocket: pair[0] });
  }

  roster() {
    return this.state.getWebSockets()
      .map((ws) => { try { return ws.deserializeAttachment(); } catch (e) { return null; } })
      .filter((a) => a && !a.dead);
  }

  broadcast(msg, exceptWs) {
    const s = JSON.stringify(msg);
    for (const ws of this.state.getWebSockets()) {
      if (ws === exceptWs) continue;
      try { ws.send(s); } catch (e) {}
    }
  }

  async webSocketMessage(ws, raw) {
    let msg;
    try { msg = JSON.parse(raw); } catch (e) { return; }
    if (!msg || typeof msg !== 'object') return;

    let me = null;
    try { me = ws.deserializeAttachment(); } catch (e) {}
    if (me && me.dead) return; // reaped — everyone already saw the leave; no resurrection

    if (msg.t === 'hi' && !me) {
      this.reapStale(); // every join clears the zombies before the roster ships
      // SUPERSEDE (same contract as ParkRoom): the same browser rejoining
      // kills its own ghost sockets NOW — quick park→club roundtrips were
      // stacking duplicate dancers until the reaper's sweep
      const sid = typeof msg.sid === 'string' ? msg.sid.slice(0, 24) : '';
      if (sid) {
        for (const other of this.state.getWebSockets()) {
          if (other === ws) continue;
          let a = null;
          try { a = other.deserializeAttachment(); } catch (e) {}
          if (a && !a.dead && a.sid === sid) {
            a.dead = true;
            try { other.serializeAttachment(a); } catch (e) {}
            try { other.close(1000, 'superseded'); } catch (e) {}
            this.broadcast({ t: 'leave', id: a.id }, other);
          }
        }
      }
      const strikes = (await this.state.storage.get('nameStrikes')) || [];
      const p = {
        id: crypto.randomUUID().slice(0, 8),
        sid,
        name: sanitizeName(msg.name, strikes), // '' = the outfit-name speaks
        outfit: sanitizeOutfit(msg.outfit),
        joined: Date.now(),
        // floor time carried across reconnects: iOS re-sockets on every
        // background/foreground, so gating the stage on `joined` alone made
        // the button LOOK ready (client clock) while the server said "early"
        // (fresh socket clock). The client reports its floor time; clamp it
        // and keep it AWAY from `joined` — the ghost reaper trusts `joined`
        // as the liveness floor for fresh sockets, so backdating it would get
        // newcomers reaped before their first ping.
        since: Date.now() - Math.min(Math.max(Number(msg.sess) || 0, 0), 86_400_000),
        lvl: sanLvl(msg.lvl),
        lastEmote: 0,
      };
      ws.serializeAttachment(p);
      const beerWin = (await this.state.storage.get('beerWin')) ?? null;
      const vinylWin = (await this.state.storage.get('vinylWin')) ?? null;
      const sauceWin = (await this.state.storage.get('sauceWin')) ?? null;
      const cocktailWin = (await this.state.storage.get('cocktailWin')) ?? null;
      const goldWin = (await this.state.storage.get('goldWin')) ?? null;
      const itemWin = (await this.state.storage.get('itemWin')) ?? null;
      ws.send(JSON.stringify({ t: 'roster', you: p.id, all: this.roster().map(strip), beerWin, vinylWin, sauceWin, cocktailWin, goldWin, itemWin }));
      this.broadcast({ t: 'join', p: strip(p) }, ws);
      if (p.name) this.recordName(p.sid, p.name); // the Banana Mail names-desk ledger
      return;
    }

    if (msg.t === 'beer' && me && !me.beer) { // first banana at the bar this window
      const win = happyWindow(Date.now());
      if (win < 0) return;
      // you must actually WALK to the bar. The zone is a GENEROUS anti-cheat
      // bound: the solid counter's edge scales with the client's floor width
      // (x≈50-62% on phones), so the precise at-the-counter gate lives client-
      // side and this only blocks cross-floor spoofing.
      if (!(typeof me.x === 'number' && me.x < 70 && typeof me.y === 'number' && me.y > 64)) return;
      if (this.beerWin === win) return;   // sync fast-path — two claims in the same window can't both pass
      this.beerWin = win;                 // claim in-memory BEFORE any await (DO interleaves at await points)
      const stored = await this.state.storage.get('beerWin');
      if (stored === win) return;         // claimed before a hibernation wipe of the instance field
      await this.state.storage.put('beerWin', win);
      me.beer = true;
      me.outfit.extras = { ...(me.outfit.extras || {}), beer: true };
      ws.serializeAttachment(me);
      this.broadcast({ t: 'beer', id: me.id });
      return;
    }

    if (msg.t === 'emote' && me && EMOTES.includes(msg.k)) {
      if (msg.k === 'fire' && !me.stage) return; // the 🔥 is earned, not given
      const now = Date.now();
      if (now - (me.lastEmote || 0) < 1500) return; // throttle: no spam cannons
      me.lastEmote = now;
      ws.serializeAttachment(me);
      this.broadcast({ t: 'emote', id: me.id, k: msg.k });
      return;
    }

    // 🌈 the rainbow-jelly flyby: cosmetic relay like the grab shout — the
    // catcher's banana does the nyan run on EVERY floor. Rainbows are ~1/60
    // jellies; the throttle just stops a devtools user painting the sky.
    if (msg.t === 'nyan' && me) {
      const now = Date.now();
      if (now - (me.lastNyan || 0) < 20000) return;
      me.lastNyan = now;
      ws.serializeAttachment(me);
      this.broadcast({ t: 'nyan', id: me.id }, ws);
      return;
    }

    // 📸 PHOTO TIME's shared shot: the snapper broadcasts only the FRAME
    // COORDS — every client composites the photo locally from its own roster,
    // so no image ever crosses the wire (nothing arbitrary can reach the LED).
    if (msg.t === 'photosnap' && me) {
      const now = Date.now();
      if (now - (me.lastSnap || 0) < 30000) return;   // one shot per snapper / 30s
      me.lastSnap = now;
      ws.serializeAttachment(me);
      const c = (v, lo, hi) => Math.max(lo, Math.min(hi, Number(v) || 0));
      this.broadcast({ t: 'photosnap', id: me.id,
        x0: c(msg.x0, 0, 100), y0: c(msg.y0, 0, 100),
        x1: c(msg.x1, 0, 100), y1: c(msg.y1, 0, 100) }, ws);
      return;
    }

    if (msg.t === 'move' && me) { // walking: position relay, sender echoes locally
      const x = Number(msg.x), y = Number(msg.y);
      if (!Number.isFinite(x) || !Number.isFinite(y)) return;
      const now = Date.now();
      if (now - (me.lastMove || 0) < 100) return; // rate guard: client sends at 150ms
      me.lastMove = now;
      me.x = Math.min(96, Math.max(4, Math.round(x * 10) / 10));
      me.y = Math.min(92, Math.max(6, Math.round(y * 10) / 10));
      ws.serializeAttachment(me);
      this.broadcast({ t: 'move', id: me.id, x: me.x, y: me.y }, ws);
      return;
    }

    if (msg.t === 'vinyl' && me && !me.vinyl) { // first banana to the lost record
      const win = vinylWindow(Date.now());
      if (win < 0) return;
      if (this.vinylWin === win) return;      // sync guard before any await
      const spot = vinylSpot(win);
      if (!(typeof me.x === 'number' && Math.abs(me.x - spot.x) < 14 && typeof me.y === 'number' && Math.abs(me.y - spot.y) < 14)) return;
      this.vinylWin = win;
      const stored = await this.state.storage.get('vinylWin');
      if (stored === win) return;
      await this.state.storage.put('vinylWin', win);
      me.vinyl = true;
      ws.serializeAttachment(me);
      this.broadcast({ t: 'vinyl', id: me.id });
      return;
    }

    if (msg.t === 'item' && me) { // first banana to this window's conveyor item
      const win = itemWindow(Date.now());
      if (win < 0) return;
      if (this.itemWin === win) return;       // sync guard before any await
      const spot = itemSpot(win);
      if (!(typeof me.x === 'number' && Math.abs(me.x - spot.x) < 14 && typeof me.y === 'number' && Math.abs(me.y - spot.y) < 14)) return;
      this.itemWin = win;
      const stored = await this.state.storage.get('itemWin');
      if (stored === win) return;
      await this.state.storage.put('itemWin', win);
      const kind = itemType(win);
      if (ITEM_FX[kind]) {
        me.fx = { id: ITEM_FX[kind], until: Date.now() + fxLen(ITEM_FX[kind]) };
        ws.serializeAttachment(me);
      }
      this.broadcast({ t: 'item', id: me.id, win, kind, fx: ITEM_FX[kind] ? me.fx : undefined });
      return;
    }

    // legacy: pre-conveyor clients still send 'sauce' against the old windows
    if (msg.t === 'sauce' && me) { // first banana to the hot-sauce bottle
      const win = sauceWindow(Date.now());
      if (win < 0) return;
      if (this.sauceWin === win) return;      // sync guard before any await
      const spot = sauceSpot(win);
      if (!(typeof me.x === 'number' && Math.abs(me.x - spot.x) < 14 && typeof me.y === 'number' && Math.abs(me.y - spot.y) < 14)) return;
      this.sauceWin = win;
      const stored = await this.state.storage.get('sauceWin');
      if (stored === win) return;
      await this.state.storage.put('sauceWin', win);
      me.fx = { id: 'flames', until: Date.now() + fxLen('flames') };
      ws.serializeAttachment(me);
      this.broadcast({ t: 'fx', id: me.id, fx: me.fx, src: 'sauce' });
      return;
    }

    if (msg.t === 'gold' && me) { // first banana to the golden one
      const win = goldWindow(Date.now());
      if (win < 0) return;
      if (this.goldWin === win) return;       // sync guard before any await
      const spot = goldSpot(win);
      if (!(typeof me.x === 'number' && Math.abs(me.x - spot.x) < 14 && typeof me.y === 'number' && Math.abs(me.y - spot.y) < 14)) return;
      this.goldWin = win;
      const stored = await this.state.storage.get('goldWin');
      if (stored === win) return;
      await this.state.storage.put('goldWin', win);
      this.broadcast({ t: 'gold', id: me.id });
      return;
    }

    if (msg.t === 'grab' && me) { // a raver caught a wearable DROP — a cosmetic
      // floor-wide shout only (the catch itself is client-authoritative; the
      // caught item rides in on the normal 'outfit' broadcast). No state, no race.
      // curated drops validate against DROP_IDS; community catalog items are
      // format-validated (clients resolve the label from the public manifest)
      if (typeof msg.item !== 'string' || !(DROP_IDS.includes(msg.item) || /^c_[a-f0-9]{6,32}$/.test(msg.item))) return;
      this.broadcast({ t: 'grab', id: me.id, item: msg.item });
      return;
    }

    if (msg.t === 'cocktail' && me) { // first banana at the bar during specials
      const win = specialWindow(Date.now());
      if (win < 0) return;
      if (this.cocktailWin === win) return;   // sync guard before any await
      // same generous walk-to-the-bar bound as the beer (client gates precisely)
      if (!(typeof me.x === 'number' && me.x < 70 && typeof me.y === 'number' && me.y > 64)) return;
      this.cocktailWin = win;
      const stored = await this.state.storage.get('cocktailWin');
      if (stored === win) return;
      await this.state.storage.put('cocktailWin', win);
      const drink = COCKTAILS[((win % COCKTAILS.length) + COCKTAILS.length) % COCKTAILS.length];
      me.fx = { id: drink, until: Date.now() + fxLen(drink) };
      ws.serializeAttachment(me);
      this.broadcast({ t: 'fx', id: me.id, fx: me.fx, src: 'cocktail' });
      return;
    }

    if (msg.t === 'vinylDrop' && me && me.vinyl) { // courier reached the stage edge
      if (!(typeof me.y === 'number' && me.y < 18 && me.x > 26 && me.x < 74)) return;
      me.vinyl = false;
      ws.serializeAttachment(me);
      this.broadcast({ t: 'minidrop', id: me.id });
      return;
    }

    if (msg.t === 'stage' && me) {
      if (msg.on) {
        if (Date.now() - (me.since || me.joined) < STAGE_MIN_MS) { // since = floor time across reconnects
          ws.send('{"t":"stageNo","reason":"early"}');
          return;
        }
        if (this.roster().filter((p) => p.stage).length >= STAGE_CAP) {
          ws.send('{"t":"stageNo","reason":"full"}');
          return;
        }
        me.stage = true;
      } else {
        me.stage = false;
      }
      ws.serializeAttachment(me);
      this.broadcast({ t: 'stage', id: me.id, on: me.stage }); // includes sender = server-authoritative echo
      return;
    }

    if (msg.t === 'lvl' && me) { // levelled up mid-rave — the roster title updates live
      const n = sanLvl(msg.n);
      if (!n || n === me.lvl) return;
      if (me.lvl && n < me.lvl) return; // levels only climb (no-decay rule, enforced here too)
      me.lvl = n;
      ws.serializeAttachment(me);
      this.broadcast({ t: 'lvl', id: me.id, n });
      return;
    }

    // 🍌💨 THE FOOD FIGHT relay — pure fan-out, no physics here. Clients
    // simulate every throw; the VICTIM announces its own splat (their jelly
    // is a local stat, so victim-authority is the only honest model — a
    // cheater can dodge but never hurt). Throttles match the client cooldown.
    if (msg.t === 'shot' && me) {
      const nowS = Date.now();
      if (me.lastShot && nowS - me.lastShot < 1800) return;
      me.lastShot = nowS;
      ws.serializeAttachment(me);
      const a = Number(msg.a);
      if (!isFinite(a)) return;
      this.broadcast({ t: 'shot', id: me.id, a: +a.toFixed(3) }, ws);
      return;
    }
    if (msg.t === 'splat' && me) {
      const nowS = Date.now();
      if (me.lastSplat && nowS - me.lastSplat < 900) return;
      me.lastSplat = nowS;
      ws.serializeAttachment(me);
      const n = Math.min(20, Math.max(0, Math.round(Number(msg.n) || 0)));
      const by = /^[a-f0-9-]{4,12}$/.test(String(msg.by || '')) ? msg.by : '';
      this.broadcast({ t: 'splat', id: me.id, by, n, s: (Number(msg.s) >>> 0) });
      return;
    }

    if (msg.t === 'outfit' && me) { // changed clothes mid-rave (via builder link back)
      const strikes = (await this.state.storage.get('nameStrikes')) || [];
      me.name = sanitizeName(msg.name !== undefined ? msg.name : me.name, strikes);
      if (me.name) this.recordName(me.sid, me.name);
      me.outfit = sanitizeOutfit(msg.outfit);
      if (msg.sober) { me.beer = false; me.fx = undefined; } // the water: a clean slate is a CLEAN slate
      if (me.beer) me.outfit.extras.beer = true; // the beer survives a wardrobe change
      ws.serializeAttachment(me);
      this.broadcast({ t: 'outfit', id: me.id, outfit: me.outfit, name: me.name || '' });
    }
  }

  // the QUICK SWIPE: a fresh strike sweeps the live floor — matching names
  // vanish immediately (their bananas fall back to outfit-names)
  scrubName(frag) {
    for (const ws of this.state.getWebSockets()) {
      let a = null;
      try { a = ws.deserializeAttachment(); } catch (e) {}
      if (a && !a.dead && a.name && normName(a.name).includes(frag)) {
        a.name = '';
        try { ws.serializeAttachment(a); } catch (e) {}
        this.broadcast({ t: 'name', id: a.id, name: '' });
      }
    }
  }

  // rolling ledger of names seen on the floor (for the Banana Mail desk).
  // ⚠️ Keyed by SID, not by the name string — a visitor who renames is the SAME
  // visitor (the sid survives renames + reconnects), so one row per person, not
  // one per name. We keep the current name, a count of genuinely different names
  // they've worn, and the recent variations (a name-cycler is a moderation
  // signal, and the previous names still get a look). Capped to 300 visitors.
  async recordName(sid, name) {
    if (!sid || !name) return;
    try {
      const seen = (await this.state.storage.get('namesBySid')) || {};
      const cur = seen[sid] || { name: '', at: 0, n: 0, vars: [] };
      const fresh = normName(name) !== normName(cur.name); // a real change, not re-decoration
      let vars = cur.vars || [];
      if (fresh && cur.name) vars = [cur.name, ...vars.filter((v) => normName(v) !== normName(cur.name))].slice(0, 6);
      seen[sid] = { name, at: Date.now(), n: (cur.n || 0) + (fresh ? 1 : 0), vars };
      const entries = Object.entries(seen).sort((a, b) => b[1].at - a[1].at).slice(0, 300);
      await this.state.storage.put('namesBySid', Object.fromEntries(entries));
    } catch (e) {}
  }

  async webSocketClose(ws) {
    let me = null;
    try { me = ws.deserializeAttachment(); } catch (e) {}
    if (me && !me.dead) this.broadcast({ t: 'leave', id: me.id }, ws); // reaped ghosts already announced their leave
  }

  async webSocketError(ws) {
    return this.webSocketClose(ws);
  }
}

function strip(p) {
  return {
    id: p.id, outfit: p.outfit, joined: p.joined, stage: !!p.stage, vinyl: !!p.vinyl, x: p.x, y: p.y,
    fx: p.fx && p.fx.until > Date.now() ? p.fx : undefined, // active effects survive a rejoin, expired ones don't travel
    lvl: p.lvl || undefined, // club level (REP) — titles show on the floor roster
    name: p.name || undefined, // the pass name (ONE identity) — sanitized at entry
  };
}

// ============================================================================
// 🌳 THE PARK — the room outside the banana stand (S5). Deliberately tiny:
// join / move / outfit / leave, same hibernation + reaper + sanitizers as the
// floor, NONE of the event machinery (no drops, no happy hour, no quests —
// the park's life is client-side: ducks, birds, the keeper).
const PARK_CAP = 40;
// The bay is 2760×1100 — nine times the park's pitch — so it can carry more
// bananas before it reads as a crowd. Still well under the ~150/room ceiling
// the cost model sets (banana-world-engineering).
const BEACH_CAP = 60;

export class ParkRoom {
  constructor(state, env) {
    this.state = state;
    this.env = env; // RAVE binding — reports the names seen here to the shared HQ ledger
    this.state.setWebSocketAutoResponse(
      new WebSocketRequestResponsePair('{"t":"ping"}', '{"t":"pong"}')
    );
  }

  reapStale() {
    const now = Date.now();
    for (const ws of this.state.getWebSockets()) {
      let last = 0;
      try {
        const t = this.state.getWebSocketAutoResponseTimestamp(ws);
        if (t) last = t.getTime();
      } catch (e) {}
      let a = null;
      try { a = ws.deserializeAttachment(); } catch (e) {}
      if (a && a.joined > last) last = a.joined;
      if (last && now - last > 120_000) {
        if (a) { a.dead = true; try { ws.serializeAttachment(a); } catch (e) {} }
        try { ws.close(1011, 'stale'); } catch (e) {}
        if (a) this.broadcast({ t: 'leave', id: a.id }, ws);
      }
    }
  }

  roster() {
    return this.state.getWebSockets()
      .map((ws) => { try { return ws.deserializeAttachment(); } catch (e) { return null; } })
      .filter((a) => a && !a.dead);
  }

  broadcast(msg, exceptWs) {
    const s = JSON.stringify(msg);
    for (const ws of this.state.getWebSockets()) {
      if (ws === exceptWs) continue;
      try { ws.send(s); } catch (e) {}
    }
  }

  async fetch(request) {
    const url = new URL(request.url);
    if (url.pathname === '/count') {
      this.reapStale(); // headcount checks double as free sweeps
      return new Response(JSON.stringify({ count: this.roster().length }));
    }
    if (url.pathname === '/rosternames') { // HQ Names desk: who's named here right now
      return new Response(JSON.stringify({ names: this.roster().filter((a) => a.name).map((a) => a.name) }));
    }
    if (url.pathname.startsWith('/garden')) return this.garden(request, url);
    if (request.headers.get('Upgrade') !== 'websocket') {
      return new Response('expected websocket', { status: 426 });
    }
    this.reapStale();
    if (this.roster().length >= PARK_CAP) {
      return new Response('park full', { status: 503 });
    }
    const pair = new WebSocketPair();
    this.state.acceptWebSocket(pair[1]);
    return new Response(null, { status: 101, webSocket: pair[0] });
  }

  // ---- 🌱 THE GARDEN (P3b) — shared slots in DO storage, wall-clock growth
  // Coins stay client-authoritative (no real money); the server only keeps
  // the shared plot truth: who planted what, when, and who watered it.
  async garden(request, url) {
    const json = (o, status = 200) => new Response(JSON.stringify(o), {
      status, headers: { 'Content-Type': 'application/json' },
    });
    let slots = (await this.state.storage.get('garden')) || [];
    if (!Array.isArray(slots)) slots = [];
    // the garden grew 8 → 16 (W3, site B) → 24 (site C NE): stored arrays PAD
    // on read — low indices must never reindex, live plants sit there
    while (slots.length < GARDEN_SLOTS) slots.push(null);
    slots = slots.slice(0, GARDEN_SLOTS);
    const now = Date.now();
    // wilt sweep: unwatered too long → the slot frees itself on the next
    // read; higher ⭐ holds out longer (3 + floor(stars/2) dry days)
    let dirty = false;
    for (let i = 0; i < GARDEN_SLOTS; i++) {
      const w = slots[i];
      const allow = (3 + Math.floor(gardenSeed(w && w.seed).stars / 2)) * 86_400_000;
      if (w && now - (w.lastWater || w.plantedAt || 0) > allow) { slots[i] = null; dirty = true; }
    }
    // 🌾 RIPE EXPIRY — the OTHER way a slot frees itself, and the one that
    // actually matters at ad scale. A ready plant can only be harvested by its
    // grower, so one planted by somebody who never comes back sits in a shared
    // bed forever — and the +2 rep stranger-watering mechanic KEEPS IT ALIVE
    // while it does, so the wilt sweep above never reaches it. Left alone, a
    // busy park silts up with orphans and nobody can ever plant again.
    // ⚠️ NOT A PUNISHMENT: the crop waits in `compost` and pays out the moment
    // that grower next walks in. You lose the slot, never the harvest.
    const cmp = (await this.state.storage.get('compost')) || {};
    let cmpDirty = false;
    for (let i = 0; i < GARDEN_SLOTS; i++) {
      const w = slots[i];
      if (!w || w.rot) continue;                      // a storm's ruin is a CHORE, not a crop
      const sd = gardenSeed(w.seed);
      if (now - (w.plantedAt || 0) < sd.days * 86_400_000 + RIPE_TTL) continue;
      const c = cmp[w.passShort] || { n: 0, stars: 0, at: 0 };
      c.n++;
      c.stars += sd.stars;
      c.at = now;
      cmp[w.passShort] = c;
      slots[i] = null;
      dirty = true;
      cmpDirty = true;
    }
    // bounded like every other per-pass map here — oldest debts drop first
    if (cmpDirty) {
      const ck = Object.keys(cmp);
      if (ck.length > 400) {
        ck.sort((a, b) => cmp[a].at - cmp[b].at).slice(0, ck.length - 400).forEach((k) => delete cmp[k]);
      }
    }
    // who is asking — set here for a GET, re-set from the body on a POST
    let asking = (url.searchParams.get('pass') || '').slice(0, 8);
    // 🌿 weeds + 🌸 bloom ride the same read: lazy decay, catch-up spawns.
    // ⭐ every living plant FEEDS the meter by its stars (post-wilt-sweep, so
    // only plants that made it through count)
    const wd = (await this.state.storage.get('weeds')) || { list: [], nextAt: 0 };
    // 🫧 algae + 🐦 birdhouses load BEFORE the decay — live patches drag it,
    // freshly-stocked houses feed it
    const alg = (await this.state.storage.get('algae')) || { list: [], nextAt: 0 };
    // 🗑 litter loads here too (its SPAWN block still runs below, where it can
    // see the fresh bl.v) because the tidiness ceiling counts it
    const tr = (await this.state.storage.get('trash')) || { list: [], nextAt: 0 };
    // 🍂 leaves + 🌼 border flowers likewise — a storm wrecks both, and the
    // weather pass runs before every spawner so the new bl.v picks the bands
    const lv = (await this.state.storage.get('leaves')) || { list: [], nextAt: 0 };
    const bd = (await this.state.storage.get('border')) || { list: [] };
    const hs = (await this.state.storage.get('houses')) || { list: [] };
    const bl = (await this.state.storage.get('bloom')) || { v: 70, at: now };
    const hrs = Math.max(0, (now - bl.at) / 3600_000);
    const decayed = hrs > 0.001;
    if (decayed) {
      // ⚠️ 30 Jul: only plants WATERED in the last 24h feed the bloom — a
      // stocked garden otherwise beat max decay forever; the daily watering
      // round is what keeps the park's engine running.
      const stars = slots.reduce((t, s2) =>
        t + (s2 && !s2.rot && now - (s2.lastWater || s2.plantedAt || 0) < 24 * 3600_000
          ? gardenSeed(s2.seed).stars : 0), 0);
      // ⭐ SATURATING FEED (31 Jul, w/ 64 slots the old linear feed would let
      // the boxes carry the park alone): feed = MAX·stars/(stars+K) — see
      // FEED_MAX/FEED_K for the napkin. Watered stars asymptote at 1.1/h;
      // decay can always win if watering stops.
      // 🐦 + stocked birdhouses (<24h, the daily ritual) at BH_FEED each
      const stocked = hs.list.filter((h2) => now - (h2.lastStock || 0) < 24 * 3600_000).length;
      const feed = BLOOM_FEED_MAX * stars / (stars + BLOOM_FEED_K) + BH_FEED * stocked;
      bl.v = Math.min(tidyCeil(wd.list, alg.list, tr.list), Math.max(BLOOM_FLOOR,
        bl.v - hrs * (BLOOM_BASE_DRIFT + BLOOM_WEED_DRAG * wd.list.length
          + ALGAE_DRAG * alg.list.length - feed)));
      bl.at = now;
    }

    // 🌦 WEATHER — walked across the elapsed window, so events nobody was
    // present for still land. The clock above is a pure function of time and is
    // mirrored in src/lib/world.js, so the client renders the very same rain.
    // ⚠️ ONE-OFF HITS, NEVER A RATE: events run 8-26 minutes and this park's
    // economy lives in ±1/h, so any sane rate over 20 minutes is invisible.
    // ⚠️ the hit SCALES WITH CURRENT HEALTH, so a pristine park falls the whole
    // way and a struggling one is not kicked while it is down.
    const wxSeen = (await this.state.storage.get('wxAt')) || 0;
    let wxDirty = !wxSeen, stormAt = (await this.state.storage.get('lastStormAt')) || 0;
    if (wxSeen && now > wxSeen) {
      for (const ev of weatherBetween(wxSeen, now)) {
        if (ev.type === 'drizzle') continue;               // cosmetic, always
        // ⭐ RAIN WATERS EVERY BED (Trym's Stardew rule). A GIFT that partly pays
        // for the hit — a rain-watered garden feeds the bloom again for 24h. If
        // the garden ever starts riding on weather instead of people, turn the
        // 24h watering window DOWN; do not weaken the rain.
        for (const s2 of slots) if (s2 && !s2.rot) { s2.lastWater = Math.max(s2.lastWater || 0, ev.at); dirty = true; }
        const to = ev.type === 'storm' ? WX_STORM_TO : WX_HEAVY_TO;
        // ⚠️ ONLY EVER DOWNWARD. The scaled pull reads v - (v-to)·(v/100), which
        // pushes UP whenever v < to — so without this guard heavy rain would
        // REVIVE a dying park to 50%. Weather damages; it never heals.
        if (bl.v > to) bl.v = Math.max(BLOOM_FLOOR, bl.v - (bl.v - to) * (bl.v / 100));
        if (ev.type === 'storm') { stormAt = ev.at; stormWreck(slots, bd, wd, tr, lv, hs, ev.at); }
      }
      wxDirty = true;
      dirty = true;   // ⚠️ the other *Dirty flags are declared BELOW this block —
                      // touching them here is a TDZ ReferenceError. wxDirty
                      // covers the storm's weeds/litter/leaves/pots instead.
    }

    // 🌿 WEEDS 2.0 — cadence + cap by bloom band (the dead park is overrun),
    // growth = EXPAND near a parent / POLLINATE far / SEED an empty map
    // ⚠️ 31 Jul: one notch harder again (more beds = more hands expected) —
    // healthy park grows ~7-8 weeds/hour; caps scaled with the notch
    const [weedEvery, weedCap] = bl.v >= 80 ? [8 * 60_000, 20]
      : bl.v >= 60 ? [390_000, 26]
        : bl.v >= 40 ? [5 * 60_000, 40]
          : [4 * 60_000, 80];
    if (!wd.nextAt || wd.nextAt < now - 86_400_000) wd.nextAt = now + weedEvery;
    let weedsDirty = false;
    const weedTaken = new Set(wd.list.map((w2) => w2.x + ',' + w2.y));
    const weedSpawn = () => {
      let pt = null;
      if (!wd.list.length || Math.random() < WEED_POLLINATE) {
        // SEED / POLLINATE: any free grid point, however far (crosses roads)
        const g = WEED_GRID[Math.floor(Math.random() * WEED_GRID.length)];
        if (!weedTaken.has(g[0] + ',' + g[1])) pt = g;
      } else {
        // EXPAND: a child beside a random living parent — this makes patches
        const par = wd.list[Math.floor(Math.random() * wd.list.length)];
        const near = WEED_GRID.filter((g) => !weedTaken.has(g[0] + ',' + g[1])
          && (g[0] - par.x) * (g[0] - par.x) + (g[1] - par.y) * (g[1] - par.y) <= WEED_NEAR * WEED_NEAR);
        if (near.length) pt = near[Math.floor(Math.random() * near.length)];
      }
      if (!pt) return;   // boxed-in parent / taken point — the slot just passes
      weedTaken.add(pt[0] + ',' + pt[1]);
      wd.list.push({ id: crypto.randomUUID().slice(0, 8), x: pt[0], y: pt[1], bornAt: now });
    };
    while (now >= wd.nextAt && wd.list.length < weedCap) {
      weedSpawn();
      wd.nextAt += weedEvery;
      weedsDirty = true;
    }
    if (now >= wd.nextAt) { wd.nextAt = now + weedEvery; weedsDirty = true; }
    // 🗑 GARBAGE rides the weed infrastructure: same grid, own list, cap
    // INVERTED by bloom (healthy park = near-spotless, dead park = littered),
    // cadence 2× the weed beat. Pieces persist until somebody walks them off.
    let trashDirty = false;
    const trashCap = bl.v >= 80 ? 4 : bl.v >= 60 ? 12 : bl.v >= 40 ? 18 : 24;   // 2x, Trym 30 Jul
    const trashEvery = Math.max(1, Math.floor(weedEvery / 2));
    if (!tr.nextAt || tr.nextAt < now - 86_400_000) tr.nextAt = now + trashEvery;
    const trashTaken = new Set([...tr.list, ...wd.list].map((t) => t.x + ',' + t.y));
    while (now >= tr.nextAt && tr.list.length < trashCap) {
      const g = WEED_GRID[Math.floor(Math.random() * WEED_GRID.length)];
      if (!trashTaken.has(g[0] + ',' + g[1])) {
        trashTaken.add(g[0] + ',' + g[1]);
        tr.list.push({ id: crypto.randomUUID().slice(0, 8), x: g[0], y: g[1],
          v: 1 + Math.floor(Math.random() * 3), bornAt: now });
      }
      tr.nextAt += trashEvery;
      trashDirty = true;
    }
    if (now >= tr.nextAt) { tr.nextAt = now + trashEvery; trashDirty = true; }
    // 🫧 POND ALGAE — the weed grammar on water: scum patches on the
    // ALGAE_SPOTS lattice, ~half the weed beat per band, each live patch
    // drags the bloom ALGAE_DRAG/h until somebody walks to the bank and skims
    let algaeDirty = false;
    const [algEvery, algCap] = bl.v >= 80 ? [16 * 60_000, 6]
      : bl.v >= 60 ? [13 * 60_000, 8]
        : bl.v >= 40 ? [10 * 60_000, 10]
          : [8 * 60_000, 14];
    if (!alg.nextAt || alg.nextAt < now - 86_400_000) alg.nextAt = now + algEvery;
    const algTaken = new Set(alg.list.map((a2) => a2.x + ',' + a2.y));
    while (now >= alg.nextAt && alg.list.length < algCap) {
      const sp = ALGAE_SPOTS[Math.floor(Math.random() * ALGAE_SPOTS.length)];
      if (!algTaken.has(sp[0] + ',' + sp[1])) {
        algTaken.add(sp[0] + ',' + sp[1]);
        alg.list.push({ id: crypto.randomUUID().slice(0, 8), x: sp[0], y: sp[1], bornAt: now });
      }
      alg.nextAt += algEvery;
      algaeDirty = true;
    }
    if (now >= alg.nextAt) { alg.nextAt = now + algEvery; algaeDirty = true; }
    // 🍂 LEAF PILES — sad-phase texture on the weed grid: they exist only
    // below 60 bloom (recovery accelerant + autumn dressing, never a
    // permanent chore) and sweep themselves once the park recovers past 65
    // (the 60/65 gap = hysteresis, no border flap)
    let leavesDirty = false;
    if (bl.v >= 65 && lv.list.length) { lv.list = []; lv.nextAt = 0; leavesDirty = true; }
    if (bl.v < 60) {
      const leafCap = bl.v >= 40 ? 8 : 14;
      const leafEvery = trashEvery;   // ~the trash beat
      if (!lv.nextAt || lv.nextAt < now - 86_400_000) lv.nextAt = now + leafEvery;
      const lvTaken = new Set([...lv.list, ...tr.list, ...wd.list].map((t) => t.x + ',' + t.y));
      while (now >= lv.nextAt && lv.list.length < leafCap) {
        const g = WEED_GRID[Math.floor(Math.random() * WEED_GRID.length)];
        if (!lvTaken.has(g[0] + ',' + g[1])) {
          lvTaken.add(g[0] + ',' + g[1]);
          lv.list.push({ id: crypto.randomUUID().slice(0, 8), x: g[0], y: g[1], bornAt: now });
        }
        lv.nextAt += leafEvery;
        leavesDirty = true;
      }
      if (now >= lv.nextAt) { lv.nextAt = now + leafEvery; leavesDirty = true; }
    }
    // 🥚 W2 EGGS ride the same lazy read: expire the stale, lay by bloom band
    const eg = (await this.state.storage.get('eggs')) || { list: [], nextAt: 0 };
    let eggsDirty = false;
    const alive = eg.list.filter((e) => now - e.bornAt < EGG_TTL);
    if (alive.length !== eg.list.length) { eg.list = alive; eggsDirty = true; }
    const eggEvery = bl.v >= 80 ? EGG_EVERY_4 : bl.v >= 60 ? EGG_EVERY_3 : bl.v >= 40 ? EGG_EVERY_2 : 0;
    if (!eggEvery) {
      if (eg.nextAt) { eg.nextAt = 0; eggsDirty = true; }   // park too sad to lay
    } else if (!eg.nextAt) {
      eg.nextAt = now + eggEvery;
      eggsDirty = true;
    } else if (now >= eg.nextAt) {
      if (eg.list.length < EGG_CAP) {
        const taken = new Set(eg.list.map((e) => e.x + ',' + e.y));
        const free = EGG_SPOTS.filter((sp) => !taken.has(sp[0] + ',' + sp[1]));
        if (free.length) {
          const sp = free[Math.floor(Math.random() * free.length)];
          eg.list.push({
            id: crypto.randomUUID().slice(0, 8), x: sp[0], y: sp[1],
            ...(bl.v >= EGG_GOLD_AT ? { g: 1 } : {}), bornAt: now,
          });
        }
      }
      eg.nextAt = now + eggEvery;
      eggsDirty = true;
    }
    // 🌼 border flowers — pure decoration with a name on it; expiry on read
    // (~7 days) frees the spot for the next planter

    let borderDirty = false;
    const bAlive = bd.list.filter((f) => now - f.at < BORDER_TTL);
    if (bAlive.length !== bd.list.length) { bd.list = bAlive; borderDirty = true; }
    const strip = (s) => (s ? {
      passShort: s.passShort, name: s.name, seed: s.seed,
      plantedAt: s.plantedAt, lastWater: s.lastWater, ...(s.rot ? { rot: s.rot } : {}),
      waterers: (s.waterers || []).length,
    } : null);
    const payload = (extra) => ({
      slots: slots.map(strip),
      // the ceiling again, on the CURRENT lists: a chore's reply then shows
      // the tidier number straight away instead of waiting for the next read.
      // ⚠️ ONE DECIMAL, not a whole number (Trym: "the progress bar should
      // weigh small things aswell, not just … phases and chunks"). One weed is
      // worth 0.3 of the ceiling, so at integer resolution most single chores
      // moved nothing at all. The BAR rides the decimal; every label rounds it.
      bloom: Math.round(Math.min(bl.v, tidyCeil(wd.list, alg.list, tr.list)) * 10) / 10,
      weeds: wd.list.map((w2) => ({ id: w2.id, x: w2.x, y: w2.y })),
      trash: tr.list.map((t) => ({ id: t.id, x: t.x, y: t.y, v: t.v })),
      eggs: eg.list.map((e) => ({ id: e.id, x: e.x, y: e.y, ...(e.g ? { g: 1 } : {}) })),
      border: bd.list.map((f) => ({ spot: f.spot, kind: f.kind, name: f.name, at: f.at,
        ...(f.rot ? { rot: f.rot } : {}) })),
      algae: alg.list.map((a2) => ({ id: a2.id, x: a2.x, y: a2.y })),
      leaves: lv.list.map((l2) => ({ id: l2.id, x: l2.x, y: l2.y })),
      stormAt,
      houses: hs.list.map((h2) => ({ spot: h2.spot, name: h2.name,
        passShort: h2.passShort, builtAt: h2.builtAt, lastStock: h2.lastStock || 0,
        stockers: (h2.stockers || []).length })),
      ...extra,
    });
    // 🌱 what the compost owes the asker, handed over once and cleared.
    // ⚠️ THE READ ONLY, never a POST reply: payload() also builds ERROR bodies,
    // and a 409 the client throws away would silently eat somebody's harvest.
    // The poll runs on arrival anyway, so it lands the moment they walk in and
    // find the bed empty — the only moment the message explains anything.
    function compostFor() {
      const c = asking && cmp[asking];
      if (!c || !c.n) return {};
      delete cmp[asking];
      cmpDirty = true;
      return { compost: { n: c.n, stars: c.stars } };
    }
    const persist = async () => {
      await this.state.storage.put('garden', slots);
      await this.state.storage.put('compost', cmp);
      await this.state.storage.put('weeds', wd);
      await this.state.storage.put('trash', tr);
      await this.state.storage.put('bloom', bl);
      await this.state.storage.put('eggs', eg);
      await this.state.storage.put('border', bd);
      await this.state.storage.put('algae', alg);
      await this.state.storage.put('leaves', lv);
      await this.state.storage.put('houses', hs);
      await this.state.storage.put('wxAt', now);
      if (stormAt) await this.state.storage.put('lastStormAt', stormAt);
    };
    if (url.pathname === '/garden' && request.method !== 'POST') {
      const body = payload(compostFor());
      if (dirty || weedsDirty || decayed || eggsDirty || trashDirty || borderDirty
        || algaeDirty || leavesDirty || wxDirty || cmpDirty) await persist();
      return json(body);
    }
    let b = null;
    try { b = JSON.parse(await request.text()); } catch (e) {}
    if (!b || typeof b !== 'object') return json({ err: 'bad body' }, 400);
    // 🚀 THE LAUNCH RESET — one-shot admin route for the go-live flip: the
    // park opens DEAD (bloom at the floor, overrun with weeds, beds bare).
    // Guarded by the LAUNCH_KEY secret (wrangler secret put LAUNCH_KEY);
    // additive-only, no client ever calls it. POST /park-garden/launchreset
    // { key } — 403 without the exact key.
    if (url.pathname === '/garden/launchreset') {
      if (!this.env || !this.env.LAUNCH_KEY || b.key !== this.env.LAUNCH_KEY) {
        return json({ err: 'forbidden' }, 403);
      }
      for (let k = 0; k < GARDEN_SLOTS; k++) slots[k] = null;
      bl.v = BLOOM_FLOOR;
      bl.at = now;
      // overgrown from minute one: fill to the dead-park cap in PATCHES —
      // ~8 seed centers, then children beside living parents (the organism's
      // own expansion rule), a few far jumps. Organic overgrowth, not confetti.
      wd.list = [];
      wd.nextAt = 0;
      const rtaken = new Set();
      const sprout = (pt) => {
        rtaken.add(pt[0] + ',' + pt[1]);
        wd.list.push({ id: crypto.randomUUID().slice(0, 8), x: pt[0], y: pt[1], bornAt: now });
      };
      let guard = 0;
      while (wd.list.length < 60 && guard++ < 5000) {
        if (wd.list.length < 8 || Math.random() < 0.06) {
          const g = WEED_GRID[Math.floor(Math.random() * WEED_GRID.length)];
          if (!rtaken.has(g[0] + ',' + g[1])) sprout(g);
        } else {
          const par = wd.list[Math.floor(Math.random() * wd.list.length)];
          const near = WEED_GRID.filter((g) => !rtaken.has(g[0] + ',' + g[1])
            && (g[0] - par.x) * (g[0] - par.x) + (g[1] - par.y) * (g[1] - par.y) <= WEED_NEAR * WEED_NEAR);
          if (near.length) sprout(near[Math.floor(Math.random() * near.length)]);
        }
      }
      tr.list = [];
      tr.nextAt = 0;   // re-arms at the dead-park cadence on the next read
      eg.list = [];
      eg.nextAt = 0;   // bloom at the floor lays nothing anyway
      bd.list = [];    // the roadsides open bare too
      alg.list = [];
      alg.nextAt = 0;  // the pond scums over at the dead-park beat
      lv.list = [];
      lv.nextAt = 0;   // piles regrow on the next read (bloom is at the floor)
      hs.list = [];    // the posts open bare — houses are player history
      await persist();
      return json({ ok: 1, bloom: Math.round(bl.v), weeds: wd.list.length,
        slotsCleared: GARDEN_SLOTS, trash: 0, eggs: 0 });
    }
    const pass = typeof b.pass === 'string' ? b.pass.slice(0, 24) : '';
    const short = pass.slice(0, 8);
    if (!short) return json({ err: 'bad pass' }, 400);
    // 🥚 first tap wins (the rave-drop pattern) — the egg's removal IS the verdict
    if (url.pathname === '/garden/egg') {
      const ei = eg.list.findIndex((e) => e.id === b.id);
      if (ei < 0) return json(payload({ err: 'gone' }), 404);
      const [e] = eg.list.splice(ei, 1);
      // generous-faucet doctrine (Trym 29 Jul): sinks are easy, faucets hard
      const reward = e.g ? { coins: 40, tickets: 8, golden: 1 }
        : Math.random() < 0.25 ? { tickets: 5 }
          : { coins: 6 + Math.floor(Math.random() * 7) };
      await persist();
      return json(payload({ ok: 1, reward }));
    }
    // 🗑 pick up a piece of litter — first touch wins, +1 bloom says thanks
    if (url.pathname === '/garden/trash') {
      const ti = tr.list.findIndex((t) => t.id === b.id);
      if (ti < 0) return json(payload({ err: 'gone' }), 404);
      tr.list.splice(ti, 1);
      bl.v = Math.min(100, bl.v + 1);
      await persist();
      return json(payload({ ok: 1 }));
    }
    // 🥀 clear a ruined plant — the storm's cleanup chore. Frees the bed and
    // pays a little back; the bed is then plantable by anyone, as before.
    if (url.pathname === '/garden/clear') {
      const i = Math.floor(Number(b.slot));
      if (!(i >= 0 && i < slots.length) || !slots[i] || !slots[i].rot) return json(payload({ err: 'gone' }), 404);
      slots[i] = null;
      bl.v = Math.min(100, bl.v + BLOOM_CLEAR);
      dirty = true;
      await persist();
      return json(payload({ ok: 1 }));
    }
    // 🌼 …and the same for a ruined roadside pot
    if (url.pathname === '/garden/clearpot') {
      const sp = Math.floor(Number(b.spot));
      const fi = bd.list.findIndex((f) => f.spot === sp && f.rot);
      if (fi < 0) return json(payload({ err: 'gone' }), 404);
      bd.list.splice(fi, 1);
      bl.v = Math.min(100, bl.v + BLOOM_CLEAR);
      borderDirty = true;
      await persist();
      return json(payload({ ok: 1 }));
    }
    // 🌿 pull a weed — removing it IS the rate limit
    if (url.pathname === '/garden/weed') {
      const wi = wd.list.findIndex((w2) => w2.id === b.id);
      if (wi < 0) return json(payload({ err: 'gone' }), 404);
      wd.list.splice(wi, 1);
      bl.v = Math.min(100, bl.v + BLOOM_PULL);
      await persist();
      return json(payload({ ok: 1 }));
    }
    // 🫧 skim an algae patch — first touch wins, a small bloom push back
    if (url.pathname === '/garden/algae') {
      const ai = alg.list.findIndex((a2) => a2.id === b.id);
      if (ai < 0) return json(payload({ err: 'gone' }), 404);
      alg.list.splice(ai, 1);
      bl.v = Math.min(100, bl.v + BLOOM_SKIM);
      await persist();
      return json(payload({ ok: 1 }));
    }
    // 🍂 rake a leaf pile — walk-over like litter, a touch more bloom back
    if (url.pathname === '/garden/rake') {
      const li = lv.list.findIndex((l2) => l2.id === b.id);
      if (li < 0) return json(payload({ err: 'gone' }), 404);
      lv.list.splice(li, 1);
      bl.v = Math.min(100, bl.v + BLOOM_RAKE);
      await persist();
      return json(payload({ ok: 1 }));
    }
    // 🐦 raise a birdhouse — first-come per post; 30 coins client-side (like
    // seeds, never charged here). Building includes the first stocking, so
    // the birds move in the moment it goes up.
    if (url.pathname === '/garden/bhbuild') {
      const sp = Math.floor(Number(b.spot));
      if (!(sp >= 0 && sp < BIRD_SPOTS_N)) return json({ err: 'bad spot' }, 400);
      if (hs.list.some((h2) => h2.spot === sp)) return json(payload({ err: 'taken' }), 409);
      hs.list.push({ spot: sp, name: sanitizeName(b.name, []) || '', passShort: short,
        builtAt: now, lastStock: now,
        sday: { [short]: Math.floor(now / 86_400_000) }, stockers: [short] });
      await persist();
      return json(payload({ ok: 1 }));
    }
    // 🌾 stock a built house — free, 1/person/day (the watering grammar);
    // stocked <24h = the birds are in and the house feeds the bloom
    if (url.pathname === '/garden/bhstock') {
      const sp = Math.floor(Number(b.spot));
      const h2 = hs.list.find((x2) => x2.spot === sp);
      if (!h2) return json(payload({ err: 'empty' }), 404);
      const day = Math.floor(now / 86_400_000);
      h2.sday = h2.sday || {};
      if (h2.sday[short] === day) return json(payload({ err: 'stocked today' }), 429);
      h2.sday[short] = day;
      const sk = Object.keys(h2.sday);         // bounded, like a plant's wday
      if (sk.length > 60) delete h2.sday[sk[0]];
      h2.lastStock = now;
      h2.stockers = h2.stockers || [];
      if (!h2.stockers.includes(short)) { h2.stockers.push(short); if (h2.stockers.length > 60) h2.stockers.shift(); }
      await persist();
      return json(payload({ ok: 1 }));
    }
    // 🌼 plant a border flower — first-come per spot; coins client-side like
    // seeds (never charged here), NO bloom feed — decoration is its own pay
    if (url.pathname === '/garden/border') {
      const sp = Math.floor(Number(b.spot));
      if (!(sp >= 0 && sp < BORDER_SPOTS_N)) return json({ err: 'bad spot' }, 400);
      if (!BORDER_KINDS.includes(b.kind)) return json({ err: 'bad kind' }, 400);
      if (bd.list.some((f) => f.spot === sp)) return json(payload({ err: 'taken' }), 409);
      bd.list.push({ spot: sp, kind: b.kind, name: sanitizeName(b.name, []) || '',
        passShort: short, at: now });
      await persist();
      return json(payload({ ok: 1 }));
    }
    const i = Math.floor(Number(b.slot));
    if (!(i >= 0 && i < GARDEN_SLOTS)) return json({ err: 'bad slot' }, 400);
    const s = slots[i];
    if (url.pathname === '/garden/plant') {
      if (s) return json(payload({ err: 'taken' }), 409);
      if (!GARDEN_SEEDS[b.seed]) return json({ err: 'bad seed' }, 400);
      slots[i] = {
        passShort: short, name: sanitizeName(b.name, []) || '', seed: b.seed,
        plantedAt: now, lastWater: now, waterers: [], wday: {},
      };
      bl.v = Math.min(100, bl.v + BLOOM_PLANT);
    } else if (url.pathname === '/garden/water') {
      if (!s) return json(payload({ err: 'empty' }), 404);
      const day = Math.floor(now / 86_400_000);
      s.wday = s.wday || {};
      if (s.wday[short] === day) return json(payload({ err: 'watered today' }), 429);
      s.wday[short] = day;
      const wk = Object.keys(s.wday);          // bounded — a busy slot can't grow forever
      if (wk.length > 60) delete s.wday[wk[0]];
      if (s.rot) return json(payload({ err: 'rot' }), 409);
      s.lastWater = now;
      s.waterers = s.waterers || [];
      if (!s.waterers.includes(short)) { s.waterers.push(short); if (s.waterers.length > 60) s.waterers.shift(); }
      bl.v = Math.min(100, bl.v + BLOOM_WATER);
    } else if (url.pathname === '/garden/harvest') {
      if (!s) return json(payload({ err: 'empty' }), 404);
      if (s.passShort !== short) return json({ err: 'not yours' }, 403);
      const days = Math.floor((now - s.plantedAt) / 86_400_000);
      if (days < gardenSeed(s.seed).days) return json(payload({ err: 'still growing' }), 409);
      slots[i] = null;
    } else {
      return json({ err: 'not found' }, 404);
    }
    await persist();
    return json(payload({ ok: 1 }));
  }

  async webSocketMessage(ws, raw) {
    let msg;
    try { msg = JSON.parse(raw); } catch (e) { return; }
    if (!msg || typeof msg !== 'object') return;
    let me = null;
    try { me = ws.deserializeAttachment(); } catch (e) {}
    if (me && me.dead) return;

    if (msg.t === 'hi' && !me) {
      this.reapStale();
      // SUPERSEDE: the same browser rejoining (park→club→park) kills its own
      // ghost sockets immediately — without this, quick roundtrips stacked
      // duplicate bananas until the reaper's 120s sweep
      const sid = typeof msg.sid === 'string' ? msg.sid.slice(0, 24) : '';
      if (sid) {
        for (const other of this.state.getWebSockets()) {
          if (other === ws) continue;
          let a = null;
          try { a = other.deserializeAttachment(); } catch (e) {}
          if (a && !a.dead && a.sid === sid) {
            a.dead = true;
            try { other.serializeAttachment(a); } catch (e) {}
            try { other.close(1000, 'superseded'); } catch (e) {}
            this.broadcast({ t: 'leave', id: a.id }, other);
          }
        }
      }
      const p = {
        id: crypto.randomUUID().slice(0, 8),
        sid,
        name: sanitizeName(msg.name, []), // family filter; the strike list is applied via /ingest below
        outfit: sanitizeOutfit(msg.outfit),
        x: parkClampX(msg.x), y: parkClampY(msg.y),
        joined: Date.now(),
      };
      // report to the shared world names ledger + apply Trym's strike list (one
      // handle follows a person into every area — the HQ Names desk sees them all)
      if (this.env && p.name) {
        try {
          const r = await this.env.RAVE.get(this.env.RAVE.idFromName('main-floor'))
            .fetch(new Request('https://room/ingest', { method: 'POST', body: JSON.stringify({ sid, name: p.name }) }));
          const j = await r.json();
          if (typeof j.name === 'string') p.name = j.name; // struck names come back empty
        } catch (e) {}
      }
      ws.serializeAttachment(p);
      ws.send(JSON.stringify({ t: 'roster', you: p.id, all: this.roster().map(parkStrip) }));
      this.broadcast({ t: 'join', p: parkStrip(p) }, ws);
      return;
    }
    if (msg.t === 'move' && me) {
      const now = Date.now();
      if (now - (me.lastMove || 0) < 100) return; // client sends at 150ms
      me.lastMove = now;
      me.x = parkClampX(msg.x); me.y = parkClampY(msg.y);
      ws.serializeAttachment(me);
      this.broadcast({ t: 'move', id: me.id, x: me.x, y: me.y }, ws);
      return;
    }
    if (msg.t === 'outfit' && me) { // bought something at the stand mid-visit
      me.outfit = sanitizeOutfit(msg.outfit);
      ws.serializeAttachment(me);
      this.broadcast({ t: 'outfit', id: me.id, outfit: me.outfit }, ws);
    }
  }

  async webSocketClose(ws) {
    let me = null;
    try { me = ws.deserializeAttachment(); } catch (e) {}
    if (me && !me.dead) this.broadcast({ t: 'leave', id: me.id }, ws);
  }

  async webSocketError(ws) {
    return this.webSocketClose(ws);
  }
}

// 🏖 BANANA BAY — the beach's own presence room. Structurally identical to
// ParkRoom (same protocol, same sid-supersede contract, same reaper), because
// the presence protocol is a CONTRACT, not a per-room invention — see the
// world-engineering doctrine. What differs is only the coordinate space: the
// park speaks PERCENT of a small pitch, the bay speaks WORLD PIXELS on a
// 2760×1100 map (src/scripts/beach-geo.js WORLD), so it has its own clamps.
//
// Deliberately NOT reusing ParkRoom's DO: one room per place keeps the caps,
// the headcounts and the blast radius separate, and a busy beach can never
// push someone out of the park.
export class BeachRoom {
  constructor(state, env) {
    this.state = state;
    this.env = env; // RAVE binding — reports the names seen here to the shared HQ ledger
    this.state.setWebSocketAutoResponse(
      new WebSocketRequestResponsePair('{"t":"ping"}', '{"t":"pong"}')
    );
  }

  reapStale() {
    const now = Date.now();
    for (const ws of this.state.getWebSockets()) {
      let last = 0;
      try {
        const t = this.state.getWebSocketAutoResponseTimestamp(ws);
        if (t) last = t.getTime();
      } catch (e) {}
      let a = null;
      try { a = ws.deserializeAttachment(); } catch (e) {}
      if (a && a.joined > last) last = a.joined;
      if (last && now - last > 120_000) {
        if (a) { a.dead = true; try { ws.serializeAttachment(a); } catch (e) {} }
        try { ws.close(1011, 'stale'); } catch (e) {}
        if (a) this.broadcast({ t: 'leave', id: a.id }, ws);
      }
    }
  }

  roster() {
    return this.state.getWebSockets()
      .map((ws) => { try { return ws.deserializeAttachment(); } catch (e) { return null; } })
      .filter((a) => a && !a.dead);
  }

  broadcast(msg, exceptWs) {
    const s = JSON.stringify(msg);
    for (const ws of this.state.getWebSockets()) {
      if (ws === exceptWs) continue;
      try { ws.send(s); } catch (e) {}
    }
  }

  async fetch(request) {
    const url = new URL(request.url);
    if (url.pathname === '/count') {
      this.reapStale();
      return new Response(JSON.stringify({ count: this.roster().length }));
    }
    if (url.pathname === '/rosternames') { // HQ Names desk: who's named here right now
      return new Response(JSON.stringify({ names: this.roster().filter((a) => a.name).map((a) => a.name) }));
    }
    if (request.headers.get('Upgrade') !== 'websocket') {
      return new Response('expected websocket', { status: 426 });
    }
    this.reapStale();
    if (this.roster().length >= BEACH_CAP) {
      return new Response('beach full', { status: 503 });
    }
    const pair = new WebSocketPair();
    this.state.acceptWebSocket(pair[1]);
    return new Response(null, { status: 101, webSocket: pair[0] });
  }

  async webSocketMessage(ws, raw) {
    let msg;
    try { msg = JSON.parse(raw); } catch (e) { return; }
    if (!msg || typeof msg !== 'object') return;
    let me = null;
    try { me = ws.deserializeAttachment(); } catch (e) {}
    if (me && me.dead) return;

    if (msg.t === 'hi' && !me) {
      this.reapStale();
      // SUPERSEDE — mandatory in every room (world-engineering doctrine): the
      // same browser rejoining (beach→park→beach) kills its own ghosts now
      // instead of leaving duplicates until the 120s sweep.
      const sid = typeof msg.sid === 'string' ? msg.sid.slice(0, 24) : '';
      if (sid) {
        for (const other of this.state.getWebSockets()) {
          if (other === ws) continue;
          let a = null;
          try { a = other.deserializeAttachment(); } catch (e) {}
          if (a && !a.dead && a.sid === sid) {
            a.dead = true;
            try { other.serializeAttachment(a); } catch (e) {}
            try { other.close(1000, 'superseded'); } catch (e) {}
            this.broadcast({ t: 'leave', id: a.id }, other);
          }
        }
      }
      const p = {
        id: crypto.randomUUID().slice(0, 8),
        sid,
        name: sanitizeName(msg.name, []),
        outfit: sanitizeOutfit(msg.outfit),
        x: bayClampX(msg.x), y: bayClampY(msg.y),
        sit: msg.sit === true,
        joined: Date.now(),
      };
      // report to the shared world names ledger + apply Trym's strike list (one
      // handle follows a person into every area — the HQ Names desk sees them all)
      if (this.env && p.name) {
        try {
          const r = await this.env.RAVE.get(this.env.RAVE.idFromName('main-floor'))
            .fetch(new Request('https://room/ingest', { method: 'POST', body: JSON.stringify({ sid, name: p.name }) }));
          const j = await r.json();
          if (typeof j.name === 'string') p.name = j.name; // struck names come back empty
        } catch (e) {}
      }
      ws.serializeAttachment(p);
      ws.send(JSON.stringify({ t: 'roster', you: p.id, all: this.roster().map(bayStrip) }));
      this.broadcast({ t: 'join', p: bayStrip(p) }, ws);
      return;
    }
    if (msg.t === 'move' && me) {
      const now = Date.now();
      if (now - (me.lastMove || 0) < 100) return; // client sends at 150ms
      me.lastMove = now;
      me.x = bayClampX(msg.x); me.y = bayClampY(msg.y);
      me.sit = msg.sit === true;
      ws.serializeAttachment(me);
      this.broadcast({ t: 'move', id: me.id, x: me.x, y: me.y, sit: me.sit }, ws);
      return;
    }
    if (msg.t === 'outfit' && me) {
      me.outfit = sanitizeOutfit(msg.outfit);
      ws.serializeAttachment(me);
      this.broadcast({ t: 'outfit', id: me.id, outfit: me.outfit }, ws);
      return;
    }
    // 🏐 THE BALLS. ⚠️ ONE PACKET PER HIT, never a stream: the sender relays
    // the state the ball leaves its hand in, and every client integrates the
    // same physics from there. Two clients running identical constants from
    // an identical snapshot draw the same arc, so a rally costs ~1 message a
    // bounce instead of 60 a second — and the next hit resyncs any drift.
    // The room does NOT simulate. It has no idea what a ball is; it fans out
    // a validated blob. (Client-authoritative until real money — a beach toy
    // is nobody's balance.)
    if (msg.t === 'ball' && me) {
      const now = Date.now();
      if (now - (me.lastBall || 0) < 90) return;   // hit cooldowns are 240ms+
      me.lastBall = now;
      ws.serializeAttachment(me);
      const b = msg.b === 'w' ? 'w' : 'v';
      this.broadcast({
        t: 'ball', b, id: me.id,
        x: num(msg.x, 0, 2760), y: num(msg.y, 0, 1100), z: num(msg.z, 0, 900),
        vx: num(msg.vx, -1600, 1600), vy: num(msg.vy, -1600, 1600),
        vz: num(msg.vz, -1600, 1600),
      }, ws);
    }
  }

  async webSocketClose(ws) {
    let me = null;
    try { me = ws.deserializeAttachment(); } catch (e) {}
    if (me && !me.dead) this.broadcast({ t: 'leave', id: me.id }, ws);
  }

  async webSocketError(ws) {
    return this.webSocketClose(ws);
  }
}

// a finite number inside [lo, hi], rounded — never NaN/Infinity onto the wire
function num(v, lo, hi) {
  const n = Number(v);
  return Number.isFinite(n) ? Math.round(Math.min(hi, Math.max(lo, n))) : 0;
}

// world pixels, rounded to whole px (the map is 2760×1100 and a banana is ~56
// wide — sub-pixel precision would only inflate every frame on the wire)
function bayClampX(v) { const n = Number(v); return Number.isFinite(n) ? Math.min(2748, Math.max(12, Math.round(n))) : 898; }
function bayClampY(v) { const n = Number(v); return Number.isFinite(n) ? Math.min(1088, Math.max(64, Math.round(n))) : 742; }
function bayStrip(p) {
  return { id: p.id, outfit: p.outfit, x: p.x, y: p.y, sit: p.sit || undefined, name: p.name || undefined };
}

// 🌱 THE seed catalog — ⚠️ keep in sync with SEEDS in src/scripts/banana-park.js
// (one catalog, two runtimes). ⭐ stars: a living plant feeds the bloom by its
// stars (BLOOM_STAR_FEED below) and wilts slower — dry-day allowance =
// 3 + floor(stars / 2). Price is client-side display/spend only (coins are
// client-authoritative), the server never charges it.
const GARDEN_SEEDS = {
  daisy: { days: 2, stars: 1, price: 10 },
  sunflower: { days: 4, stars: 2, price: 25 },
  tulip: { days: 5, stars: 3, price: 60 },
  tomato: { days: 4, stars: 3, price: 90 },
  pumpkin: { days: 5, stars: 4, price: 160 },
  wheat: { days: 6, stars: 5, price: 300 },
};
const gardenSeed = (id) => GARDEN_SEEDS[id] || { days: 99, stars: 1 };
// 64 slots: 0-7 = site A by the meadow, 8-15 = W3's site B by the playground,
// 16-23 = site C NE (the lawn the stand freed); the 31 Jul expansion APPENDED
// a second bed pair per site — 24-31 A2, 32-39 B2, 40-47 C2 — plus a fourth
// site D on the pond's SE bank, 48-63. Indices never reorder; stored arrays
// pad on read.
const GARDEN_SLOTS = 64;
// 🌾 RIPE TTL — how long a FINISHED plant waits for its grower before the
// park picks it. Two days on top of its growing time. Short enough that a
// crowd cannot silt the beds up with orphans, long enough that a weekend away
// never costs you anything (and it costs you nothing anyway — see `compost`).
const RIPE_TTL = 2 * 86_400_000;
// 🌼 BORDER FLOWERS — single roadside blooms on the generator's BORDER_SPOTS
// (count rides park-weed-grid.js): pure decoration with a name, no bloom
// feed, no watering. A flower lives ~7 days, then the read sweeps it — the
// road shoulders stay a slowly repainting community canvas. ⚠️ kind ids must
// match BORDER_FLOWERS in src/scripts/park-garden.js.
const BORDER_KINDS = ['marigold', 'poppy', 'bluebell', 'primrose'];
const BORDER_TTL = 7 * 86_400_000;
// ⭐ THE SATURATING FEED (31 Jul — the balance keystone of the 64-slot
// garden; the old linear +0.06/h/star would have let full boxes beat max
// decay forever): watered stars (<24h) feed the bloom via MAX·s/(s+K) —
//   6 stars → 0.28/h · 18 → 0.55 · 36 → 0.73 · 72 → 0.88 · 192 → ~1.0
// Early plants RESCUE (steep start), later plants only POLISH (asymptote
// 1.1/h), and decay always wins once the watering stops.
const BLOOM_FEED_MAX = 1.1;        // per hour, the asymptote
const BLOOM_FEED_K = 18;           // watered stars at half-feed
// 🐦 BIRDHOUSES (the post-flip batch): a house STOCKED in the last 24h feeds
// BH_FEED/h — 4 posts × 0.04 = +0.16/h ceiling, and only while somebody
// keeps the daily stocking ritual going. Updated ≥80 napkin WITH the batch:
// sink ≤ 0.3 + 20×0.035 (weeds) + 6×0.02 (algae) = 1.12/h vs feed ceiling
// 1.1 (stars) + 0.16 (houses) = 1.26/h — the top is only holdable with
// daily watering AND stocking AND weeding/skimming; lapse a day and every
// feed dies (24h gates) while drift + drags keep pulling. Decay still wins.
const BH_FEED = 0.04;
// 🫧 ALGAE — the weed grammar on water: cadence ~half the weed beat per
// band (healthy ~1/16min cap 6 → dead ~1/8min cap 14), each live patch
// drags 0.02/h (full healthy scum = 0.12/h, full dead scum = 0.28/h).
// Skim pays +0.3 bloom; a rake pays +0.4 (piles only exist below 60).
const ALGAE_DRAG = 0.02;
const BLOOM_SKIM = 0.3, BLOOM_RAKE = 0.4;

// 🌦 WEATHER DAMAGE (Trym's numbers, 30 Jul). Drizzle is free forever — if
// all three tiers cost health then weather is just a tax with three animations,
// and drizzle is the one that is actually on screen (7.3% of the time), so it
// is the one selling "living park" rather than "here comes the bill".
const WX_HEAVY_TO = 50;            // heavy rain pulls health toward 50%
const WX_STORM_TO = 8;             // a storm flattens it to ~5-10%
const WX_ROT_SHARE = 0.5;          // …and ruins HALF the planted beds + pots
const BLOOM_CLEAR = 0.5;           // clearing one ruined plant pays this back
// ⚠️ BIRDHOUSES ARE DESTROYED, and that is CLAIM RECYCLING rather than damage
// (⭐ Trym's reasoning): posts are first-come with one name each, so permanent
// houses would lock everyone who arrives later out of the feature forever. The
// storm frees the posts. Consistent with border flowers fading at 7 days — the
// park's rule is that nothing is forever, and birdhouses were the exception.
function stormWreck(slots, bd, wd, tr, lv, hs, at) {
  // 50% of PLANTED beds, chosen at random across the whole garden (Trym:
  // "randomized plants across plant boxes", not a contiguous swathe)
  const live = [];
  slots.forEach((s2, i) => { if (s2 && !s2.rot) live.push(i); });
  for (let i = live.length - 1; i > 0; i--) {          // Fisher-Yates
    const j = Math.floor(Math.random() * (i + 1));
    [live[i], live[j]] = [live[j], live[i]];
  }
  live.slice(0, Math.round(live.length * WX_ROT_SHARE)).forEach((i) => { slots[i].rot = at; });
  // the roadside pots take the same share
  const pots = bd.list.filter((f) => !f.rot);
  for (let i = pots.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [pots[i], pots[j]] = [pots[j], pots[i]];
  }
  pots.slice(0, Math.round(pots.length * WX_ROT_SHARE)).forEach((f) => { f.rot = at; });
  // …and the mess it leaves behind, on free grid points
  const taken = new Set([...wd.list, ...tr.list, ...lv.list].map((t) => t.x + ',' + t.y));
  const drop = (list, n, extra) => {
    for (let k = 0; k < n; k++) {
      for (let t = 0; t < 12; t++) {
        const g = WEED_GRID[Math.floor(Math.random() * WEED_GRID.length)];
        const key = g[0] + ',' + g[1];
        if (taken.has(key)) continue;
        taken.add(key);
        list.push({ id: crypto.randomUUID().slice(0, 8), x: g[0], y: g[1], bornAt: at, ...extra });
        break;
      }
    }
  };
  drop(wd.list, 6 + Math.floor(Math.random() * 5));
  drop(tr.list, 3 + Math.floor(Math.random() * 3), { v: 1 + Math.floor(Math.random() * 3) });
  drop(lv.list, 2 + Math.floor(Math.random() * 3));
  hs.list.length = 0;                                   // every birdhouse down
}

// 🧹 THE TIDINESS CEILING (Trym, 30 Jul: "the park has been on 100% the whole
// day … but theres algae in the pond and some weed, and garbage here and
// there … it at least should be reduced some percent"). The drags were always
// in the decay — but they are a RATE, and a watered 64-slot garden out-feeds
// them, so the meter pins at 100 and mess stops registering the moment the
// park is healthy. Raising the drags cannot fix that: a big enough feed still
// wins and still pins. A ceiling is the honest shape — however hard you water,
// THE PARK CANNOT READ PERFECT WHILE THERE IS LITTER IN IT.
// Deliberately small and capped: this is a nudge to tidy up, not a second
// decay. At the ≥80 band the caps are 20 weeds / 6 algae / 4 litter, so a
// fully messy healthy park reads ~90 and a spotless one still reads 100 —
// which is what keeps clearing it worth doing.
// ⚠️ NO CAP, and that is the point: a cap means the first items you clear pay
// NOTHING (you are still pinned to the cap), which is the same dead feedback
// this whole change is fixing. Uncapped and small, every single item you clear
// moves the bar. The ≥80 band's caps are 20 weeds / 6 algae / 4 litter, so the
// worst a spotlessly-fed park can read is ~87 — comfortably above the 80 band
// border, so tidiness alone can never push the park into a worse spawn band.
const TIDY_WEED = 0.3, TIDY_ALGAE = 0.6, TIDY_LITTER = 0.8;
const tidyCeil = (weeds, algae, litter) => 100
  - (TIDY_WEED * weeds.length + TIDY_ALGAE * algae.length + TIDY_LITTER * litter.length);

// 🌿 WEEDS 2.0 + 🌸 THE BLOOM — the park's entropy loop. Weeds are an
// ORGANISM on WEED_GRID (park-weed-grid.js, generated): children sprout NEAR
// a living parent (patches that visibly spread), ~15% of spawns POLLINATE to
// a random far grid point (crossing roads → new patches), and an empty map
// always re-seeds one. Cadence + cap ride the bloom DOWN (bands in garden())
// so a dead park looks OVERRUN — a viewport on a patch reads fully overtaken
// (~30-40 weeds in view) while the global count stays bounded.
// Napkin equilibria (31 Jul retune, one notch harder for the 64-slot era:
// 0.3/h base + 0.035/h/weed vs the saturating feed ≤1.1/h; pull +0.4,
// water +2, plant +6):
//   ≥80: cap 20 → sink ≤1.0/h vs feed max 1.1 — holding at FULL weed cap
//   would take ~180 watered stars, so weeding stays mandatory; weeded +
//   ~18 watered stars (0.55 vs 0.3) holds comfortably
//   60-79: cap 26 → ≤1.21/h ≈ 29/day — a couple of visitors' rounds cover it
//   40-59: cap 40 → ≤1.70/h ≈ 41/day
//   <40: cap 80 → ≤3.10/h ≈ 74/day — the overrun LOOK, but pulling the lot
//   pays +32 bloom and kills the drag; the floor keeps it never-hopeless
const WEED_NEAR = 110;             // a child sprouts this close to its parent
const WEED_POLLINATE = 0.15;       // share of spawns that jump far instead
const BLOOM_FLOOR = 5;             // launch-era floor (was 15) — properly dead, never hopeless
const BLOOM_BASE_DRIFT = 0.3;      // per hour, always
const BLOOM_WEED_DRAG = 0.035;     // per hour, per live weed (0.05 pre-64-slot)
// ⚠️ retuned 29 Jul post-flip (Trym: "mowing bushes increases the health
// percentage really fast") — 60 weeds × 3 = +180 meant one mowing session
// ended the recovery arc. Pulling now mostly STOPS the decay (drag removal);
// the healing comes from planting/watering/star-feeds over days.
const BLOOM_PULL = 0.4, BLOOM_WATER = 2, BLOOM_PLANT = 6;
// 🥚 W2 EGGS — laid near the hens' lawn, first tap wins. Cadence rides the
// bloom band: below 40 nothing, 40+ rare, 60+ steady, 80+ often; the golden
// egg only while the park sits at 95+. Rewards resolve server-side.
const EGG_TTL = 20 * 60_000;
const EGG_CAP = 2;
const EGG_EVERY_2 = 3 * 3600_000, EGG_EVERY_3 = 90 * 60_000, EGG_EVERY_4 = 45 * 60_000;
const EGG_GOLD_AT = 95;
// hen-lawn spots SW of the plaza — lawn only, clear of tables and roads
const EGG_SPOTS = [[1060, 640], [1150, 706], [1270, 745], [1005, 715], [1180, 760]];

function parkClampX(v) { const n = Number(v); return Number.isFinite(n) ? Math.min(95, Math.max(5, Math.round(n * 10) / 10)) : 50; }
function parkClampY(v) { const n = Number(v); return Number.isFinite(n) ? Math.min(99, Math.max(20, Math.round(n * 10) / 10)) : 90; }
function parkStrip(p) {
  return { id: p.id, outfit: p.outfit, x: p.x, y: p.y, name: p.name || undefined };
}
const sanLvl = (v) => { const n = Math.round(Number(v)); return n >= 1 && n <= 99 ? n : undefined; };
