// Banana rave worker — the realtime dance floor.
//
// The trick that makes this nearly free: the dance itself needs ZERO server
// traffic. Every banana on Earth dances in phase off the wall clock
// (t = Date.now() % cycle). The server only does PRESENCE: who's on the
// floor (outfit ids + join time) and the occasional emote. A rave is,
// technically, a chat room where nobody talks.
//
// Moderation surface: ONE field, defended in depth (17 Jul — Trym's ONE-
// identity call: the pass name shows on the floor too). Outfits validate
// against id allowlists, emotes are a fixed set, and the NAME passes the
// family filter + Trym's strike list at the door (sanitizeName) — a name
// that fails simply doesn't travel; the banana wears its outfit-name.
// Admin: GET /names?key= (ledger of names seen + live + strikes) and
// POST /strike?key= {t, remove?} — the quick swipe; scrubs the live floor.
//
// Cost guardrails: WebSocket hibernation (idle connections ≈ free), room cap,
// per-connection emote throttle, Origin allowlist. Free plan fails closed.
//
// Routes:
//   GET /ws      upgrade → the room ("main-floor")
//   GET /count   current floor count (for the homepage proof-of-life later)

// ALLOWLISTS-START — GENERATED by tools/build-worker-allowlists.mjs from
// src/data/wearables.js (the single-source manifest). NEVER edit by hand:
// rerun the script after any wearable change, then deploy this worker.
// raveOnly items (beer/cone/vinyl/broom) are server-granted and excluded
// so sanitize strips them from client outfits.
const HAT_IDS = ['none', 'party', 'crown', 'tophat', 'cowboy', 'viking', 'sombrero', 'halo', 'beanieprop', 'backwardscap', 'gradcap', 'tricorn', 'jester', 'friedegg', 'pigeon', 'arrowthru', 'fishbowl', 'devilhorns', 'nightcap', 'djheadphones', 'duckhat', 'melticecream', 'watermelonhat', 'buckethat', 'snailhat', 'squidhat'];
const DROP_IDS = ['djheadphones'];
const SHADE_IDS = ['none', 'shades', 'dwi', 'hearts', 'visor', 'threed', 'potter', 'nerd', 'monocle', 'groucho', 'eyepatch', 'googlyeyes', 'cucumbers', 'snorkelmask'];
const EXTRA_IDS = ['mustache', 'fatstache', 'bowtie', 'necktie', 'goldchain', 'scarf', 'coneofshame', 'lifering', 'nightshirt', 'flamingoring', 'medal', 'sneakers', 'sneakersblue', 'sneakersgold', 'skates', 'clownshoes', 'cowboyboots', 'discoboots', 'ledsneakers', 'flamekicks', 'flippers', 'sockssandals', 'boombox', 'mug', 'trophy', 'boingball', 'balloons', 'rubberchicken', 'bigfish', 'protestsign', 'candle', 'balloondog', 'potato', 'cactuspot', 'glowstick', 'goldbanana'];
// ALLOWLISTS-END
const EFFECT_IDS = ['none', 'disco', 'sparkle', 'confetti'];
const EMOTES = ['heart', 'confetti', 'banana', 'fire']; // fire = stage members only
const ROOM_CAP = 200;
const STAGE_CAP = 8;                  // spots on the line behind the DJ
const STAGE_MIN_MS = 5 * 60 * 1000;   // survive 5 min on the floor → the stage opens (keep in sync with STAGE_UNLOCK_MS in banana-rave.js)
// HAPPY HOUR — same wall-clock windows as the client (keep in sync with banana-rave.js).
// One beer per window, first claim wins; the beer lives in outfit.extras but is
// SERVER-GRANTED only ('beer' is deliberately NOT in EXTRA_IDS → sanitize strips it).
const HAPPY_PERIOD = 300_000, HAPPY_LEN = 40_000, HAPPY_OFFSET = 120_000;
function happyWindow(now) {
  const ph = (((now - HAPPY_OFFSET) % HAPPY_PERIOD) + HAPPY_PERIOD) % HAPPY_PERIOD;
  return ph < HAPPY_LEN ? Math.floor((now - HAPPY_OFFSET) / HAPPY_PERIOD) : -1;
}
// THE LOST VINYL — courier quest (keep schedule + spot math in sync with banana-rave.js):
// spawns every 7 min at a clock-seeded spot, first banana to reach it carries it,
// delivering to the stage edge buys the whole floor a bonus drop.
const VINYL_PERIOD = 420_000, VINYL_WAIT = 180_000, VINYL_OFFSET = 210_000;
function vinylWindow(now) {
  const ph = (((now - VINYL_OFFSET) % VINYL_PERIOD) + VINYL_PERIOD) % VINYL_PERIOD;
  return ph < VINYL_WAIT ? Math.floor((now - VINYL_OFFSET) / VINYL_PERIOD) : -1;
}
function seedRand(n) {
  let x = Math.imul(n ^ 0x9e3779b9, 0x85ebca6b);
  x = Math.imul(x ^ (x >>> 13), 0xc2b2ae35);
  x ^= x >>> 16;
  return (x >>> 0) / 4294967296;
}
function vinylSpot(w) {
  let x = 12 + seedRand(0x5eed + w * 2) * 70;
  let y = 26 + seedRand(0x5eed + w * 2 + 1) * 46; // open floor only — high spawns near the stage edge were unreachable on iOS
  if (x < 36 && y > 66) y -= 30;
  return { x, y };
}
// HOT SAUCE — a bottle on the open floor every 4 min; grabbing it grants a timed
// flame-trail fx. fx is SERVER-GRANTED like the beer: clients only render what
// the roster says, so effects can't be spoofed.
const SAUCE_PERIOD = 180_000, SAUCE_WAIT = 100_000, SAUCE_OFFSET = 60_000;
function sauceWindow(now) {
  const ph = (((now - SAUCE_OFFSET) % SAUCE_PERIOD) + SAUCE_PERIOD) % SAUCE_PERIOD;
  return ph < SAUCE_WAIT ? Math.floor((now - SAUCE_OFFSET) / SAUCE_PERIOD) : -1;
}
function sauceSpot(w) {
  let x = 12 + seedRand(0xf1a5 + w * 2) * 70;
  let y = 26 + seedRand(0xf1a5 + w * 2 + 1) * 46;
  if (x < 36 && y > 66) y -= 30;
  return { x, y };
}
// THE GOLDEN BANANA — a rare drop (~every 30 min); the finder mints a patch and
// the whole floor gets a confetti party. A moment, not a power-up.
const GOLD_PERIOD = 1_800_000, GOLD_WAIT = 240_000, GOLD_OFFSET = 660_000;
function goldWindow(now) {
  const ph = (((now - GOLD_OFFSET) % GOLD_PERIOD) + GOLD_PERIOD) % GOLD_PERIOD;
  return ph < GOLD_WAIT ? Math.floor((now - GOLD_OFFSET) / GOLD_PERIOD) : -1;
}
function goldSpot(w) {
  let x = 12 + seedRand(0x601d + w * 2) * 70;
  let y = 26 + seedRand(0x601d + w * 2 + 1) * 46;
  if (x < 36 && y > 66) y -= 30;
  return { x, y };
}
// THE CONVEYOR — one unified item stream so the floor is NEVER dead (Trym's
// low-traffic brief: solo visitors need a constant chase). A new item every 75s
// at a clock-seeded spot; the type comes from the same seed. Effect items ride
// the fx system; snacks (candy/pizza/balloon) are pure chase + client-side chain.
// items live FIVE SECONDS on the floor (Trym: reflex, not patience) — the
// client shows/poofs at 5s; the server window carries 1.5s latency grace
const ITEM_PERIOD = 75_000, ITEM_WAIT = 6_500, ITEM_OFFSET = 15_000;
function itemWindow(now) {
  const ph = (((now - ITEM_OFFSET) % ITEM_PERIOD) + ITEM_PERIOD) % ITEM_PERIOD;
  return ph < ITEM_WAIT ? Math.floor((now - ITEM_OFFSET) / ITEM_PERIOD) : -1;
}
function itemSpot(w) {
  let x = 12 + seedRand(0x17e6 + w * 2) * 70;
  let y = 26 + seedRand(0x17e6 + w * 2 + 1) * 46;
  if (x < 36 && y > 66) y -= 30;
  return { x, y };
}
function itemType(w) { // keep weights in sync with banana-rave.js
  const r = seedRand(0x7ab1e + w);
  // 22 kinds — classics keep a slight edge; the R4.5 six close the table
  return r < 0.08 ? 'sauce' : r < 0.15 ? 'zap' : r < 0.22 ? 'fizz'
    : r < 0.28 ? 'candy' : r < 0.34 ? 'pizza' : r < 0.40 ? 'balloon'
    : r < 0.45 ? 'shard' : r < 0.50 ? 'cone' : r < 0.55 ? 'popper'
    : r < 0.59 ? 'remote' : r < 0.63 ? 'kazoo' : r < 0.67 ? 'glitter'
    : r < 0.71 ? 'phone' : r < 0.75 ? 'cube' : r < 0.78 ? 'pizzabox'
    : r < 0.81 ? 'wand' : r < 0.85 ? 'boots' : r < 0.88 ? 'gel'
    : r < 0.91 ? 'sparkler' : r < 0.94 ? 'magnet' : r < 0.97 ? 'vhs' : 'star';
}
const ITEM_FX = { // all rendering is client-side; the server only stamps fx ids
  sauce: 'flames', zap: 'zap', fizz: 'fizz', balloon: 'balloon',
  shard: 'prism', cone: 'cone', popper: 'popper', remote: 'fog', kazoo: 'notes',
  glitter: 'glitter', phone: 'flash', cube: 'slide', wand: 'bubbles',
  boots: 'boots', gel: 'wobble', sparkler: 'sparkler', magnet: 'magnet', vhs: 'vhs', star: 'conga',
  // the snacks wear their dinner now (Trym round 2): held pizza props + the
  // sugar shakes; pizzabox still pays its jelly client-side on top
  pizza: 'slice', pizzabox: 'box', candy: 'sugar',
};
// BARTY'S SPECIALS — between happy hours a rotating cocktail lands on the counter;
// first banana at the bar drinks it and wears its effect for a while.
const SPECIAL_PERIOD = 300_000, SPECIAL_LEN = 35_000, SPECIAL_OFFSET = 270_000;
const COCKTAILS = ['daiquiri', 'fizz', 'espresso', 'lagoon', 'colada', 'margarita', 'champagne', 'milkshake', 'jellyshot', 'water']; // keep in sync with banana-rave.js
function specialWindow(now) {
  const ph = (((now - SPECIAL_OFFSET) % SPECIAL_PERIOD) + SPECIAL_PERIOD) % SPECIAL_PERIOD;
  return ph < SPECIAL_LEN ? Math.floor((now - SPECIAL_OFFSET) / SPECIAL_PERIOD) : -1;
}
// effects are MOMENTS, not outfits — 10s baseline with the item menu cycling
// (Trym's call; was 150s/60s). Clients also cap at first sight (capFx).
// Trym's juice pass: the crowd favourites earn longer runs (keep in sync
// with banana-rave.js FX_DUR — the client cap clamps to the same table).
const FX_MS = 10_000;
const FX_DUR = { cone: 30_000, balloon: 20_000, zap: 20_000, conga: 15_000, boots: 15_000, magnet: 12_000, sparkler: 12_000, fog: 20_000 };
const fxLen = (id) => FX_DUR[id] || FX_MS;

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const room = env.RAVE.get(env.RAVE.idFromName('main-floor'));
    if (url.pathname === '/ws') {
      const allowed = (env.ALLOWED_ORIGIN || '').split(',').map((s) => s.trim());
      if (!allowed.includes(request.headers.get('Origin') || '')) {
        return new Response('forbidden', { status: 403 });
      }
      return room.fetch(request);
    }
    // 🌳 the PARK outside the stand — its own tiny room (S5): presence +
    // positions + outfits only, none of the floor's event machinery
    if (url.pathname === '/park') {
      const allowed = (env.ALLOWED_ORIGIN || '').split(',').map((s) => s.trim());
      if (!allowed.includes(request.headers.get('Origin') || '')) {
        return new Response('forbidden', { status: 403 });
      }
      return env.PARK.get(env.PARK.idFromName('the-park')).fetch(request);
    }
    // the Banana Mail rave-names desk (browser fetches from trymstene.com)
    if (url.pathname === '/names' || url.pathname === '/strike') {
      const allowed = (env.ALLOWED_ORIGIN || '').split(',').map((s) => s.trim());
      const origin = request.headers.get('Origin') || '';
      const cors = {
        'Access-Control-Allow-Origin': allowed.includes(origin) ? origin : 'https://trymstene.com',
        'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
        'Access-Control-Allow-Headers': 'content-type',
        'Cache-Control': 'no-store',
        'Content-Type': 'application/json',
      };
      if (request.method === 'OPTIONS') return new Response(null, { headers: cors });
      const res = await room.fetch(new Request('https://room' + url.pathname + url.search, {
        method: request.method,
        body: request.method === 'POST' ? await request.text() : undefined,
      }));
      return new Response(await res.text(), { status: res.status, headers: cors });
    }
    if (url.pathname === '/count') {
      const res = await room.fetch(new Request('https://room/count'));
      return new Response(await res.text(), {
        headers: { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*', 'Cache-Control': 'no-store' },
      });
    }
    if (url.pathname === '/park-count') { // the HQ world desk's park headcount
      const res = await env.PARK.get(env.PARK.idFromName('the-park')).fetch(new Request('https://room/count'));
      return new Response(await res.text(), {
        headers: { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*', 'Cache-Control': 'no-store' },
      });
    }
    return new Response('not found', { status: 404 });
  },
};

function sanitizeOutfit(o) {
  o = o && typeof o === 'object' ? o : {};
  const extras = {};
  EXTRA_IDS.forEach((id) => { if (o.extras && o.extras[id] === true) extras[id] = true; });
  return {
    hat: HAT_IDS.includes(o.hat) ? o.hat : 'none',
    glasses: SHADE_IDS.includes(o.glasses) ? o.glasses : 'none',
    extras,
    effect: EFFECT_IDS.includes(o.effect) ? o.effect : 'none',
    // 'c' = a caught COMMUNITY catalog item (worker-share catalog/items.json).
    // Format-validated only: spectators render it from the public manifest, so
    // an unknown id simply draws nothing — bounded string, no art risk here.
    ...(/^c_[a-f0-9]{6,32}$/.test(o.c || '') ? { c: o.c } : {}),
  };
}

// THE FAMILY FILTER (server copy — floor names the client can't sneak past).
// AUTO-PATCHED by tools/build-family-filter.py between the markers below;
// same lists + matching as src/lib/family-filter.js. Never edit by hand.
// FAMILY-FILTER-START
const F_WORDS = new Set('acrotomophilia|anal|anilingus|anus|arsehole|ass|asshole|assmunch|autoerotic|babeland|bangbros|bangbus|bareback|barenaked|bastard|bastardo|bastinado|bbw|bdsm|beaner|beaners|beastiality|bestiality|bimbos|birdlock|blowjob|blumpkin|bollocks|bondage|boner|boob|boobs|bukkake|bulldyke|bunghole|busty|butt|buttcheeks|butthole|camgirl|camslut|carpetmuncher|cialis|circlejerk|clit|clitoris|cock|cocks|coon|coons|coprolagnia|coprophilia|cornhole|creampie|cum|cumming|cumshot|cumshots|cunnilingus|darkie|daterape|deepthroat|dendrophilia|dick|dildo|dingleberries|dingleberry|doggiestyle|doggystyle|dolcett|domination|dominatrix|dommes|dritt|drittsekk|dvda|ecchi|ejaculation|erotic|erotism|escort|eunuch|faen|fag|fanken|fecal|felch|fellatio|feltch|femdom|figging|fingerbang|fingering|fisting|fitte|footjob|forbanna|forbannet|frotting|fudgepacker|futanari|føkk|føkka|føkkings|gangbang|genitals|goatcx|goatse|gokkun|goodpoop|goregasm|grope|guro|handjob|hardcore|helvete|helvetet|hentai|homoerotic|honkey|hooker|hore|horny|humping|incest|intercourse|jailbait|jigaboo|jiggaboo|jiggerboo|jizz|juggs|kike|kinbaku|kinkster|kinky|kneppe|knobbing|kuk|kukene|kuker|livesex|lolita|lovemaking|masturbate|masturbating|masturbation|milf|mong|morraknuller|morrapuler|muffdiving|nambla|nawashi|nazi|negro|neonazi|nimphomania|nipple|nipples|nsfw|nude|nudity|nutten|nympho|nymphomania|octopussy|omorashi|orgasm|orgy|paedophile|paki|pakkis|panties|panty|pedobear|pedophile|pegging|penis|pikey|pikk|pissing|pisspig|playboy|pokker|ponyplay|poof|poon|poontang|poopchute|pthc|pubes|punany|pussy|queaf|queef|quim|raghead|rape|raping|rapist|rectum|retard|rimjob|rimming|ræva|ræven|sadism|santorum|satan|scat|schlong|scissoring|semen|sex|sexcam|sexo|sexual|sexuality|sexually|sexy|shemale|shibari|shota|shrimping|sinnsykt|skeet|skitt|slanteye|slut|smut|snatch|snowballing|sodomize|sodomy|sotrør|spastic|spic|splooge|spooge|spunk|stapikk|stapikkene|stapikker|strapon|strappado|suck|sucks|svartheiteste|swastika|swinger|threesome|throating|thumbzilla|tit|tits|titties|titty|topless|tosser|towelhead|tranny|tribadism|tubgirl|tushy|twat|twink|twinkie|undressing|upskirt|urophilia|vagina|viagra|vibrator|vorarephilia|voyeur|voyeurweb|voyuer|vulva|wank|wetback|worldsex|xxx|yaoi|yiffy|zoophilia|🖕'.split('|'));
const F_PHRASES = 'alabamahotpocket|alaskanpipeline|autoerotic|babybatter|babyjuice|ballgag|ballgravy|ballkicking|balllicking|ballsack|ballsucking|barelylegal|beavercleaver|beaverlips|bigblack|bigbreasts|bigknockers|bigtits|blackcock|blondeaction|blondeonblondeaction|blowjob|blowyourload|bluewaffle|bootycall|brownshowers|brunetteaction|bulletvibe|bunghole|cameltoe|carpetmuncher|chocolaterosebuds|clevelandsteamer|cloverclamps|daterape|deepthroat|dirtypillows|dirtysanchez|doggiestyle|doggystyle|dogstyle|donkeypunch|doubledong|doublepenetration|dpaction|dryhump|eatmyass|faenihelvete|femalesquirting|footfetish|fudgepacker|fyfaen|gangbang|gaysex|giantcock|girlon|girlontop|girlscup|girlsgonewild|goddamn|goldenshower|googirl|groupsex|gspot|handjob|hardcore|hotcarl|hotchick|howtokill|howtomurder|hugefat|jackoff|jailbait|jellydonut|jerkoff|leatherrestraint|leatherstraightjacket|lemonparty|makemecome|malesquirting|menageatrois|missionaryposition|moundofvenus|mrhands|muffdiver|nignog|nsfwimages|onecuptwogirls|oneguyonejar|phonesex|pisspig|pleasurechest|polesmoker|poopchute|princealbertpiercing|ragingboner|reversecowgirl|rosypalm|rosypalmandhersisters|rustytrombone|shavedbeaver|shavedpussy|sploogemoose|spreadlegs|strapon|stripclub|styledoggy|suicidegirls|sultrywomen|taintedlove|tastemy|teabagging|tiedup|tightwhite|tongueina|tubgirl|twogirlsonecup|urethraplay|venusmound|violetwand|wetdream|whitepower|wrappingmen|wrinkledstarfish|yellowshowers'.split('|');
const F_STEMS = 'nigg|fagg|cunt|whore|hitler|jævl|jævel|fuck|shit|bitch|porn'.split('|');
// FAMILY-FILTER-END
const F_LEET = { '0': 'o', '1': 'i', '3': 'e', '4': 'a', '5': 's', '7': 't', '8': 'b', '@': 'a', '$': 's', '!': 'i' };
const F_MARKS = new RegExp('[' + String.fromCharCode(768) + '-' + String.fromCharCode(879) + ']', 'g');
function dirty(s) {
  let base = String(s || '').toLowerCase();
  try { base = base.normalize('NFD').replace(F_MARKS, ''); } catch (e) {}
  base = base.replace(/[0134578@$!]/g, (c) => F_LEET[c] || c);
  const squeezed = base.replace(/(.)\1{2,}/g, '$1');
  for (const v of (base === squeezed ? [base] : [base, squeezed])) {
    const collapsed = v.replace(/[^a-zæø]/g, '');
    if (F_STEMS.some((w) => collapsed.includes(w))) return true;
    if (F_PHRASES.some((p) => collapsed.includes(p))) return true;
    const toks = v.split(/[^a-zæø]+/).filter(Boolean);
    for (const tok of toks) { if (F_WORDS.has(tok)) return true; }
    let run = '';
    for (let i = 0; i <= toks.length; i++) {
      const t = toks[i];
      if (t && t.length === 1) { run += t; continue; }
      if (run.length >= 3 && (F_WORDS.has(run) || F_STEMS.some((w) => run.includes(w)))) return true;
      run = '';
    }
  }
  return false;
}

// strike-list matching key: lowercase, de-accent, de-leet, letters only —
// so a struck fragment catches respellings of the same stunt
function normName(s) {
  let b = String(s || '').toLowerCase();
  try { b = b.normalize('NFD').replace(F_MARKS, ''); } catch (e) {}
  return b.replace(/[0134578@$!]/g, (c) => F_LEET[c] || c).replace(/[^a-zæø]/g, '');
}

// ONE identity (Trym's call, 17 Jul): the pass name shows on the floor too.
// Defense in depth: family filter + Trym's strike list; a name that fails
// either simply doesn't travel — the banana falls back to its outfit-name.
function sanitizeName(s, strikes) {
  s = String(s || '').split('').filter((c) => {
    const k = c.charCodeAt(0);
    return k >= 32 && k !== 127;
  }).join('').trim().slice(0, 24);
  if (!s) return '';
  if (dirty(s)) return '';
  const n = normName(s);
  if (strikes.some((k) => n.includes(k))) return '';
  return s;
}

export class RaveRoom {
  constructor(state, env) {
    this.state = state;
    this.env = env; // RAVE_KEY gates the names/strike admin endpoints
    // auto-respond to pings without waking the object (hibernation-friendly)
    this.state.setWebSocketAutoResponse(
      new WebSocketRequestResponsePair('{"t":"ping"}', '{"t":"pong"}')
    );
  }

  // GHOST REAPER (12 Jul — Trym saw his own iOS zombie twice on the floor):
  // iOS drops the goodbye close-frame on quick reloads/backgrounding, so dead
  // sessions linger in the roster. Liveness = the hibernation auto-response
  // timestamp (every client pings ~30s; the runtime stamps it WITHOUT waking
  // us) — so pocket-AFK farmers stay safe and no client change is needed.
  reapStale() {
    const now = Date.now();
    for (const ws of this.state.getWebSockets()) {
      let last = 0;
      try {
        const t = this.state.getWebSocketAutoResponseTimestamp(ws);
        if (t) last = t.getTime();
      } catch (e) {}
      let a = null;
      try { a = ws.deserializeAttachment(); } catch (e) {}
      if (a && a.joined > last) last = a.joined; // fresh sockets haven't pinged yet
      if (last && now - last > 120_000) { // 4 missed pings = dead
        // close() is async — the socket stays in getWebSockets() this tick, so
        // mark the attachment dead and roster()/count filter it out NOW
        if (a) { a.dead = true; try { ws.serializeAttachment(a); } catch (e) {} }
        try { ws.close(1011, 'stale'); } catch (e) {}
        if (a) this.broadcast({ t: 'leave', id: a.id }, ws);
      }
    }
  }

  async fetch(request) {
    const url = new URL(request.url);
    if (url.pathname === '/count') {
      this.reapStale(); // the homepage door polls this — free periodic sweeps
      return new Response(JSON.stringify({ count: this.roster().length }));
    }
    // ---- Banana Mail's rave-names desk (key-gated; fails closed until Trym
    // sets the RAVE_KEY secret) ---------------------------------------------
    if (url.pathname === '/names' || url.pathname === '/strike') {
      const key = url.searchParams.get('key') || '';
      if (!this.env || !this.env.RAVE_KEY || key !== this.env.RAVE_KEY) {
        return new Response(JSON.stringify({ error: 'forbidden' }), { status: 403 });
      }
      const strikes = (await this.state.storage.get('nameStrikes')) || [];
      if (url.pathname === '/strike' && request.method === 'POST') {
        let b = {};
        try { b = JSON.parse(await request.text()); } catch (e) {}
        const frag = normName(String(b.t || '')).slice(0, 24);
        if (frag.length < 2) return new Response(JSON.stringify({ error: 'too short' }), { status: 400 });
        const next = b.remove
          ? strikes.filter((s) => s !== frag)
          : [...new Set([...strikes, frag])].slice(-200);
        await this.state.storage.put('nameStrikes', next);
        if (!b.remove) this.scrubName(frag); // the QUICK SWIPE: live floor scrub
        return new Response(JSON.stringify({ ok: true, strikes: next }));
      }
      const seen = (await this.state.storage.get('namesSeen')) || {};
      const names = Object.entries(seen).sort((a, b) => b[1] - a[1]).map(([n, at]) => ({ n, at }));
      const live = this.roster().filter((a) => a.name).map((a) => a.name);
      return new Response(JSON.stringify({ live, names, strikes }));
    }
    if (request.headers.get('Upgrade') !== 'websocket') {
      return new Response('expected websocket', { status: 426 });
    }
    this.reapStale(); // ghosts must never hold seats against the cap
    if (this.roster().length >= ROOM_CAP) {
      return new Response('floor full', { status: 503 });
    }
    const pair = new WebSocketPair();
    this.state.acceptWebSocket(pair[1]);
    return new Response(null, { status: 101, webSocket: pair[0] });
  }

  roster() {
    return this.state.getWebSockets()
      .map((ws) => { try { return ws.deserializeAttachment(); } catch (e) { return null; } })
      .filter((a) => a && !a.dead);
  }

  broadcast(msg, exceptWs) {
    const s = JSON.stringify(msg);
    for (const ws of this.state.getWebSockets()) {
      if (ws === exceptWs) continue;
      try { ws.send(s); } catch (e) {}
    }
  }

  async webSocketMessage(ws, raw) {
    let msg;
    try { msg = JSON.parse(raw); } catch (e) { return; }
    if (!msg || typeof msg !== 'object') return;

    let me = null;
    try { me = ws.deserializeAttachment(); } catch (e) {}
    if (me && me.dead) return; // reaped — everyone already saw the leave; no resurrection

    if (msg.t === 'hi' && !me) {
      this.reapStale(); // every join clears the zombies before the roster ships
      // SUPERSEDE (same contract as ParkRoom): the same browser rejoining
      // kills its own ghost sockets NOW — quick park→club roundtrips were
      // stacking duplicate dancers until the reaper's sweep
      const sid = typeof msg.sid === 'string' ? msg.sid.slice(0, 24) : '';
      if (sid) {
        for (const other of this.state.getWebSockets()) {
          if (other === ws) continue;
          let a = null;
          try { a = other.deserializeAttachment(); } catch (e) {}
          if (a && !a.dead && a.sid === sid) {
            a.dead = true;
            try { other.serializeAttachment(a); } catch (e) {}
            try { other.close(1000, 'superseded'); } catch (e) {}
            this.broadcast({ t: 'leave', id: a.id }, other);
          }
        }
      }
      const strikes = (await this.state.storage.get('nameStrikes')) || [];
      const p = {
        id: crypto.randomUUID().slice(0, 8),
        sid,
        name: sanitizeName(msg.name, strikes), // '' = the outfit-name speaks
        outfit: sanitizeOutfit(msg.outfit),
        joined: Date.now(),
        // floor time carried across reconnects: iOS re-sockets on every
        // background/foreground, so gating the stage on `joined` alone made
        // the button LOOK ready (client clock) while the server said "early"
        // (fresh socket clock). The client reports its floor time; clamp it
        // and keep it AWAY from `joined` — the ghost reaper trusts `joined`
        // as the liveness floor for fresh sockets, so backdating it would get
        // newcomers reaped before their first ping.
        since: Date.now() - Math.min(Math.max(Number(msg.sess) || 0, 0), 86_400_000),
        lvl: sanLvl(msg.lvl),
        lastEmote: 0,
      };
      ws.serializeAttachment(p);
      const beerWin = (await this.state.storage.get('beerWin')) ?? null;
      const vinylWin = (await this.state.storage.get('vinylWin')) ?? null;
      const sauceWin = (await this.state.storage.get('sauceWin')) ?? null;
      const cocktailWin = (await this.state.storage.get('cocktailWin')) ?? null;
      const goldWin = (await this.state.storage.get('goldWin')) ?? null;
      const itemWin = (await this.state.storage.get('itemWin')) ?? null;
      ws.send(JSON.stringify({ t: 'roster', you: p.id, all: this.roster().map(strip), beerWin, vinylWin, sauceWin, cocktailWin, goldWin, itemWin }));
      this.broadcast({ t: 'join', p: strip(p) }, ws);
      if (p.name) this.recordName(p.name); // the Banana Mail names-desk ledger
      return;
    }

    if (msg.t === 'beer' && me && !me.beer) { // first banana at the bar this window
      const win = happyWindow(Date.now());
      if (win < 0) return;
      // you must actually WALK to the bar. The zone is a GENEROUS anti-cheat
      // bound: the solid counter's edge scales with the client's floor width
      // (x≈50-62% on phones), so the precise at-the-counter gate lives client-
      // side and this only blocks cross-floor spoofing.
      if (!(typeof me.x === 'number' && me.x < 70 && typeof me.y === 'number' && me.y > 64)) return;
      if (this.beerWin === win) return;   // sync fast-path — two claims in the same window can't both pass
      this.beerWin = win;                 // claim in-memory BEFORE any await (DO interleaves at await points)
      const stored = await this.state.storage.get('beerWin');
      if (stored === win) return;         // claimed before a hibernation wipe of the instance field
      await this.state.storage.put('beerWin', win);
      me.beer = true;
      me.outfit.extras = { ...(me.outfit.extras || {}), beer: true };
      ws.serializeAttachment(me);
      this.broadcast({ t: 'beer', id: me.id });
      return;
    }

    if (msg.t === 'emote' && me && EMOTES.includes(msg.k)) {
      if (msg.k === 'fire' && !me.stage) return; // the 🔥 is earned, not given
      const now = Date.now();
      if (now - (me.lastEmote || 0) < 1500) return; // throttle: no spam cannons
      me.lastEmote = now;
      ws.serializeAttachment(me);
      this.broadcast({ t: 'emote', id: me.id, k: msg.k });
      return;
    }

    if (msg.t === 'move' && me) { // walking: position relay, sender echoes locally
      const x = Number(msg.x), y = Number(msg.y);
      if (!Number.isFinite(x) || !Number.isFinite(y)) return;
      const now = Date.now();
      if (now - (me.lastMove || 0) < 100) return; // rate guard: client sends at 150ms
      me.lastMove = now;
      me.x = Math.min(96, Math.max(4, Math.round(x * 10) / 10));
      me.y = Math.min(92, Math.max(6, Math.round(y * 10) / 10));
      ws.serializeAttachment(me);
      this.broadcast({ t: 'move', id: me.id, x: me.x, y: me.y }, ws);
      return;
    }

    if (msg.t === 'vinyl' && me && !me.vinyl) { // first banana to the lost record
      const win = vinylWindow(Date.now());
      if (win < 0) return;
      if (this.vinylWin === win) return;      // sync guard before any await
      const spot = vinylSpot(win);
      if (!(typeof me.x === 'number' && Math.abs(me.x - spot.x) < 14 && typeof me.y === 'number' && Math.abs(me.y - spot.y) < 14)) return;
      this.vinylWin = win;
      const stored = await this.state.storage.get('vinylWin');
      if (stored === win) return;
      await this.state.storage.put('vinylWin', win);
      me.vinyl = true;
      ws.serializeAttachment(me);
      this.broadcast({ t: 'vinyl', id: me.id });
      return;
    }

    if (msg.t === 'item' && me) { // first banana to this window's conveyor item
      const win = itemWindow(Date.now());
      if (win < 0) return;
      if (this.itemWin === win) return;       // sync guard before any await
      const spot = itemSpot(win);
      if (!(typeof me.x === 'number' && Math.abs(me.x - spot.x) < 14 && typeof me.y === 'number' && Math.abs(me.y - spot.y) < 14)) return;
      this.itemWin = win;
      const stored = await this.state.storage.get('itemWin');
      if (stored === win) return;
      await this.state.storage.put('itemWin', win);
      const kind = itemType(win);
      if (ITEM_FX[kind]) {
        me.fx = { id: ITEM_FX[kind], until: Date.now() + fxLen(ITEM_FX[kind]) };
        ws.serializeAttachment(me);
      }
      this.broadcast({ t: 'item', id: me.id, win, kind, fx: ITEM_FX[kind] ? me.fx : undefined });
      return;
    }

    // legacy: pre-conveyor clients still send 'sauce' against the old windows
    if (msg.t === 'sauce' && me) { // first banana to the hot-sauce bottle
      const win = sauceWindow(Date.now());
      if (win < 0) return;
      if (this.sauceWin === win) return;      // sync guard before any await
      const spot = sauceSpot(win);
      if (!(typeof me.x === 'number' && Math.abs(me.x - spot.x) < 14 && typeof me.y === 'number' && Math.abs(me.y - spot.y) < 14)) return;
      this.sauceWin = win;
      const stored = await this.state.storage.get('sauceWin');
      if (stored === win) return;
      await this.state.storage.put('sauceWin', win);
      me.fx = { id: 'flames', until: Date.now() + fxLen('flames') };
      ws.serializeAttachment(me);
      this.broadcast({ t: 'fx', id: me.id, fx: me.fx, src: 'sauce' });
      return;
    }

    if (msg.t === 'gold' && me) { // first banana to the golden one
      const win = goldWindow(Date.now());
      if (win < 0) return;
      if (this.goldWin === win) return;       // sync guard before any await
      const spot = goldSpot(win);
      if (!(typeof me.x === 'number' && Math.abs(me.x - spot.x) < 14 && typeof me.y === 'number' && Math.abs(me.y - spot.y) < 14)) return;
      this.goldWin = win;
      const stored = await this.state.storage.get('goldWin');
      if (stored === win) return;
      await this.state.storage.put('goldWin', win);
      this.broadcast({ t: 'gold', id: me.id });
      return;
    }

    if (msg.t === 'grab' && me) { // a raver caught a wearable DROP — a cosmetic
      // floor-wide shout only (the catch itself is client-authoritative; the
      // caught item rides in on the normal 'outfit' broadcast). No state, no race.
      // curated drops validate against DROP_IDS; community catalog items are
      // format-validated (clients resolve the label from the public manifest)
      if (typeof msg.item !== 'string' || !(DROP_IDS.includes(msg.item) || /^c_[a-f0-9]{6,32}$/.test(msg.item))) return;
      this.broadcast({ t: 'grab', id: me.id, item: msg.item });
      return;
    }

    if (msg.t === 'cocktail' && me) { // first banana at the bar during specials
      const win = specialWindow(Date.now());
      if (win < 0) return;
      if (this.cocktailWin === win) return;   // sync guard before any await
      // same generous walk-to-the-bar bound as the beer (client gates precisely)
      if (!(typeof me.x === 'number' && me.x < 70 && typeof me.y === 'number' && me.y > 64)) return;
      this.cocktailWin = win;
      const stored = await this.state.storage.get('cocktailWin');
      if (stored === win) return;
      await this.state.storage.put('cocktailWin', win);
      const drink = COCKTAILS[((win % COCKTAILS.length) + COCKTAILS.length) % COCKTAILS.length];
      me.fx = { id: drink, until: Date.now() + fxLen(drink) };
      ws.serializeAttachment(me);
      this.broadcast({ t: 'fx', id: me.id, fx: me.fx, src: 'cocktail' });
      return;
    }

    if (msg.t === 'vinylDrop' && me && me.vinyl) { // courier reached the stage edge
      if (!(typeof me.y === 'number' && me.y < 18 && me.x > 26 && me.x < 74)) return;
      me.vinyl = false;
      ws.serializeAttachment(me);
      this.broadcast({ t: 'minidrop', id: me.id });
      return;
    }

    if (msg.t === 'stage' && me) {
      if (msg.on) {
        if (Date.now() - (me.since || me.joined) < STAGE_MIN_MS) { // since = floor time across reconnects
          ws.send('{"t":"stageNo","reason":"early"}');
          return;
        }
        if (this.roster().filter((p) => p.stage).length >= STAGE_CAP) {
          ws.send('{"t":"stageNo","reason":"full"}');
          return;
        }
        me.stage = true;
      } else {
        me.stage = false;
      }
      ws.serializeAttachment(me);
      this.broadcast({ t: 'stage', id: me.id, on: me.stage }); // includes sender = server-authoritative echo
      return;
    }

    if (msg.t === 'lvl' && me) { // levelled up mid-rave — the roster title updates live
      const n = sanLvl(msg.n);
      if (!n || n === me.lvl) return;
      if (me.lvl && n < me.lvl) return; // levels only climb (no-decay rule, enforced here too)
      me.lvl = n;
      ws.serializeAttachment(me);
      this.broadcast({ t: 'lvl', id: me.id, n });
      return;
    }

    // 🍌💨 THE FOOD FIGHT relay — pure fan-out, no physics here. Clients
    // simulate every throw; the VICTIM announces its own splat (their jelly
    // is a local stat, so victim-authority is the only honest model — a
    // cheater can dodge but never hurt). Throttles match the client cooldown.
    if (msg.t === 'shot' && me) {
      const nowS = Date.now();
      if (me.lastShot && nowS - me.lastShot < 1800) return;
      me.lastShot = nowS;
      ws.serializeAttachment(me);
      const a = Number(msg.a);
      if (!isFinite(a)) return;
      this.broadcast({ t: 'shot', id: me.id, a: +a.toFixed(3) }, ws);
      return;
    }
    if (msg.t === 'splat' && me) {
      const nowS = Date.now();
      if (me.lastSplat && nowS - me.lastSplat < 900) return;
      me.lastSplat = nowS;
      ws.serializeAttachment(me);
      const n = Math.min(20, Math.max(0, Math.round(Number(msg.n) || 0)));
      const by = /^[a-f0-9-]{4,12}$/.test(String(msg.by || '')) ? msg.by : '';
      this.broadcast({ t: 'splat', id: me.id, by, n, s: (Number(msg.s) >>> 0) });
      return;
    }

    if (msg.t === 'outfit' && me) { // changed clothes mid-rave (via builder link back)
      const strikes = (await this.state.storage.get('nameStrikes')) || [];
      me.name = sanitizeName(msg.name !== undefined ? msg.name : me.name, strikes);
      if (me.name) this.recordName(me.name);
      me.outfit = sanitizeOutfit(msg.outfit);
      if (msg.sober) { me.beer = false; me.fx = undefined; } // the water: a clean slate is a CLEAN slate
      if (me.beer) me.outfit.extras.beer = true; // the beer survives a wardrobe change
      ws.serializeAttachment(me);
      this.broadcast({ t: 'outfit', id: me.id, outfit: me.outfit, name: me.name || '' });
    }
  }

  // the QUICK SWIPE: a fresh strike sweeps the live floor — matching names
  // vanish immediately (their bananas fall back to outfit-names)
  scrubName(frag) {
    for (const ws of this.state.getWebSockets()) {
      let a = null;
      try { a = ws.deserializeAttachment(); } catch (e) {}
      if (a && !a.dead && a.name && normName(a.name).includes(frag)) {
        a.name = '';
        try { ws.serializeAttachment(a); } catch (e) {}
        this.broadcast({ t: 'name', id: a.id, name: '' });
      }
    }
  }

  // rolling ledger of names seen on the floor (for the Banana Mail desk) —
  // capped, newest-first, no other data attached
  async recordName(name) {
    try {
      const seen = (await this.state.storage.get('namesSeen')) || {};
      seen[name] = Date.now();
      const entries = Object.entries(seen).sort((a, b) => b[1] - a[1]).slice(0, 300);
      await this.state.storage.put('namesSeen', Object.fromEntries(entries));
    } catch (e) {}
  }

  async webSocketClose(ws) {
    let me = null;
    try { me = ws.deserializeAttachment(); } catch (e) {}
    if (me && !me.dead) this.broadcast({ t: 'leave', id: me.id }, ws); // reaped ghosts already announced their leave
  }

  async webSocketError(ws) {
    return this.webSocketClose(ws);
  }
}

function strip(p) {
  return {
    id: p.id, outfit: p.outfit, joined: p.joined, stage: !!p.stage, vinyl: !!p.vinyl, x: p.x, y: p.y,
    fx: p.fx && p.fx.until > Date.now() ? p.fx : undefined, // active effects survive a rejoin, expired ones don't travel
    lvl: p.lvl || undefined, // club level (REP) — titles show on the floor roster
    name: p.name || undefined, // the pass name (ONE identity) — sanitized at entry
  };
}

// ============================================================================
// 🌳 THE PARK — the room outside the banana stand (S5). Deliberately tiny:
// join / move / outfit / leave, same hibernation + reaper + sanitizers as the
// floor, NONE of the event machinery (no drops, no happy hour, no quests —
// the park's life is client-side: ducks, birds, the keeper).
const PARK_CAP = 40;

export class ParkRoom {
  constructor(state) {
    this.state = state;
    this.state.setWebSocketAutoResponse(
      new WebSocketRequestResponsePair('{"t":"ping"}', '{"t":"pong"}')
    );
  }

  reapStale() {
    const now = Date.now();
    for (const ws of this.state.getWebSockets()) {
      let last = 0;
      try {
        const t = this.state.getWebSocketAutoResponseTimestamp(ws);
        if (t) last = t.getTime();
      } catch (e) {}
      let a = null;
      try { a = ws.deserializeAttachment(); } catch (e) {}
      if (a && a.joined > last) last = a.joined;
      if (last && now - last > 120_000) {
        if (a) { a.dead = true; try { ws.serializeAttachment(a); } catch (e) {} }
        try { ws.close(1011, 'stale'); } catch (e) {}
        if (a) this.broadcast({ t: 'leave', id: a.id }, ws);
      }
    }
  }

  roster() {
    return this.state.getWebSockets()
      .map((ws) => { try { return ws.deserializeAttachment(); } catch (e) { return null; } })
      .filter((a) => a && !a.dead);
  }

  broadcast(msg, exceptWs) {
    const s = JSON.stringify(msg);
    for (const ws of this.state.getWebSockets()) {
      if (ws === exceptWs) continue;
      try { ws.send(s); } catch (e) {}
    }
  }

  async fetch(request) {
    const url = new URL(request.url);
    if (url.pathname === '/count') {
      this.reapStale(); // headcount checks double as free sweeps
      return new Response(JSON.stringify({ count: this.roster().length }));
    }
    if (request.headers.get('Upgrade') !== 'websocket') {
      return new Response('expected websocket', { status: 426 });
    }
    this.reapStale();
    if (this.roster().length >= PARK_CAP) {
      return new Response('park full', { status: 503 });
    }
    const pair = new WebSocketPair();
    this.state.acceptWebSocket(pair[1]);
    return new Response(null, { status: 101, webSocket: pair[0] });
  }

  async webSocketMessage(ws, raw) {
    let msg;
    try { msg = JSON.parse(raw); } catch (e) { return; }
    if (!msg || typeof msg !== 'object') return;
    let me = null;
    try { me = ws.deserializeAttachment(); } catch (e) {}
    if (me && me.dead) return;

    if (msg.t === 'hi' && !me) {
      this.reapStale();
      // SUPERSEDE: the same browser rejoining (park→club→park) kills its own
      // ghost sockets immediately — without this, quick roundtrips stacked
      // duplicate bananas until the reaper's 120s sweep
      const sid = typeof msg.sid === 'string' ? msg.sid.slice(0, 24) : '';
      if (sid) {
        for (const other of this.state.getWebSockets()) {
          if (other === ws) continue;
          let a = null;
          try { a = other.deserializeAttachment(); } catch (e) {}
          if (a && !a.dead && a.sid === sid) {
            a.dead = true;
            try { other.serializeAttachment(a); } catch (e) {}
            try { other.close(1000, 'superseded'); } catch (e) {}
            this.broadcast({ t: 'leave', id: a.id }, other);
          }
        }
      }
      const p = {
        id: crypto.randomUUID().slice(0, 8),
        sid,
        name: sanitizeName(msg.name, []), // family filter, no strike list here
        outfit: sanitizeOutfit(msg.outfit),
        x: parkClampX(msg.x), y: parkClampY(msg.y),
        joined: Date.now(),
      };
      ws.serializeAttachment(p);
      ws.send(JSON.stringify({ t: 'roster', you: p.id, all: this.roster().map(parkStrip) }));
      this.broadcast({ t: 'join', p: parkStrip(p) }, ws);
      return;
    }
    if (msg.t === 'move' && me) {
      const now = Date.now();
      if (now - (me.lastMove || 0) < 100) return; // client sends at 150ms
      me.lastMove = now;
      me.x = parkClampX(msg.x); me.y = parkClampY(msg.y);
      ws.serializeAttachment(me);
      this.broadcast({ t: 'move', id: me.id, x: me.x, y: me.y }, ws);
      return;
    }
    if (msg.t === 'outfit' && me) { // bought something at the stand mid-visit
      me.outfit = sanitizeOutfit(msg.outfit);
      ws.serializeAttachment(me);
      this.broadcast({ t: 'outfit', id: me.id, outfit: me.outfit }, ws);
    }
  }

  async webSocketClose(ws) {
    let me = null;
    try { me = ws.deserializeAttachment(); } catch (e) {}
    if (me && !me.dead) this.broadcast({ t: 'leave', id: me.id }, ws);
  }

  async webSocketError(ws) {
    return this.webSocketClose(ws);
  }
}

function parkClampX(v) { const n = Number(v); return Number.isFinite(n) ? Math.min(95, Math.max(5, Math.round(n * 10) / 10)) : 50; }
function parkClampY(v) { const n = Number(v); return Number.isFinite(n) ? Math.min(99, Math.max(20, Math.round(n * 10) / 10)) : 90; }
function parkStrip(p) {
  return { id: p.id, outfit: p.outfit, x: p.x, y: p.y, name: p.name || undefined };
}
const sanLvl = (v) => { const n = Math.round(Number(v)); return n >= 1 && n <= 99 ? n : undefined; };
