// GENERATED by tools/build-homestead-scene.py — DO NOT EDIT.
export const WORLD = { w: 1800, h: 1100 };
export const BOUND = 96;
export const ROAD = { y: 900, hw: 44 };
export const GATE = { x: 1152, y: 816 };
export const SPAWN = { x: 1650, y: 900 };
export const EXIT_EAST = { x: 1760, y: 900, r: 60 };
export const FENCE = [336, 240, 1344, 816];
export const PLOT = [384, 302, 1296, 768];
// 🌱 land grows with the ladder: stage 0-1 → tier 1, 2 → 2, 3 → 3
export const FENCE_TIERS = {"1": {"fence": [816, 432, 1344, 816], "plot": [864, 494, 1296, 768], "cols": [[816, 450, 1344, 464], [816, 786, 1104, 812], [1200, 786, 1344, 812], [818, 450, 836, 786], [1320, 450, 1340, 786]], "yard": ["ov-fyard1.png", 816, 432, 528, 336, 464], "south": ["ov-fsouth1.png", 816, 764, 528, 56, 816]}, "2": {"fence": [576, 336, 1344, 816], "plot": [624, 398, 1296, 768], "cols": [[576, 354, 1344, 368], [576, 786, 1104, 812], [1200, 786, 1344, 812], [578, 354, 596, 786], [1320, 354, 1340, 786]], "yard": ["ov-fyard2.png", 576, 336, 768, 432, 368], "south": ["ov-fsouth2.png", 576, 764, 768, 56, 816]}, "3": {"fence": [336, 240, 1344, 816], "plot": [384, 302, 1296, 768], "cols": [[336, 258, 1344, 272], [336, 786, 1104, 812], [1200, 786, 1344, 812], [338, 258, 356, 786], [1320, 258, 1340, 786]], "yard": ["ov-fyard3.png", 336, 240, 1008, 528, 272], "south": ["ov-fsouth3.png", 336, 764, 1008, 56, 816]}};
export const BED = { w: 280, h: 100, def: { x: 1010, y: 730 }, slots: [[-90, -32], [-20, -32], [50, -32], [120, -32]] };
export const TENT = { x: 1000, y: 560, w: 140, h: 136, solid: [-62, -20, 62, 4] };
export const STRUCT_STYLES = {1: ["tent1", "tent2", "tent3", "tent4", "tent5", "tent6"], 2: ["mob1", "mob2", "mob3", "mob4", "mob5", "mob6", "mob7", "mob8", "mobm1", "mobm2", "mobm3", "mobm4", "mobm5", "mobm6", "mobm7", "mobm8", "barn", "hloftgreen", "hloftgrey", "hloftred", "hloftyellow"], 3: ["country", "haunted", "japanese", "villa1", "villa2", "villa3", "villa4", "villa5", "condoa", "condo6", "condo9"]};
export const STRUCTS = { tent1: { w: 140, h: 136 }, tent2: { w: 140, h: 136 }, tent3: { w: 140, h: 136 }, tent4: { w: 117, h: 92 }, tent5: { w: 117, h: 92 }, tent6: { w: 117, h: 92 }, mob1: { w: 282, h: 163 }, mob2: { w: 282, h: 163 }, mob3: { w: 282, h: 163 }, mob4: { w: 282, h: 163 }, mob5: { w: 244, h: 186 }, mob6: { w: 244, h: 186 }, mob7: { w: 244, h: 186 }, mob8: { w: 244, h: 186 }, mobm1: { w: 224, h: 163 }, mobm2: { w: 224, h: 163 }, mobm3: { w: 224, h: 163 }, mobm4: { w: 224, h: 163 }, mobm5: { w: 180, h: 172 }, mobm6: { w: 180, h: 172 }, mobm7: { w: 180, h: 172 }, mobm8: { w: 180, h: 172 }, barn: { w: 188, h: 250 }, hloftgreen: { w: 433, h: 202 }, hloftgrey: { w: 433, h: 202 }, hloftred: { w: 433, h: 202 }, hloftyellow: { w: 433, h: 202 }, country: { w: 356, h: 322 }, haunted: { w: 278, h: 321 }, japanese: { w: 354, h: 330 }, villa1: { w: 229, h: 331 }, villa2: { w: 229, h: 331 }, villa3: { w: 229, h: 331 }, villa4: { w: 229, h: 331 }, villa5: { w: 229, h: 331 }, condoa: { w: 103, h: 309 }, condo6: { w: 285, h: 327 }, condo9: { w: 159, h: 319 } };
export const MAILBOX = { x: 1252, y: 850 };
export const SIGN = { x: 1010, y: 850 };
export const OB_RECTS = [[1238, 838, 1266, 852], [994, 840, 1026, 852], [141, 868, 229, 890]];
export const OVERLAYS = [['ov-0.png', 1235, 808, 35, 42, 850], ['ov-1.png', 995, 819, 31, 31, 850]];
export const BIRDS = ["cardinal", "bluejay", "chickadee", "redrobin", "whitedove", "magpie"];
