// GENERATED by tools/build-homestead-scene.py — DO NOT EDIT.
export const WORLD = { w: 1800, h: 1100 };
export const BOUND = 96;
export const ROAD = { y: 900, hw: 44 };
export const GATE = { x: 1152, y: 816 };
export const SPAWN = { x: 1650, y: 900 };
export const EXIT_EAST = { x: 1760, y: 900, r: 60 };
export const FENCE = [336, 240, 1680, 816];
export const PLOT = [384, 302, 1632, 768];
// 🌱 land grows with the ladder: stage 0-1 → tier 1, 2 → 2, 3 → 3
export const FENCE_TIERS = {"1": {"fence": [816, 432, 1344, 816], "plot": [864, 494, 1296, 768], "cols": [[816, 450, 1344, 464], [816, 786, 1104, 820], [1200, 786, 1344, 820], [818, 450, 836, 786], [1320, 450, 1340, 786]], "yard": ["ov-fyard1.png", 816, 432, 528, 336, 464], "south": ["ov-fsouth1.png", 816, 764, 528, 56, 816]}, "2": {"fence": [576, 336, 1344, 816], "plot": [624, 398, 1296, 768], "cols": [[576, 354, 1344, 368], [576, 786, 1104, 820], [1200, 786, 1344, 820], [578, 354, 596, 786], [1320, 354, 1340, 786]], "yard": ["ov-fyard2.png", 576, 336, 768, 432, 368], "south": ["ov-fsouth2.png", 576, 764, 768, 56, 816]}, "3": {"fence": [336, 240, 1680, 816], "plot": [384, 302, 1632, 768], "cols": [[336, 258, 1680, 272], [336, 786, 1104, 820], [1200, 786, 1680, 820], [338, 258, 356, 786], [1656, 258, 1676, 786]], "yard": ["ov-fyard3.png", 336, 240, 1344, 528, 272], "south": ["ov-fsouth3.png", 336, 764, 1344, 56, 816]}};
export const BED = { w: 280, h: 100, def: { x: 1010, y: 730 }, slots: [[-90, -32], [-20, -32], [50, -32], [120, -32]] };
export const TENT = { x: 1000, y: 560, w: 140, h: 136, solid: [-62, -20, 62, 4] };
export const STRUCT_STYLES = {1: ["tent1", "tent2", "tent3"], 2: ["mobm3", "mobm7"], 3: ["country"]};
export const STRUCTS = { tent1: { w: 140, h: 136 }, tent2: { w: 140, h: 136 }, tent3: { w: 140, h: 136 }, mobm3: { w: 224, h: 163 }, mobm7: { w: 180, h: 172 }, country: { w: 356, h: 322 } };
export const MAILBOX = { x: 1252, y: 850, w: 35, h: 42 };
export const SIGN = { x: 1010, y: 850, w: 31, h: 31 };
export const OB_RECTS = [[141, 868, 229, 890]];
export const OVERLAYS = [];
export const BIRDS = ["cardinal", "bluejay", "chickadee", "redrobin", "whitedove", "magpie"];
export const INTERIORS = {"2": {"img": "in-wood2.png", "box": [732, 372, 336, 288], "spawn": [900, 604], "exit": [854, 642, 946, 660], "cols": [[732, 372, 1068, 472], [732, 372, 746, 660], [1054, 372, 1068, 660], [732, 646, 840, 660], [960, 646, 1068, 660]]}, "3": {"img": "in-wood3.png", "box": [588, 332, 624, 432], "spawn": [900, 708], "exit": [854, 746, 946, 764], "cols": [[588, 332, 1212, 432], [588, 332, 602, 764], [1198, 332, 1212, 764], [588, 750, 840, 764], [960, 750, 1212, 764]]}, "1": {"img": "in-tent.png", "box": [780, 408, 240, 192], "spawn": [900, 556], "exit": [858, 578, 942, 598], "cols": [[780, 408, 1020, 424], [780, 408, 796, 600], [1004, 408, 1020, 600], [780, 584, 854, 600], [946, 584, 1020, 600], [810, 480, 868, 536], [926, 482, 994, 528]]}};
