// 🌱 THE GARDEN — the park's daily-return ritual (P3b) + the entropy loop
// (weeds/trash/eggs/bloom, P3b-LOOP) + the tool slot + the health bar.
// Split from banana-park.js (P5); wired through the shared ctx.
import { poofInto, worldSid } from '../lib/world.js';
import { passStat, passGet } from '../lib/banana-pass.js';
import { iconSvg } from '../lib/pixel-icons.js';
import { PLOTS, BORDER_SPOTS, ALGAE_SPOTS, BIRD_SPOTS, POND } from './park-geo.js';
import { track, PARK_TEST, R, SVG, esc, PHASE_STARTS } from './park-util.js';
import { hasVoucher, setVoucher, VOUCHER_MAX } from './park-fountain.js';

// ?phase=0..4 — bookmarkable phase-view links (Trym): forces that phase's
// full visual state (plates/trees/critters/fountain/pill) RENDER-ONLY; the
// server data still flows (weeds/plants/eggs), only the phase is pinned.
const PHASE_FORCE = (() => {
  if (typeof location === 'undefined') return -1;
  const m = location.search.match(/[?&]phase=([0-4])(?:&|$)/);
  return m ? +m[1] : -1;
})();
const PHASE_MID = [10, 30, 50, 70, 90];   // a mid-band % to show when pinned
// the health bar's phase faces — real PixelIcon glyphs (pixelarticons Pro,
// bundled via src/icons/pixelart/), dead → joy. Never stock-emoji faces.
const PHASE_FACES = ['skull', 'frown', 'meh', 'smile', 'laugh'];

// 🪧 the ownership stake — a tiny garden-label stake (plank-wood palette,
// banana-density) planted at the soil's front edge of YOUR plants only.
// The chips it replaced "took up much of the visuals" (Trym): species = the
// sprite, thirst = the soil, ready = the glint — only ownership needed art.
const STAKE_SVG = SVG('7 12',
  R(1, 0, 5, 1, '#3a2b18')
  + R(0, 1, 1, 4, '#3a2b18') + R(6, 1, 1, 4, '#3a2b18')
  + R(1, 1, 5, 3, '#b8834a') + R(1, 1, 5, 1, '#d9a860') + R(1, 1, 1, 3, '#d9a860')
  + R(1, 4, 5, 1, '#8a5a2b') + R(1, 5, 5, 1, '#3a2b18')
  + R(2, 6, 3, 5, '#8a5a2b') + R(4, 6, 1, 5, '#6b4320')
  + R(3, 11, 1, 1, '#4a3018'));

// ⚠️ THE seed catalog — stars/days/price must match GARDEN_SEEDS in
// worker-rave/src/index.js (one catalog, two runtimes). ⭐ stars have ONE
// meaning: a living plant feeds the Bloom by its stars (higher also wilts
// slower, server-side). Flowers harvest into DRAFT wearables (own_<id> pass
// stats, /dev-wearables desk); crops pay rep (stars × 8) — crop wearables
// wait on a Trym batch review.
const SEEDS = [
  { id: 'daisy', emoji: '🌼', name: 'daisy', stars: 1, price: 10, days: 2, wearable: 'daisypin', wearLabel: 'daisy pin' },
  // sunflower wearable TBD (round 4: the crown draft was dropped) — pays rep meanwhile
  { id: 'sunflower', emoji: '🌻', name: 'sunflower', stars: 2, price: 25, days: 4 },
  { id: 'tulip', emoji: '🌷', name: 'midnight tulip', stars: 3, price: 60, days: 5, wearable: 'midnighttulip', wearLabel: 'midnight tulip', rare: true },
  { id: 'tomato', emoji: '🍅', name: 'tomato', stars: 3, price: 90, days: 4, crop: 1 },
  { id: 'pumpkin', emoji: '🎃', name: 'pumpkin', stars: 4, price: 160, days: 5, crop: 1 },
  { id: 'wheat', emoji: '🌾', name: 'golden wheat', stars: 5, price: 300, days: 6, crop: 1, rare: true },
];
const SEED_BY = {};
SEEDS.forEach((s) => { SEED_BY[s.id] = s; });
const starStr = (n) => '⭐'.repeat(n);
// 🧑‍🌾 gardener level — derived from total harvests (garden_harvests pass
// stat): reach GLVL_AT[i] harvests → level i+1 → seeds up to GLVL_STARS[i]
const GLVL_AT = [0, 3, 8, 15];
const GLVL_STARS = [2, 3, 4, 5];
// growth-stage sprites (generated by build-park-scene.py, pack art) + dims;
// crops carry four stages of their own (c-<id>-1..4)
const STAGE_ART = {
  sprout1: ['g-sprout1.png', 24, 28], sprout2: ['g-sprout2.png', 24, 33],
  daisy: ['g-daisy.png', 26, 31], sunflower: ['g-sunflower.png', 31, 47], tulip: ['g-tulip.png', 31, 26],
  tomato1: ['c-tomato-1.png', 22, 19], tomato2: ['c-tomato-2.png', 22, 33],
  tomato3: ['c-tomato-3.png', 22, 38], tomato4: ['c-tomato-4.png', 28, 58],
  pumpkin1: ['c-pumpkin-1.png', 28, 19], pumpkin2: ['c-pumpkin-2.png', 38, 28],
  pumpkin3: ['c-pumpkin-3.png', 38, 35], pumpkin4: ['c-pumpkin-4.png', 38, 51],
  wheat1: ['c-wheat-1.png', 24, 12], wheat2: ['c-wheat-2.png', 24, 24],
  wheat3: ['c-wheat-3.png', 24, 26], wheat4: ['c-wheat-4.png', 31, 38],
};
// 🌼 BORDER FLOWERS — single-tap roadside decoration on the generator's
// BORDER_SPOTS (bare-soil dots baked into the plate): 3 coins, one stage,
// no watering, no stars, no harvest — ~7 days of life (server expires on
// read), your name on the tap card. ⚠️ kind ids must match BORDER_KINDS in
// worker-rave/src/index.js + the b-<id>.png sprites the generator bakes.
const BORDER_FLOWERS = [
  { id: 'marigold', name: 'marigold', emoji: '🌼' },
  { id: 'poppy', name: 'poppy', emoji: '🌺' },
  { id: 'bluebell', name: 'bluebell', emoji: '🪻' },
  { id: 'primrose', name: 'primrose', emoji: '🌸' },
];
const BORDER_PRICE = 3;
const BORDER_ART = {
  marigold: ['b-marigold.png', 17, 15], poppy: ['b-poppy.png', 12, 15],
  bluebell: ['b-bluebell.png', 17, 15], primrose: ['b-primrose.png', 17, 12],
};
// 🫧 POND ALGAE — the weed grammar ON the water. Neither pack has an
// algae/lily-scum sprite (searched), so a patch is a tinted translucent
// blob — water-surface FX under the FX exception, not a world object.
// The skim walk targets the pond BANK nearest the patch (bananas can't
// swim); the skim itself reaches across the water.
const ALGAE_REACH = 60;             // close enough to the bank point to skim
// 🐦 BIRDHOUSES — 4 bare pack posts baked by the generator; building hangs
// the pack's Little_Bird_House over the post (colour by spot index) with
// the builder's name on the tap card. Stocked <24h = the birds are in.
const BH_PRICE = 30;
const BH_ART = [36, 72];            // bh-house-N.png dims (covers the post)

const GARDEN_API = 'https://banana-rave.trymstene.workers.dev/park-garden';
// 🌿 weed spots for the ?parktest shim only — the real list lives server-side
// in worker-rave (keep in sync); two sprite variants picked by id hash
const WEED_SPOTS_QA = [[380, 690], [960, 640], [1700, 560], [1650, 700], [900, 1000], [1550, 950]];

// 🧰 THE TOOL SLOT — tools for chores, taps for things (Trym): ONE morphing
// action-bar button, live only while a chore is in range; press = do the
// NEAREST one (walk the last step if needed). Tapping the thing still works.
const TOOL_RANGE = 110;

// 🌸 the bloom card IS the bar (Trym): five tappable phase segments, a
// glyph each, wilted→lush ramp; a tap reveals that phase's line below
const PHASE_GLYPHS = ['💀', '🍂', '🌱', '🌿', '🦋'];
// ONE line per phase (Trym): the state + what to do about it
const PHASE_LINES = [
  '💀 the park is dead — pull the weeds and plant something.',
  '🍂 wilting badly — keep pulling, keep planting.',
  '🌾 patchy, half straw — water what grows.',
  '🌿 nearly back — keep it watered and weeded.',
  '🦋 the park is thriving — hold it here and an egg can come out golden.',
];

export function initGarden(ctx) {
  const { W, H, world, pct, depth, float, toast, pos, tgt, coinBal, refreshHud } = ctx;

  // ---- 🌱 THE GARDEN — plant · water · harvest ----------------------------
  // Server truth lives on the ParkRoom DO (/park-garden); the client renders
  // the plots from polled state, acts optimistically, and reconciles on the
  // reply. ?parktest swaps the fetch for a local shim so the whole flow runs
  // before the worker deploy (+ __park.ff() fast-forwards growth locally).
  const myShort = worldSid().slice(0, 8);
  const gardenPanel = document.getElementById('pkGarden');
  const gardenBody = document.getElementById('pkGardenBody');
  // 64 slots — 0-7 site A (meadow), 8-15 site B (playground), 16-23 site C
  // (NE, the lawn the stand freed); the 31 Jul expansion APPENDED 24-31 A2 ·
  // 32-39 B2 · 40-47 C2 · 48-63 site D (the pond's SE bank). ⚠️ indices are
  // the contract, never reorder.
  let gSlots = Array(64).fill(null);
  const gEls = PLOTS.map(() => ({ plant: null, stage: '', soil: null, soilKey: '', stake: null }));
  let pendingGarden = null, pendingWater = null, gardenOpenSlot = -1;
  let plantTracked = false, waterTracked = false, harvestTracked = false;
  const gShim = {   // the ?parktest stand-in server (pre-lays a plain + golden egg)
    slots: Array(64).fill(null), weeds: [], trash: [], bloom: 70,
    eggs: [{ id: 'qa1', x: 1330, y: 876 }, { id: 'qa2', x: 1432, y: 866, g: 1 }],
    // one pre-planted border flower so the named tap card is testable at once
    border: [{ spot: 1, kind: 'marigold', name: 'Inka', at: Date.now() - 3 * 86400000 }],
    // two scum patches + one built-and-stocked birdhouse, testable at once
    algae: [{ id: 'qg1', x: ALGAE_SPOTS[2][0], y: ALGAE_SPOTS[2][1] },
      { id: 'qg2', x: ALGAE_SPOTS[ALGAE_SPOTS.length - 3][0], y: ALGAE_SPOTS[ALGAE_SPOTS.length - 3][1] }],
    leaves: [],
    houses: [{ spot: 1, name: 'Inka', passShort: 'qashort', builtAt: Date.now() - 86400000, lastStock: Date.now() - 3600000, stockers: 2, sday: {} }],
  };
  function shimGarden(path, body) {
    const now = Date.now();
    const strip = () => ({
      ok: 1,
      slots: gShim.slots.map((s) => (s ? { ...s, waterers: (s.waterers || []).length } : null)),
      // the shim mirrors the worker's wire: one decimal, and the same
      // tidiness ceiling (0.3/weed · 0.6/algae · 0.8/litter) so ?parktest
      // behaves like the live park instead of pinning at 100
      bloom: Math.round(Math.min(gShim.bloom, 100
        - (0.3 * gShim.weeds.length + 0.6 * gShim.algae.length
          + 0.8 * gShim.trash.length)) * 10) / 10,
      weeds: gShim.weeds.map((w2) => ({ ...w2 })),
      trash: gShim.trash.map((t) => ({ ...t })),
      eggs: gShim.eggs.map((e) => ({ ...e })),
      border: gShim.border.map((f) => ({ ...f })),
      algae: gShim.algae.map((a2) => ({ ...a2 })),
      leaves: gShim.leaves.map((l2) => ({ ...l2 })),
      houses: gShim.houses.map((h2) => ({ ...h2 })),
    });
    if (!body) return Promise.resolve(strip());
    if (path === '/algae') {
      const ai = gShim.algae.findIndex((a2) => a2.id === body.id);
      if (ai < 0) return Promise.resolve({ err: 'gone', ...strip() });
      gShim.algae.splice(ai, 1);
      gShim.bloom = Math.min(100, gShim.bloom + 0.3);
      return Promise.resolve(strip());
    }
    if (path === '/rake') {
      const li = gShim.leaves.findIndex((l2) => l2.id === body.id);
      if (li < 0) return Promise.resolve({ err: 'gone', ...strip() });
      gShim.leaves.splice(li, 1);
      gShim.bloom = Math.min(100, gShim.bloom + 0.4);
      return Promise.resolve(strip());
    }
    if (path === '/bhbuild') {
      if (gShim.houses.some((h2) => h2.spot === body.spot)) return Promise.resolve({ err: 'taken', ...strip() });
      gShim.houses.push({ spot: body.spot, name: body.name || '', passShort: myShort,
        builtAt: now, lastStock: now, stockers: 1, sday: { [myShort]: Math.floor(now / 86400000) } });
      return Promise.resolve(strip());
    }
    if (path === '/bhstock') {
      const h2 = gShim.houses.find((x2) => x2.spot === body.spot);
      if (!h2) return Promise.resolve({ err: 'empty', ...strip() });
      if (h2.sday[myShort] === Math.floor(now / 86400000)) return Promise.resolve({ err: 'stocked today', ...strip() });
      h2.sday[myShort] = Math.floor(now / 86400000);
      h2.lastStock = now;
      h2.stockers += 1;
      return Promise.resolve(strip());
    }
    if (path === '/egg') {
      const ei = gShim.eggs.findIndex((e) => e.id === body.id);
      if (ei < 0) return Promise.resolve({ err: 'gone', ...strip() });
      const [e] = gShim.eggs.splice(ei, 1);
      const reward = e.g ? { coins: 25, tickets: 5, golden: 1 }
        : Math.random() < 0.25 ? { tickets: 3 } : { coins: 3 + Math.floor(Math.random() * 6) };
      return Promise.resolve({ reward, ...strip() });
    }
    if (path === '/trash') {
      const ti = gShim.trash.findIndex((t) => t.id === body.id);
      if (ti < 0) return Promise.resolve({ err: 'gone', ...strip() });
      gShim.trash.splice(ti, 1);
      gShim.bloom = Math.min(100, gShim.bloom + 1);
      return Promise.resolve(strip());
    }
    if (path === '/weed') {
      const wi = gShim.weeds.findIndex((w2) => w2.id === body.id);
      if (wi < 0) return Promise.resolve({ err: 'gone', ...strip() });
      gShim.weeds.splice(wi, 1);
      gShim.bloom = Math.min(100, gShim.bloom + 3);
      return Promise.resolve(strip());
    }
    if (path === '/border') {
      if (gShim.border.some((f) => f.spot === body.spot)) return Promise.resolve({ err: 'taken', ...strip() });
      gShim.border.push({ spot: body.spot, kind: body.kind, name: body.name || '', at: now });
      return Promise.resolve(strip());
    }
    const i = body.slot, s = gShim.slots[i];
    if (path === '/plant') {
      if (s) return Promise.resolve({ err: 'taken', ...strip() });
      gShim.slots[i] = { passShort: myShort, name: body.name || '', seed: body.seed, plantedAt: now, lastWater: now, waterers: [] };
      gShim.bloom = Math.min(100, gShim.bloom + 6);
    } else if (path === '/water') {
      if (!s) return Promise.resolve({ err: 'empty' });
      s.lastWater = now;
      if (!s.waterers.includes(body.pass.slice(0, 8))) s.waterers.push(body.pass.slice(0, 8));
      gShim.bloom = Math.min(100, gShim.bloom + 2);
    } else if (path === '/harvest') {
      if (!s) return Promise.resolve({ err: 'empty' });
      if (Math.floor((now - s.plantedAt) / 86400000) < SEED_BY[s.seed].days) return Promise.resolve({ err: 'still growing' });
      gShim.slots[i] = null;
    }
    return Promise.resolve(strip());
  }
  async function gFetch(path, body) {
    if (PARK_TEST) return shimGarden(path, body);
    try {
      const r = await fetch(GARDEN_API + path, body
        ? { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }
        : undefined);
      return await r.json();
    } catch (e) { return null; }   // no server, no garden — the park still works
  }
  const gDays = (s) => Math.floor((Date.now() - s.plantedAt) / 86400000);
  const gReady = (s) => s && gDays(s) >= (SEED_BY[s.seed] || { days: 99 }).days;
  const gMine = (s) => s && s.passShort === myShort;
  // watered today? (UTC day, matching the server's wday math)
  const gWet = (s) => s && Math.floor((s.lastWater || 0) / 86400000) === Math.floor(Date.now() / 86400000);
  function gStageArt(s) {
    const sd = SEED_BY[s.seed] || SEEDS[0];
    const t = gDays(s) / sd.days;
    if (sd.crop) {   // crops grow through their own four baked stages
      return STAGE_ART[s.seed + (t >= 1 ? 4 : t >= 0.66 ? 3 : t >= 0.33 ? 2 : 1)];
    }
    return t >= 1 ? STAGE_ART[s.seed] : t >= 0.4 ? STAGE_ART.sprout2 : STAGE_ART.sprout1;
  }
  // 🧑‍🌾 gardener level from harvests: [lvl 1..GLVL_AT.length, harvests, max ⭐]
  function gardenerLvl() {
    const n = (passGet().stats || {}).garden_harvests || 0;
    let l = 1;
    while (l < GLVL_AT.length && n >= GLVL_AT[l]) l++;
    return { lvl: l, n, stars: GLVL_STARS[l - 1] };
  }
  // zero floating UI over the beds (Trym — signs cramped, then the emoji
  // chips "took up the visuals" too): the sprite says species, the soil says
  // thirst, the glint says ready, the stake says yours. Words = the tap card.
  function renderGarden() {
    PLOTS.forEach(([sx, sy], i) => {
      const s = gSlots[i], el = gEls[i];
      if (!s) {
        if (el.plant) { el.plant.remove(); el.plant = null; el.stage = ''; }
        if (el.stake) { el.stake.remove(); el.stake = null; }
        if (el.soil) { el.soil.remove(); el.soil = null; el.soilKey = ''; }
        return;
      }
      // 💧 the soil tells the state: dark wet = watered today, light dry = not
      const wet = gWet(s) ? 'wet' : 'dry';
      if (el.soilKey !== wet) {
        el.soilKey = wet;
        if (!el.soil) {
          el.soil = document.createElement('div');
          el.soil.className = 'pk-soil';
          el.soil.style.left = pct(sx, W);
          el.soil.style.top = pct(sy + 12, H);
          el.soil.style.width = pct(39, W);
          el.soil.style.height = pct(25, H);
          el.soil.style.zIndex = String(100 + Math.round(sy));   // under the plant
          world.appendChild(el.soil);
        }
        el.soil.classList.toggle('pk-soil--wet', wet === 'wet');
        el.soil.classList.toggle('pk-soil--dry', wet === 'dry');
      }
      const [img, w2, h2] = gStageArt(s);
      const key = img + (gReady(s) ? '!' : '');
      if (el.stage !== key) {
        el.stage = key;
        if (!el.plant) {
          el.plant = document.createElement('div');
          el.plant.className = 'pk-plant';
          world.appendChild(el.plant);
        }
        el.plant.style.backgroundImage = "url('/assets/park/" + img + "')";
        el.plant.style.width = pct(w2, W);
        el.plant.style.height = pct(h2, H);
        el.plant.style.left = pct(sx, W);
        el.plant.style.top = pct(sy + 10, H);
        el.plant.classList.toggle('is-ready', gReady(s));
        depth(el.plant, sy + 10);
      }
      // 🪧 ownership: the tiny stake at the soil's front edge, YOURS only
      // (no floating UI over the beds — Trym; taps read the slot, not this)
      if (gMine(s) && !el.stake) {
        el.stake = document.createElement('div');
        el.stake.className = 'pk-gstake';
        el.stake.innerHTML = STAKE_SVG;
        el.stake.style.left = pct(sx - 13, W);
        el.stake.style.top = pct(sy + 21, H);
        el.stake.style.width = pct(7, W);
        el.stake.style.height = pct(12, H);
        el.stake.style.zIndex = String(100 + Math.round(sy) + 12);
        world.appendChild(el.stake);
      } else if (!gMine(s) && el.stake) {
        el.stake.remove();
        el.stake = null;
      }
    });
  }
  // ---- 🌼 BORDER FLOWERS — the road shoulders are the community's canvas --
  // A baked soil dot marks every empty spot; a planted one is a single pack
  // flower with its planter's name on the tap card. Pure decoration: no
  // bloom feed, no watering — it lives ~7 days, fades near the end (client
  // opacity), and the server sweeps it on read. First-come per spot.
  let bSpots = Array(BORDER_SPOTS.length).fill(null);   // spot → entry | null
  const bEls = BORDER_SPOTS.map(() => null);
  let pendingBorder = null, borderTracked = false;
  const borderKind = (id) => BORDER_FLOWERS.find((f) => f.id === id) || BORDER_FLOWERS[0];
  function renderBorder(list) {
    bSpots = Array(BORDER_SPOTS.length).fill(null);
    (list || []).forEach((f) => {
      if (f.spot >= 0 && f.spot < bSpots.length) bSpots[f.spot] = f;
    });
    BORDER_SPOTS.forEach(([sx, sy], i) => {
      const f = bSpots[i];
      let el = bEls[i];
      if (!f) {
        if (el) { el.remove(); bEls[i] = null; }   // faded out — empty pot again
        return;
      }
      if (!el) {
        el = bEls[i] = document.createElement('div');
        el.className = 'pk-bflower';
        el.style.left = pct(sx, W);
        el.style.top = pct(sy - 12, H);   // sits IN the planter's soil, not below it
        depth(el, sy);
        world.appendChild(el);
      }
      if (el.dataset.kind !== f.kind) {
        el.dataset.kind = f.kind;
        const [img, w2, h2] = BORDER_ART[f.kind] || BORDER_ART.marigold;
        el.style.backgroundImage = "url('/assets/park/" + img + "')";
        el.style.width = pct(w2, W);
        el.style.height = pct(h2, H);
      }
      // the last stretch of its ~7 days: it visibly wilts before it goes
      el.classList.toggle('is-fading', Date.now() - (f.at || 0) > 6 * 86400000);
    });
  }
  function openBorderSheet(i) {
    const bal = coinBal();
    gardenBody.innerHTML = '<h2>a bare road spot</h2>'
      + '<p class="pk-panel__sub">plant a little flower here — pure prettiness, with your '
      + 'name on it. it lives about a week, then the spot frees up for somebody else.</p>'
      + BORDER_FLOWERS.map((f) =>
        '<button class="pk-seedrow" type="button" data-kind="' + f.id + '"'
        + (bal < BORDER_PRICE ? ' disabled' : '') + '>'
        + '<i>' + f.emoji + '</i>'
        + '<span class="pk-seedrow__txt"><b>' + f.name + '</b>'
        + '<small>one flower · ~7 days</small></span>'
        + coinChip(BORDER_PRICE) + '</button>').join('')
      + (bal < BORDER_PRICE ? '<p class="pk-seedpoor">no coins — pull a few weeds, the roots sometimes pay</p>' : '');
    gardenBody.querySelectorAll('.pk-seedrow').forEach((b) => {
      b.addEventListener('click', () => plantBorder(i, b.dataset.kind));
    });
    gardenPanel.hidden = false;
  }
  async function plantBorder(i, kindId) {
    if (coinBal() < BORDER_PRICE) return;
    passStat('coins_spent', BORDER_PRICE);
    refreshHud();
    closeGarden();
    const res = await gFetch('/border', { spot: i, kind: kindId, name: ctx.parkName, pass: worldSid() });
    if (res && res.err === 'taken') {
      passStat('coins_spent', -BORDER_PRICE);   // refund — beaten to the spot
      refreshHud();
      toast('somebody beat you to this spot');
      applyGarden(res);
      return;
    }
    applyGarden(res);
    const kd = borderKind(kindId);
    float(BORDER_SPOTS[i][0], BORDER_SPOTS[i][1] - 6, kd.emoji);
    toast(kd.emoji + ' ' + kd.name + ' planted — the road just got prettier');
    if (!borderTracked) { borderTracked = true; track('park_border', { kind: kindId }); }
  }
  function openBorderCard(i) {
    const f = bSpots[i];
    if (!f) { openBorderSheet(i); return; }
    const kd = borderKind(f.kind);
    gardenBody.innerHTML = '<h2>' + kd.emoji + ' '
      + esc(f.name || 'a mystery banana') + '’s ' + kd.name + '</h2>'
      + '<p class="pk-panel__sub">planted by the roadside to make the park prettier.</p>';
    gardenPanel.hidden = false;
  }
  function borderAct(i) { if (bSpots[i]) openBorderCard(i); else openBorderSheet(i); }
  function tapBorder(wx, wy) {
    let best = -1, bd2 = 1e9;
    BORDER_SPOTS.forEach(([sx, sy], i) => {
      const d = Math.hypot(wx - sx, wy - (sy - (bSpots[i] ? 8 : 0)));
      if (d < 26 && d < bd2) { bd2 = d; best = i; }
    });
    if (best < 0) return false;
    const [sx, sy] = BORDER_SPOTS[best];
    if (Math.hypot(pos.x - sx, pos.y - sy) < 90) { borderAct(best); return true; }
    pendingBorder = best;                 // walk-then-act, like everything else
    tgt.x = sx;
    tgt.y = sy + 20;
    return true;
  }

  // ---- 🫧 POND ALGAE — the weed grammar on water --------------------------
  // Server truth on the garden read (cadence ~half the weed beat). A patch
  // is a translucent blob ON the water (surface FX, z under every walker);
  // the tap walks you to the BANK nearest the patch, then the skim reaches
  // across — ripple + poof + 1 rep, first touch wins.
  const algae = new Map();                      // id → { el, x, y, bx, by }
  let pendingAlgae = null, algaeTracked = false;
  function bankPoint(x, y) {
    // the shore point on the patch's ray from the pond's centre, just past
    // the engine's pond collider (ellipse norm 1.13 — solid stops at 1)
    let dx = (x - POND.x) / POND.rx, dy = (y - POND.y) / POND.ry;
    const n = Math.hypot(dx, dy) || 1;
    return { x: POND.x + (dx / n) * 1.13 * POND.rx, y: POND.y + (dy / n) * 1.13 * POND.ry };
  }
  function algaeSvg(seed) {
    const r = (n) => { seed = (Math.imul(seed, 1103515245) + 12345) & 0x7fffffff; return seed % n; };
    let bd2 = '';
    for (let i = 0; i < 5; i++) {
      bd2 += '<ellipse cx="' + (14 + r(20)) + '" cy="' + (9 + r(10)) + '" rx="' + (7 + r(7))
        + '" ry="' + (4 + r(3)) + '" fill="' + (i % 2 ? '#1e4a26' : '#2a5e2e')
        + '" opacity="0.5"/>';
    }
    return SVG('48 28', bd2);
  }
  function renderAlgae(list) {
    const seen = new Set();
    (list || []).forEach((a2) => {
      seen.add(a2.id);
      if (algae.has(a2.id)) return;
      const el = document.createElement('div');
      el.className = 'pk-algae';
      el.innerHTML = algaeSvg((parseInt(a2.id, 36) || 7) >>> 0);
      el.style.left = pct(a2.x, W);
      el.style.top = pct(a2.y, H);
      world.appendChild(el);
      const b2 = bankPoint(a2.x, a2.y);
      algae.set(a2.id, { el, x: a2.x, y: a2.y, bx: b2.x, by: b2.y });
    });
    algae.forEach((a2, id) => {
      if (!seen.has(id)) { a2.el.remove(); algae.delete(id); }   // skimmed elsewhere
    });
  }
  async function skimAlgae(id) {
    const a2 = algae.get(id);
    if (!a2) return;
    algae.delete(id);                       // optimistic — the poll reconciles
    a2.el.classList.add('is-skimmed');
    setTimeout(() => a2.el.remove(), 420);
    const rp = document.createElement('i');   // the skim ripple, on the water
    rp.className = 'pk-ripple';
    rp.style.left = pct(a2.x, W);
    rp.style.top = pct(a2.y, H);
    world.appendChild(rp);
    setTimeout(() => rp.remove(), 900);
    poofInto(world, 'pk-poof', a2.x / W * 100, (a2.y - 8) / H * 100);
    passStat('rep', 1);
    refreshHud();
    float(a2.x, a2.y - 14, '+1');
    if (!algaeTracked) { algaeTracked = true; track('park_algae'); }
    applyGarden(await gFetch('/algae', { id, pass: worldSid() }));
  }
  function tapAlgae(wx, wy) {
    let hit = null;
    algae.forEach((a2, id) => {
      if (Math.hypot(wx - a2.x, wy - a2.y) < 32) hit = id;
    });
    if (hit == null) return false;
    const a2 = algae.get(hit);
    if (Math.hypot(pos.x - a2.bx, pos.y - a2.by) < ALGAE_REACH) { skimAlgae(hit); return true; }
    pendingAlgae = hit;                   // walk to the bank, then skim
    tgt.x = a2.bx;
    tgt.y = a2.by;
    return true;
  }

  // ---- 🐦 BIRDHOUSES — build once (30 🪙), stock daily --------------------
  // 4 bare posts baked by the generator (BIRD_SPOTS); a built house is a
  // client overlay that covers its post exactly, with the builder's name on
  // the tap card. Stocked in the last 24h = 2-3 birds flutter around it and
  // the house feeds park health (+0.04/h, server-side).
  let bHouses = Array(BIRD_SPOTS.length).fill(null);
  const bhEls = BIRD_SPOTS.map(() => null);
  let pendingPost = null, bhBuildTracked = false, bhStockTracked = false;
  const bhFed = (h) => h && Date.now() - (h.lastStock || 0) < 24 * 3600000;
  function renderHouses(list) {
    bHouses = Array(BIRD_SPOTS.length).fill(null);
    (list || []).forEach((h) => {
      if (h.spot >= 0 && h.spot < bHouses.length) bHouses[h.spot] = h;
    });
    BIRD_SPOTS.forEach(([sx, sy], i) => {
      const h = bHouses[i];
      let el = bhEls[i];
      if (!h) {
        if (el) { el.remove(); bhEls[i] = null; }   // reset era — bare post again
        return;
      }
      if (!el) {
        el = bhEls[i] = document.createElement('div');
        el.className = 'pk-bhouse';
        el.style.backgroundImage = "url('/assets/park/bh-house-" + (1 + (i % 4)) + ".png')";
        el.style.left = pct(sx, W);
        el.style.top = pct(sy, H);
        el.style.width = pct(BH_ART[0], W);
        el.style.height = pct(BH_ART[1], H);
        depth(el, sy);
        world.appendChild(el);
      }
    });
    // 🐦 the residents live in park-birds.js — it moves them in and out
    if (ctx.birds) ctx.birds.setStocked(BIRD_SPOTS.map((_, i) => bhFed(bHouses[i])));
  }
  function openPostSheet(i) {
    const bal = coinBal();
    gardenBody.innerHTML = '<h2>a bare post</h2>'
      + '<p class="pk-panel__sub">raise a birdhouse here — your name on it forever. '
      + 'any banana can stock it once a day, and a stocked house keeps 2-3 birds '
      + 'around and feeds the park’s health.</p>'
      + '<button class="pk-seedrow" type="button" id="pkBhBuild"'
      + (bal < BH_PRICE ? ' disabled' : '') + '>'
      + '<i>🐦</i><span class="pk-seedrow__txt"><b>raise a birdhouse</b>'
      + '<small>built once · stocked daily</small></span>'
      + coinChip(BH_PRICE) + '</button>'
      + (bal < BH_PRICE ? '<p class="pk-seedpoor">no coins — the rave floor drops them</p>' : '');
    const bb = document.getElementById('pkBhBuild');
    if (bb) bb.addEventListener('click', () => buildHouse(i));
    gardenPanel.hidden = false;
  }
  async function buildHouse(i) {
    if (coinBal() < BH_PRICE) return;
    passStat('coins_spent', BH_PRICE);
    refreshHud();
    closeGarden();
    const res = await gFetch('/bhbuild', { spot: i, name: ctx.parkName, pass: worldSid() });
    if (res && res.err === 'taken') {
      passStat('coins_spent', -BH_PRICE);   // refund — beaten to the post
      refreshHud();
      toast('somebody beat you to this post');
      applyGarden(res);
      return;
    }
    applyGarden(res);
    float(BIRD_SPOTS[i][0], BIRD_SPOTS[i][1] - 80, '🐦');
    toast('🐦 birdhouse raised — the birds moved straight in. stock it daily to keep them.', 4600);
    if (!bhBuildTracked) { bhBuildTracked = true; track('park_birdhouse', { act: 'build' }); }
  }
  async function stockHouse(i) {
    const h = bHouses[i];
    if (!h) return;
    closeGarden();
    const res = await gFetch('/bhstock', { spot: i, pass: worldSid() });
    if (res && res.err === 'stocked today') { toast('already stocked today — once a day per banana'); applyGarden(res); return; }
    if (res && res.err) { applyGarden(res); return; }
    applyGarden(res);
    float(BIRD_SPOTS[i][0], BIRD_SPOTS[i][1] - 80, '🌾');
    if (h.passShort !== myShort) { passStat('rep', 2); refreshHud(); }
    toast('🌾 stocked — the birds are staying another day');
    if (!bhStockTracked) { bhStockTracked = true; track('park_birdhouse', { act: 'stock' }); }
  }
  function openHouseCard(i) {
    const h = bHouses[i];
    if (!h) { openPostSheet(i); return; }
    const mine = h.passShort === myShort;
    const fed = bhFed(h);
    gardenBody.innerHTML = '<h2>🐦 ' + (mine ? 'your birdhouse'
      : esc(h.name || 'a mystery banana') + '’s birdhouse') + '</h2>'
      + '<p class="pk-panel__sub">' + (fed
        ? 'stocked — the birds are here, and the house is feeding the park’s health.'
        : 'quiet up there — nobody has stocked it in a day, so the birds moved out.')
      + '</p>'
      + '<p class="pk-gwater">🌾 stocked by ' + (h.stockers || 0) + ' banana' + (h.stockers === 1 ? '' : 's') + '</p>'
      + '<button class="pk-btn pk-gbtn" id="pkBhStock" type="button">🌾 stock it'
      + (mine ? '' : ' <small>+2 rep</small>') + '</button>';
    const sb = document.getElementById('pkBhStock');
    if (sb) sb.addEventListener('click', () => stockHouse(i));
    gardenPanel.hidden = false;
  }
  function postAct(i) { if (bHouses[i]) openHouseCard(i); else openPostSheet(i); }
  function tapPost(wx, wy) {
    // a built house's tap zone reaches up over the box; a bare post is small
    let best = -1, bd2 = 1e9;
    BIRD_SPOTS.forEach(([sx, sy], i) => {
      const hit = bHouses[i]
        ? (Math.abs(wx - sx) < 24 && wy > sy - 80 && wy < sy + 16) || Math.hypot(wx - sx, wy - sy) < 32
        : Math.hypot(wx - sx, wy - (sy - 14)) < 30;
      if (!hit) return;
      const d = Math.hypot(wx - sx, wy - (sy - (bHouses[i] ? 34 : 0)));
      if (d < bd2) { bd2 = d; best = i; }
    });
    if (best < 0) return false;
    const [sx, sy] = BIRD_SPOTS[best];
    if (Math.hypot(pos.x - sx, pos.y - sy) < 95) { postAct(best); return true; }
    pendingPost = best;                   // walk-then-act, like everything else
    tgt.x = sx;
    tgt.y = sy + 26;
    return true;
  }

  // ---- 🌿 WEEDS + 🌸 THE BLOOM — the shared entropy loop ------------------
  const weeds = new Map();                      // id → { el, x, y }
  let bloomV = -1, pendingWeed = null, weedTracked = false;
  // 🌸 THE HEALTH BAR — bottom-docked (the jellymeter's spot in the rave):
  // fill + % ride the live value, the face + whole palette ride the phase
  const bloomBtn = document.getElementById('pkHBar');
  const hFaceEl = document.getElementById('pkHFace');
  const hFillEl = document.getElementById('pkHFill');
  const hPctEl = document.getElementById('pkHPct');
  let hbarPhase = -1;
  // ⚠️ the fill takes the RAW value (the server sends one decimal) so a single
  // weed pulled visibly moves the bar; only the readout rounds
  function renderHBar(v, p) {
    hFillEl.style.width = v + '%';
    hPctEl.textContent = Math.round(v) + '%';
    hPctEl.style.left = v + '%';
    hPctEl.classList.toggle('is-out', v < 20);   // slim fill: % steps outside
    if (hbarPhase !== p) {
      hbarPhase = p;
      bloomBtn.className = 'pk-hbar pk-hbar--p' + p;
      hFaceEl.innerHTML = iconSvg(PHASE_FACES[p], { size: 20 });
    }
  }
  function refreshBloom(v) {
    if (PHASE_FORCE >= 0) v = PHASE_MID[PHASE_FORCE];   // pinned — polls no-op
    if (v === bloomV || typeof v !== 'number') return;
    bloomV = v;
    const p = ctx.phaseFor(v);             // ±3 hysteresis lives in phaseFor
    renderHBar(Math.max(0, v), p);
    ctx.setPhase(p);
    // 🐦 the wild roster gates on the RAW band (no hysteresis) so every client
    // in the park lands on the same species for the same 10-minute window
    if (ctx.birds) ctx.birds.setBloom(Math.max(0, v));
    const f = document.getElementById('pkBfill');
    if (f) {                               // the card is open — nudge it live
      f.style.clipPath = 'inset(0 ' + (100 - Math.max(0, v)) + '% 0 0)';
      gardenBody.querySelectorAll('.pk-bglyph').forEach((g, i) => g.classList.toggle('is-now', i === p));
      const num = document.getElementById('pkBnum');
      if (num) num.textContent = bloomStatus();
    }
  }
  // ---- 🗑 GARBAGE — litter on the lawn, walked over like acorns -----------
  // Server truth on the garden read (cap inverted by bloom: a hurting park
  // is littered). No tap, no tool: walking over it IS the pickup — poof,
  // +2 rep, and the server says thanks with +1 health (first touch wins).
  const trash = new Map();                      // id → { el, x, y }
  let trashTracked = false;
  function renderTrash(list) {
    const seen = new Set();
    (list || []).forEach((t) => {
      seen.add(t.id);
      if (trash.has(t.id)) return;
      const el = document.createElement('div');
      el.className = 'pk-trash pk-trash--' + (t.v === 2 ? 2 : t.v === 3 ? 3 : 1);
      el.style.left = pct(t.x, W);
      el.style.top = pct(t.y, H);
      depth(el, t.y);
      world.appendChild(el);
      trash.set(t.id, { el, x: t.x, y: t.y });
    });
    trash.forEach((t, id) => {
      if (!seen.has(id)) { t.el.remove(); trash.delete(id); }   // picked elsewhere
    });
  }
  function trashTick() {
    trash.forEach((t, id) => {
      if (Math.hypot(pos.x - t.x, (pos.y - 6) - t.y) > 32) return;
      trash.delete(id);                    // optimistic — the reply reconciles
      poofInto(world, 'pk-poof', t.x / W * 100, (t.y - 10) / H * 100);
      t.el.remove();
      passStat('rep', 2);
      refreshHud();
      float(t.x, t.y - 14, '+2');
      if (!trashTracked) { trashTracked = true; track('park_trash'); }
      gFetch('/trash', { id, pass: worldSid() }).then(applyGarden);
    });
    // 🍂 leaf piles ride the same walk-over beat (they only exist while the
    // park sits under 60 health — raking is recovery accelerant)
    leaves.forEach((l2, id) => {
      if (Math.hypot(pos.x - l2.x, (pos.y - 6) - l2.y) > 34) return;
      leaves.delete(id);
      poofInto(world, 'pk-poof', l2.x / W * 100, (l2.y - 10) / H * 100);
      l2.el.remove();
      passStat('rep', 1);
      refreshHud();
      float(l2.x, l2.y - 14, '🍂 +1');
      if (!rakeTracked) { rakeTracked = true; track('park_rake'); }
      gFetch('/rake', { id, pass: worldSid() }).then(applyGarden);
    });
  }
  // ---- 🍂 LEAF PILES — sad-phase texture, raked by walking over -----------
  const leaves = new Map();                     // id → { el, x, y }
  let rakeTracked = false;
  function renderLeaves(list) {
    const seen = new Set();
    (list || []).forEach((l2) => {
      seen.add(l2.id);
      if (leaves.has(l2.id)) return;
      const el = document.createElement('div');
      el.className = 'pk-leaf pk-leaf--' + (1 + (parseInt(l2.id, 36) || 0) % 2);
      el.style.left = pct(l2.x, W);
      el.style.top = pct(l2.y, H);
      depth(el, l2.y);
      world.appendChild(el);
      leaves.set(l2.id, { el, x: l2.x, y: l2.y });
    });
    leaves.forEach((l2, id) => {
      if (!seen.has(id)) { l2.el.remove(); leaves.delete(id); }   // raked elsewhere
    });
  }
  function renderWeeds(list) {
    const seen = new Set();
    (list || []).forEach((w2) => {
      seen.add(w2.id);
      if (weeds.has(w2.id)) return;
      const el = document.createElement('div');
      el.className = 'pk-weed pk-weed--' + (1 + (parseInt(w2.id, 36) || 0) % 2);
      el.style.left = pct(w2.x, W);
      el.style.top = pct(w2.y, H);
      depth(el, w2.y);
      world.appendChild(el);
      weeds.set(w2.id, { el, x: w2.x, y: w2.y });
    });
    weeds.forEach((w2, id) => {
      if (!seen.has(id)) { w2.el.remove(); weeds.delete(id); }   // pulled elsewhere
    });
  }
  async function pullWeed(id) {
    const w2 = weeds.get(id);
    if (!w2) return;
    weeds.delete(id);                       // optimistic — the poll reconciles
    w2.el.classList.add('is-pulled');
    setTimeout(() => {
      poofInto(world, 'pk-poof', w2.x / W * 100, (w2.y - 14) / H * 100);
      w2.el.remove();
    }, 240);
    passStat('rep', 1);
    passStat('weeds_pulled', 1);            // the park-day card's ledger
    // 🪙 ~8%: something under the roots — the chore is a tiny lottery
    // (client-side roll, same as the world's other coin juice)
    if (Math.random() < 0.08) {
      const n = 1 + Math.floor(Math.random() * 3);
      passStat('coins_earned', n);
      float(w2.x + 18, w2.y - 34, '+' + n + ' 🪙');
      toast('🪙 something under the roots — +' + n, 2600);
    }
    refreshHud();
    float(w2.x, w2.y - 20, '+1');
    if (!weedTracked) { weedTracked = true; track('park_weed'); }
    applyGarden(await gFetch('/weed', { id, pass: worldSid() }));
  }
  function tapWeed(wx, wy) {
    let hit = null;
    weeds.forEach((w2, id) => {
      if (Math.hypot(wx - w2.x, wy - (w2.y - 10)) < 30) hit = { id, w2 };
    });
    if (!hit) return false;
    if (Math.hypot(pos.x - hit.w2.x, pos.y - hit.w2.y) < 90) { pullWeed(hit.id); return true; }
    pendingWeed = hit.id;                   // walk-then-pull
    tgt.x = hit.w2.x;
    tgt.y = hit.w2.y + 26;
    return true;
  }
  // ---- 🥚 EGGS — laid on the hens' lawn, FIRST TAP WINS -------------------
  // The rave-drop pattern: the server's removal is the verdict, so the egg
  // stays put until the reply lands — no optimistic grab on a shared prize.
  const eggs = new Map();                       // id → { el, x, y, g }
  let pendingEgg = null, eggBusy = false, eggTracked = false;
  function renderEggs(list) {
    const seen = new Set();
    (list || []).forEach((e) => {
      seen.add(e.id);
      if (eggs.has(e.id)) return;
      const el = document.createElement('div');
      el.className = 'pk-egg' + (e.g ? ' pk-egg--gold' : '');
      el.style.left = pct(e.x, W);
      el.style.top = pct(e.y, H);
      depth(el, e.y);
      world.appendChild(el);
      eggs.set(e.id, { el, x: e.x, y: e.y, g: e.g ? 1 : 0 });
    });
    eggs.forEach((e, id) => {
      if (!seen.has(id)) {
        e.el.remove();
        eggs.delete(id);
        if (pendingEgg === id) pendingEgg = null;   // snapped up mid-walk
      }
    });
  }
  async function claimEgg(id) {
    const e = eggs.get(id);
    if (!e || eggBusy) return;
    eggBusy = true;
    const res = await gFetch('/egg', { id, pass: worldSid() });
    eggBusy = false;
    if (!res) return;
    applyGarden(res);
    if (res.err) { toast('🥚 someone got it first'); return; }
    passStat('eggs_found', 1);              // the park-day card's ledger
    const r = res.reward || {};
    if (r.coins) passStat('coins_earned', r.coins);
    if (r.tickets) passStat('tickets', r.tickets);   // the bay's pier currency
    refreshHud();
    float(e.x, e.y - 14, r.golden ? '✨' : '+' + (r.coins || r.tickets));
    if (r.golden) {
      confettiAt(e.x, e.y);
      toast('🥚✨ THE GOLDEN EGG — +' + r.coins + ' coins, +' + r.tickets + ' beach tickets!', 4600);
    } else if (r.tickets) {
      toast('🥚 ' + r.tickets + ' beach tickets in an egg?! the pier takes those', 4200);
    } else {
      toast('🥚 +' + r.coins + ' coins — fresh from the hens');
    }
    if (!eggTracked) { eggTracked = true; track('park_egg', { golden: r.golden ? 1 : 0 }); }
  }
  function tapEgg(wx, wy) {
    let hit = null;
    eggs.forEach((e, id) => {
      if (Math.hypot(wx - e.x, wy - (e.y - 9)) < 26) hit = id;
    });
    if (hit == null) return false;
    const e = eggs.get(hit);
    if (Math.hypot(pos.x - e.x, pos.y - e.y) < 90) { claimEgg(hit); return true; }
    pendingEgg = hit;                     // walk-then-claim, like everything else
    tgt.x = e.x;
    tgt.y = e.y + 22;
    return true;
  }
  // the card is mostly BAR: five phase segments, each its own fill slice,
  // the live phase ringed; tapping a segment reveals that phase's lines
  function bloomStatus() {
    const n = weeds.size;
    const v = Math.max(0, bloomV);
    const stars = gSlots.reduce((t, s) => t + ((SEED_BY[s && s.seed] || {}).stars || 0), 0);
    return Math.round(v) + '%'
      + (n ? ' · ' + n + ' weed' + (n === 1 ? '' : 's') + ' out there' : '')
      + (stars ? ' · ' + starStr(Math.min(stars, 5)) + (stars > 5 ? '×' + stars : '') + ' feeding it' : '');
  }
  // ONE continuous bar (Trym: progress first, chapters second): a single
  // fill sliding over the faint ramp, ticks at the phase borders, glyphs
  // over their zones, invisible per-phase tap zones for the line reveals.
  // The fill + status track LIVE while the card is open (refreshBloom).
  bloomBtn.addEventListener('click', () => {
    const v = Math.max(0, bloomV);
    gardenBody.innerHTML = '<h2>🌸 park health</h2>'
      + '<div class="pk-bbar">'
      + '<div class="pk-bglyphs">' + PHASE_GLYPHS.map((g, i) =>
        '<span class="pk-bglyph' + (i === ctx.phase() ? ' is-now' : '') + '">' + g + '</span>').join('') + '</div>'
      + '<div class="pk-btrack"><i class="pk-bramp"></i>'
      + '<i class="pk-bfill" id="pkBfill" style="clip-path:inset(0 ' + (100 - v) + '% 0 0)"></i>'
      + PHASE_STARTS.slice(1).map((t) => '<i class="pk-btick" style="left:' + t + '%"></i>').join('') + '</div>'
      + PHASE_GLYPHS.map((g, i) =>
        '<button class="pk-bzone" type="button" data-p="' + i + '" style="left:' + (i * 20) + '%"'
        + ' aria-label="park health phase ' + (i + 1) + ' of 5"></button>').join('')
      + '</div>'
      + '<p class="pk-bloomnum" id="pkBnum">' + bloomStatus() + '</p>'
      + '<p id="pkBexp"></p>';
    const exp = document.getElementById('pkBexp');
    const show = (i) => {
      exp.className = 'pk-bexp' + (i <= 1 ? ' pk-bexp--sad' : '');
      exp.textContent = PHASE_LINES[i];
      gardenBody.querySelectorAll('.pk-bglyph').forEach((g, gi) => g.classList.toggle('is-open', gi === i));
    };
    gardenBody.querySelectorAll('.pk-bzone').forEach((b) => {
      b.addEventListener('click', () => show(+b.dataset.p));
    });
    show(Math.max(0, ctx.phase()));
    gardenPanel.hidden = false;
  });
  function applyGarden(res) {
    if (!res) return;
    if (Array.isArray(res.slots)) { gSlots = res.slots; renderGarden(); }
    if (Array.isArray(res.weeds)) renderWeeds(res.weeds);
    if (Array.isArray(res.trash)) renderTrash(res.trash);
    if (Array.isArray(res.eggs)) renderEggs(res.eggs);
    if (Array.isArray(res.border)) renderBorder(res.border);
    if (Array.isArray(res.algae)) renderAlgae(res.algae);
    if (Array.isArray(res.leaves)) renderLeaves(res.leaves);
    if (Array.isArray(res.houses)) renderHouses(res.houses);
    if (typeof res.bloom === 'number') refreshBloom(res.bloom);
  }
  async function gardenPoll() {
    applyGarden(await gFetch(''));
    if (ctx.phase() < 0) {        // no word from the server — the park at its
      if (PHASE_FORCE >= 0) refreshBloom(PHASE_MID[PHASE_FORCE]);
      else { ctx.setPhase(4); if (ctx.birds) ctx.birds.setBloom(90); }   // best

    }
  }
  gardenPoll();
  setInterval(() => { if (!document.hidden) gardenPoll(); }, 60000);
  function closeGarden() { gardenPanel.hidden = true; gardenOpenSlot = -1; }
  document.getElementById('pkGardenClose').addEventListener('click', closeGarden);
  gardenPanel.addEventListener('click', (e) => { if (e.target === gardenPanel) closeGarden(); });
  addEventListener('keydown', (e) => { if (e.key === 'Escape' && !gardenPanel.hidden) closeGarden(); });
  function coinChip(n) {
    return '<span class="pk-seedcost"><img src="/assets/banana-stand/coin.png" width="14" height="14" alt="coins" /> ' + n + '</span>';
  }
  function openSeedSheet(i) {
    gardenOpenSlot = i;
    const bal = coinBal();
    const gl = gardenerLvl();
    const blessed = hasVoucher();   // ⛲ a fountain voucher: one small seed free
    // locked seeds stay VISIBLE (aspiration) — greyed, with the level they need
    const lvlFor2 = (sd) => 1 + GLVL_STARS.findIndex((mx) => sd.stars <= mx);
    gardenBody.innerHTML = '<h2>an empty patch</h2>'
      + '<p class="pk-glvl">🧑‍🌾 gardener lvl ' + gl.lvl + ' · ' + gl.n + ' harvest' + (gl.n === 1 ? '' : 's') + '</p>'
      + '<p class="pk-panel__sub">plant a seed — it grows on real days, even while you’re gone. '
      + 'water it or it wilts away (higher ⭐ holds out longer). ⭐ feed the park’s health while it lives.</p>'
      + SEEDS.map((sd) => {
        const locked = sd.stars > gl.stars;
        const free = blessed && !locked && sd.price <= VOUCHER_MAX;
        return '<button class="pk-seedrow' + (locked ? ' pk-seedrow--lock' : '') + '" type="button"'
          + ' data-seed="' + sd.id + '"' + (locked || (!free && bal < sd.price) ? ' disabled' : '') + '>'
          + '<i>' + sd.emoji + '</i>'
          + '<span class="pk-seedrow__txt"><b>' + sd.name + (sd.rare ? ' <em>rare</em>' : '') + '</b>'
          + '<small>' + starStr(sd.stars) + ' · ' + sd.days + ' days → '
          + (locked ? '🔒 gardener lvl ' + lvlFor2(sd)
            : sd.wearable ? 'the ' + sd.wearLabel : '+' + (sd.stars * 8) + ' rep') + '</small></span>'
          + (free ? '<span class="pk-seedcost pk-seedcost--free">🎁 blessed — free</span>' : coinChip(sd.price))
          + '</button>';
      }).join('')
      + (bal < SEEDS[0].price && !blessed ? '<p class="pk-seedpoor">no coins — the rave floor drops them</p>' : '');
    gardenBody.querySelectorAll('.pk-seedrow').forEach((b) => {
      b.addEventListener('click', () => plantSeed(i, b.dataset.seed));
    });
    gardenPanel.hidden = false;
  }
  async function plantSeed(i, seedId) {
    const sd = SEED_BY[seedId];
    if (!sd || sd.stars > gardenerLvl().stars) return;
    // ⛲ the fountain's voucher pays for small seeds; it spends HERE, on the
    // plant itself — and comes back if somebody beat you to the patch
    const free = hasVoucher() && sd.price <= VOUCHER_MAX;
    if (!free && coinBal() < sd.price) return;
    if (free) setVoucher(false);
    else {
      passStat('coins_spent', sd.price);
      refreshHud();
    }
    closeGarden();
    const res = await gFetch('/plant', { slot: i, seed: seedId, name: ctx.parkName, pass: worldSid() });
    if (res && res.err === 'taken') {
      if (free) setVoucher(true);           // the blessing survives the miss
      else {
        passStat('coins_spent', -sd.price); // refund — somebody beat you to it
        refreshHud();
      }
      toast('somebody beat you to this patch');
      applyGarden(res);
      return;
    }
    applyGarden(res);
    float(PLOTS[i][0], PLOTS[i][1] - 6, '🌱');
    toast(sd.emoji + ' ' + sd.name + ' planted — day 1 of ' + sd.days);
    if (!plantTracked) { plantTracked = true; track('park_plant', { seed: seedId }); }
  }
  function openPlantCard(i) {
    const s = gSlots[i];
    if (!s) { openSeedSheet(i); return; }
    gardenOpenSlot = i;
    const sd = SEED_BY[s.seed] || SEEDS[0];
    const mine = gMine(s), ready = gReady(s);
    // a stranger's plant is an OWNERSHIP popup: their name leads, big
    gardenBody.innerHTML = (mine
      ? '<h2>' + sd.emoji + ' your ' + sd.name + '</h2>'
      : '<h2>' + esc(s.name || 'a mystery banana') + '</h2>'
        + '<p class="pk-gplant">' + sd.emoji + ' their ' + sd.name + '</p>')
      + '<p class="pk-gplant">' + starStr(sd.stars) + '</p>'
      + '<p class="pk-panel__sub">' + (ready
        ? (mine ? 'full-grown — tap it to harvest!' : 'ready to pick — only its grower can harvest it.')
        : 'day ' + Math.min(gDays(s) + 1, sd.days) + ' of ' + sd.days + ' · growing on real days')
      + '</p>'
      + '<p class="pk-gwater">💧 watered by ' + (s.waterers || 0) + ' visitor' + (s.waterers === 1 ? '' : 's') + '</p>'
      + (ready ? '' : '<button class="pk-btn pk-gbtn" id="pkWaterBtn" type="button">💧 water it'
        + (mine ? '' : ' <small>+2 rep</small>') + '</button>')
      + (mine ? '<p class="pk-gsaved">' + (sd.wearable
        ? '💾 saved to your pass' : '🌾 harvest pays +' + (sd.stars * 8) + ' rep') + '</p>' : '');
    const wb = document.getElementById('pkWaterBtn');
    if (wb) wb.addEventListener('click', () => waterSlot(i));
    gardenPanel.hidden = false;
  }
  async function waterSlot(i) {
    const s = gSlots[i];
    if (!s) return;
    closeGarden();
    s.lastWater = Date.now();   // the soil darkens right away; the reply reconciles
    renderGarden();
    const res = await gFetch('/water', { slot: i, pass: worldSid() });
    if (res && res.err === 'watered today') { toast('already watered today — once a day per banana'); applyGarden(res); return; }
    if (res && res.err) { applyGarden(res); return; }
    applyGarden(res);
    float(PLOTS[i][0], PLOTS[i][1] - 8, '💧');
    if (!gMine(gSlots[i] || s)) { passStat('rep', 2); refreshHud(); }
    if (!waterTracked) { waterTracked = true; track('park_water'); }
  }
  function confettiAt(x, y) {
    for (let n = 0; n < 14; n++) {
      const c = document.createElement('i');
      c.className = 'pk-confetti';
      c.style.left = pct(x + (Math.random() * 60 - 30), W);
      c.style.top = pct(y - 10 - Math.random() * 30, H);
      c.style.background = ['#ffe135', '#8de08d', '#7db9ff', '#ff9d3a', '#b48ae0'][n % 5];
      c.style.animationDelay = (Math.random() * 0.2).toFixed(2) + 's';
      world.appendChild(c);
      setTimeout(() => c.remove(), 1400);
    }
  }
  async function doHarvest(i) {
    const s = gSlots[i];
    if (!s || !gMine(s) || !gReady(s)) return;
    const sd = SEED_BY[s.seed] || SEEDS[0];
    const res = await gFetch('/harvest', { slot: i, pass: worldSid() });
    if (res && res.err) { applyGarden(res); toast(res.err === 'still growing' ? 'not quite ready yet' : 'the patch is bare'); return; }
    applyGarden(res);
    const before = gardenerLvl().lvl;
    passStat('garden_harvests', 1);      // the gardener level's ledger
    confettiAt(PLOTS[i][0], PLOTS[i][1]);
    if (!sd.wearable) {                  // no wearable → rep by stars, never coins
      passStat('rep', sd.stars * 8);
      refreshHud();
      float(PLOTS[i][0], PLOTS[i][1] - 20, '+' + (sd.stars * 8));
      toast(sd.emoji + ' ' + sd.name + ' harvested — +' + (sd.stars * 8) + ' rep!', 4200);
    } else {
      passStat('own_' + sd.wearable, 1); // the wearable's earned-gate proof
      toast(sd.emoji + ' ' + sd.wearLabel + ' harvested — saved to your pass!', 4200);
    }
    const gl = gardenerLvl();
    if (gl.lvl > before) setTimeout(() => toast('🧑‍🌾 gardener lvl ' + gl.lvl + ' — new seeds in the sheet!', 4600), 1500);
    if (!harvestTracked) { harvestTracked = true; track('park_harvest', { seed: s.seed, level: gl.lvl }); }
  }
  function gardenAct(i) {
    const s = gSlots[i];
    if (!s) { openSeedSheet(i); return; }
    if (gReady(s) && gMine(s)) { doHarvest(i); return; }
    openPlantCard(i);
  }
  function tapGarden(wx, wy) {
    // an occupied slot's tap zone reaches UP over its plant; among
    // overlapping hits the nearest visual middle wins (rows sit 38px apart)
    let best = -1, bd = 1e9;
    PLOTS.forEach(([sx, sy], i) => {
      const hit = gSlots[i]
        ? (Math.abs(wx - sx) < 24 && wy > sy - 76 && wy < sy + 18) || Math.hypot(wx - sx, wy - sy) < 34
        : Math.hypot(wx - sx, wy - sy) < 34;
      if (!hit) return;
      const d2 = Math.hypot(wx - sx, wy - (sy - (gSlots[i] ? 24 : 0)));
      if (d2 < bd) { bd = d2; best = i; }
    });
    if (best < 0) return false;
    const [sx, sy] = PLOTS[best];
    if (Math.hypot(pos.x - sx, pos.y - sy) < 95) { gardenAct(best); return true; }
    pendingGarden = best;                 // walk-then-act, like everything else
    tgt.x = sx;
    // just south of the bed's collider: rows alternate top (even i, gb-62)
    // and bottom (odd i, gb-24), so both land on gb+16 — works at EVERY site
    // (the old fixed 882 was sites A/B's line and never reached site C)
    tgt.y = sy + (best % 2 ? 40 : 78);
    return true;
  }
  function gardenTick() {
    if (pendingGarden != null) {
      const [sx, sy] = PLOTS[pendingGarden];
      if (Math.hypot(pos.x - sx, pos.y - sy) < 95) { const i = pendingGarden; pendingGarden = null; gardenAct(i); }
    }
    if (pendingWater != null) {   // the tool slot's walk-then-water
      const [sx, sy] = PLOTS[pendingWater];
      if (Math.hypot(pos.x - sx, pos.y - sy) < 95) { const i = pendingWater; pendingWater = null; waterSlot(i); }
    }
    if (pendingWeed != null) {
      const w2 = weeds.get(pendingWeed);
      if (!w2) pendingWeed = null;          // pulled by somebody else mid-walk
      else if (Math.hypot(pos.x - w2.x, pos.y - w2.y) < 90) { const id = pendingWeed; pendingWeed = null; pullWeed(id); }
    }
    if (pendingEgg != null) {
      const e = eggs.get(pendingEgg);
      if (!e) pendingEgg = null;            // claimed by somebody else mid-walk
      else if (Math.hypot(pos.x - e.x, pos.y - e.y) < 90) { const id = pendingEgg; pendingEgg = null; claimEgg(id); }
    }
    if (pendingBorder != null) {
      const [sx, sy] = BORDER_SPOTS[pendingBorder];
      if (Math.hypot(pos.x - sx, pos.y - sy) < 90) { const i = pendingBorder; pendingBorder = null; borderAct(i); }
    }
    if (pendingAlgae != null) {
      const a2 = algae.get(pendingAlgae);
      if (!a2) pendingAlgae = null;         // skimmed by somebody else mid-walk
      else if (Math.hypot(pos.x - a2.bx, pos.y - a2.by) < ALGAE_REACH) { const id = pendingAlgae; pendingAlgae = null; skimAlgae(id); }
    }
    if (pendingPost != null) {
      const [sx, sy] = BIRD_SPOTS[pendingPost];
      if (Math.hypot(pos.x - sx, pos.y - sy) < 95) { const i = pendingPost; pendingPost = null; postAct(i); }
    }
  }

  // ---- 🧰 THE TOOL SLOT — the one contextual chore button ----------------
  // Scans every frame (≤10 weeds + 24 slots — cheap); DOM writes are
  // change-guarded on the chore key. DRY plant = not watered today (anyone's);
  // a ready plant is a harvest, not a chore. Press = act on the nearest,
  // walking the last step first — the same pull/water paths as a direct tap.
  const toolBtn = document.getElementById('pkTool');
  let toolChore = null, toolKey = '';
  function toolScan() {
    let best = null, bd = TOOL_RANGE;
    weeds.forEach((w2, id) => {
      const d = Math.hypot(pos.x - w2.x, pos.y - w2.y);
      if (d < bd) { bd = d; best = { kind: 'weed', id, x: w2.x, y: w2.y }; }
    });
    PLOTS.forEach(([sx, sy], i) => {
      const s = gSlots[i];
      if (!s || gWet(s) || gReady(s)) return;
      const d = Math.hypot(pos.x - sx, pos.y - sy);
      if (d < bd) { bd = d; best = { kind: 'water', i, x: sx, y: sy }; }
    });
    // 🫧 a scum patch counts as in-range by its BANK point (you skim from
    // the shore — a mid-pond patch would otherwise never light the tool)
    algae.forEach((a2, id) => {
      const d = Math.hypot(pos.x - a2.bx, pos.y - a2.by);
      if (d < bd) { bd = d; best = { kind: 'algae', id, x: a2.bx, y: a2.by }; }
    });
    return best;
  }
  function toolTick() {
    const c = toolScan();
    toolChore = c;
    const key = c ? c.kind + ':' + (c.kind === 'water' ? c.i : c.id) : '';
    if (key === toolKey) return;
    toolKey = key;
    if (!c) { toolBtn.hidden = true; return; }
    toolBtn.textContent = c.kind === 'weed' ? '🌿 pull' : c.kind === 'algae' ? '🫧 skim' : '💧 water';
    toolBtn.hidden = false;
  }
  toolBtn.addEventListener('click', () => {
    const c = toolChore;
    if (!c) return;
    if (c.kind === 'weed') {
      if (Math.hypot(pos.x - c.x, pos.y - c.y) < 90) { pullWeed(c.id); return; }
      pendingWeed = c.id;
      tgt.x = c.x; tgt.y = c.y + 26;
      return;
    }
    if (c.kind === 'algae') {   // c.x/c.y = the bank point
      if (Math.hypot(pos.x - c.x, pos.y - c.y) < ALGAE_REACH) { skimAlgae(c.id); return; }
      pendingAlgae = c.id;
      tgt.x = c.x; tgt.y = c.y;
      return;
    }
    if (Math.hypot(pos.x - c.x, pos.y - c.y) < 95) { waterSlot(c.i); return; }
    pendingWater = c.i;
    tgt.x = c.x;
    tgt.y = c.y + (c.i % 2 ? 40 : 78);   // the bed's own south edge (see tapGarden)
  });

  return {
    trashTick, gardenTick, toolTick,
    tapEgg, tapWeed, tapGarden, tapBorder, tapAlgae, tapPost,
    closeGarden,
    gardenerLvl,
    bloomNow: () => bloomV,
    clearPending: () => { pendingGarden = null; pendingWater = null; pendingWeed = null; pendingEgg = null; pendingBorder = null; pendingAlgae = null; pendingPost = null; },
    qa: {
      eggs,
      // 🥚 egg QA: lay one at your feet (egg(1) = golden); steal() = somebody
      // else claims the oldest — tap it after for the 'someone got it' path
      egg: (g) => {
        gShim.eggs.push({ id: 'qa' + Math.random().toString(36).slice(2, 6),
          x: Math.round(pos.x) + 60, y: Math.round(pos.y), ...(g ? { g: 1 } : {}) });
        gardenPoll();
      },
      steal: () => { gShim.eggs.shift(); gardenPoll(); },
      // 🗑 litter QA: drop a piece just ahead — walk over it to test pickup
      litter: (v) => {
        gShim.trash.push({ id: 'qt' + Math.random().toString(36).slice(2, 6),
          x: Math.round(pos.x) + 80, y: Math.round(pos.y), v: v || 1 + Math.floor(Math.random() * 3) });
        gardenPoll();
      },
      // 🧰 chore QA: lay a weed at your feet; dry(i) = slot i missed today
      weed: () => {
        gShim.weeds.push({ id: 'qw' + Math.random().toString(36).slice(2, 6),
          x: Math.round(pos.x) - 70, y: Math.round(pos.y) });
        gardenPoll();
      },
      dry: (i) => { const s = gShim.slots[i]; if (s) s.lastWater -= 86460000; gardenPoll(); },
      // 🫧 algae QA: scatter n patches on free lattice spots; 🍂 a pile just
      // ahead; 🐦 age a house's stocking h hours back (birds-gone at 24)
      algae: (n) => {
        const taken = new Set(gShim.algae.map((a2) => a2.x + ',' + a2.y));
        for (let k = 0; k < (n || 3); k++) {
          const sp = ALGAE_SPOTS[Math.floor(Math.random() * ALGAE_SPOTS.length)];
          if (taken.has(sp[0] + ',' + sp[1])) continue;
          taken.add(sp[0] + ',' + sp[1]);
          gShim.algae.push({ id: 'qg' + Math.random().toString(36).slice(2, 6), x: sp[0], y: sp[1] });
        }
        gardenPoll();
      },
      leaf: () => {
        gShim.leaves.push({ id: 'ql' + Math.random().toString(36).slice(2, 6),
          x: Math.round(pos.x) + 84, y: Math.round(pos.y) });
        gardenPoll();
      },
      stockAge: (spot, h) => {
        const h2 = gShim.houses.find((x2) => x2.spot === spot);
        if (h2) { h2.lastStock -= (h || 25) * 3600000; h2.sday = {}; }
        gardenPoll();
      },
      // 🧑‍🌾 gardener QA: set the harvest count / jump straight to a level
      harvests: (n) => { passStat('garden_harvests', n - ((passGet().stats || {}).garden_harvests || 0)); return gardenerLvl(); },
      lvl: (n) => { passStat('garden_harvests', GLVL_AT[Math.max(1, Math.min(GLVL_AT.length, n)) - 1] - ((passGet().stats || {}).garden_harvests || 0)); return gardenerLvl(); },
      // 🌱 garden QA: read state, fast-forward growth d days (shim store =
      // this session's local stand-in server; render follows on next poll)
      garden: () => gSlots,
      gShim,
      ff: (i, d2) => { const s = gShim.slots[i]; if (s) s.plantedAt -= d2 * 86400000; gardenPoll(); },
      // 🌸 phase QA: force the shim's bloom, read the resolved phase
      bloom: (v) => { gShim.bloom = v; gardenPoll(); },
    },
  };
}
