# -*- coding: utf-8 -*-
"""THE FAMILY FILTER generator — builds src/lib/family-filter.js (client) and
prints the worker-share drop-in arrays (server sync-copy) from the vendored
wordlists in tools/family-lists/.

Lists: LDNOOBW (List of Dirty, Naughty, Obscene and Otherwise Bad Words),
https://github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words
(CC BY 4.0 — attribution kept in the generated file). en + no; drop more
language files into tools/family-lists/ and rerun to widen coverage.

Matching design (the part a giant list gets WRONG if done naively):
- WORD-BOUNDARY tokens for everything (so Scunthorpe-class false positives
  like "chore"/"class"/"kukkelure" pass — the old 20-word substring list
  actually blocked "chore" via "hore").
- A tiny hand-kept STEM list matched as substrings on the separator-collapsed
  string (slur stems + the old list's strictness kept — no regression).
- Multi-word phrases collapse ("blow job" -> "blowjob") and match as
  substrings of the collapsed string (separators can't dodge them).
- Normalization before any check: lowercase, strip diacritics, leetspeak map
  (0->o 1->i 3->e 4->a 5->s 7->t 8->b @->a $->s !->i), plus a variant with
  3+ character runs collapsed (fuuuck -> fuck) — both variants are checked.

RUN: python tools/build-family-filter.py   (rewrites src/lib/family-filter.js,
     prints the worker arrays to paste into worker-share's dirty()).
"""
import os
import re
import unicodedata

def norm(w):
    """The SAME normalization the JS applies to input: NFD, drop combining
    marks (å->a, é->e; æ/ø don't decompose and survive), lowercase."""
    return ''.join(c for c in unicodedata.normalize('NFD', w.lower())
                   if unicodedata.category(c) != 'Mn')

HERE = os.path.dirname(os.path.abspath(__file__))
SITE = os.path.dirname(HERE)
LISTS = os.path.join(HERE, 'family-lists')
OUT = os.path.join(SITE, 'src', 'lib', 'family-filter.js')

# slur/hate stems — substring-matched on the collapsed string. KEEP TINY and
# unambiguous-ish; everything else belongs in the boundary list. Includes the
# pre-2026-07 BLOCKLIST's substring behaviour so strictness never regresses.
# core profanities ride as stems too — compounds ("sh*thead", "f*ckface")
# dodge boundary matching otherwise. NOT stem-safe, kept boundary-only:
# 'cum' (cucumber!), 'dick' (Dickens), 'cock' (peacock), 'slut' (NO "slutt").
STEMS = ['nigg', 'fagg', 'cunt', 'whore', 'hitler', 'jævl', 'jævel',
         'fuck', 'shit', 'bitch', 'porn']

# list entries that are innocent in OUR context (English collisions with the
# Norwegian list, letter-pairs): "biggest banana FAN", "hugs XX"…
ALLOW = {'fan', 'xx', 'sm', 'gc'}

def load_words():
    words = set()
    phrases = set()
    for f in sorted(os.listdir(LISTS)):
        if not f.endswith('.txt'):
            continue
        for line in open(os.path.join(LISTS, f), encoding='utf-8'):
            w = norm(line.strip())
            if not w or w.startswith('#'):
                continue
            if ' ' in w or '-' in w:
                phrases.add(re.sub(r'[^a-zæø]', '', w))
            else:
                words.add(re.sub(r'[^a-zæø]', '', w) or w)
    # legacy list entries that were words (keep coverage)
    for w in ['retard', 'rape', 'nazi', 'faen', 'fitte', 'kuk', 'pikk', 'hore', 'kneppe', 'porn', 'slut', 'bitch', 'shit', 'fuck']:
        words.add(w)
    words.discard('')
    # stems already cover these as substrings — no need to double-list
    words = {w for w in words if not any(s in w for s in STEMS)} - ALLOW
    phrases = {p for p in phrases if p and not any(s in p for s in STEMS)}
    return sorted(words), sorted(phrases)

def js_array(items):
    return "'" + "|".join(items).replace("\\", "\\\\").replace("'", "\\'") + "'"

def main():
    words, phrases = load_words()
    print(f'{len(words)} boundary words, {len(phrases)} collapsed phrases, {len(STEMS)} stems')
    module = f"""// THE FAMILY FILTER — one shared gate for every user-typed string that can
// end up on our letterhead: captions, pass names, gallery bylines.
// GENERATED by tools/build-family-filter.py — edit the lists/tool, not this.
// Wordlists: LDNOOBW (CC BY 4.0),
// github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words
// Matching: word-boundary tokens (no Scunthorpe false positives), slur STEMS
// as substrings, multi-word phrases on the separator-collapsed string, all
// after leetspeak/diacritic normalization + a repeat-collapsed variant.
const WORDS = new Set({js_array(words)}.split('|'));
const PHRASES = {js_array(phrases)}.split('|');
const STEMS = {js_array(STEMS)}.split('|');

const LEET = {{ '0': 'o', '1': 'i', '3': 'e', '4': 'a', '5': 's', '7': 't', '8': 'b', '@': 'a', '$': 's', '!': 'i' }};

// same normalization the generator applied to the stored words: lowercase,
// NFD + strip combining marks (å->a, é->e; æ/ø survive), leetspeak map
function normalize(str) {{
  let s = String(str || '').toLowerCase();
  try {{ s = s.normalize('NFD').replace(/[\\u0300-\\u036f]/g, ''); }} catch (e) {{}}
  return s.replace(/[0134578@$!]/g, (c) => LEET[c] || c);
}}

function variants(str) {{
  const base = normalize(str);
  const squeezed = base.replace(/(.)\\1{{2,}}/g, '$1'); // fuuuck -> fuck ('ss' survives)
  return base === squeezed ? [base] : [base, squeezed];
}}

// true = clean. The one gate — import THIS for any new user-text surface.
export function textClean(str) {{
  for (const v of variants(str)) {{
    const collapsed = v.replace(/[^a-z\\u00e6\\u00f8]/g, '');
    if (STEMS.some((s) => collapsed.includes(s))) return false;
    if (PHRASES.some((p) => collapsed.includes(p))) return false;
    const toks = v.split(/[^a-z\\u00e6\\u00f8]+/).filter(Boolean);
    for (const tok of toks) {{
      if (WORDS.has(tok)) return false;
    }}
    // spaced-out dodges ("f.u.c.k"): join runs of single-letter tokens and
    // judge the run as one word — leaves normal prose untouched
    let run = '';
    for (let i = 0; i <= toks.length; i++) {{
      const t = toks[i];
      if (t && t.length === 1) {{ run += t; continue; }}
      if (run.length >= 3 && (WORDS.has(run) || STEMS.some((s) => run.includes(s)))) return false;
      run = '';
    }}
  }}
  return true;
}}
"""
    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write(module)
    print('wrote', OUT)

    # auto-patch every worker's marker block (the sync-copies can never drift)
    block = ('// FAMILY-FILTER-START\n'
             f"const F_WORDS = new Set({js_array(words)}.split('|'));\n"
             f"const F_PHRASES = {js_array(phrases)}.split('|');\n"
             f"const F_STEMS = {js_array(STEMS)}.split('|');\n"
             '// FAMILY-FILTER-END')
    for worker in ['worker-share', 'worker-rave']:
        wpath = os.path.join(SITE, worker, 'src', 'index.js')
        if not os.path.exists(wpath):
            continue
        wsrc = open(wpath, encoding='utf-8').read()
        patched = re.sub(r'// FAMILY-FILTER-START\n.*?// FAMILY-FILTER-END', block, wsrc, flags=re.S)
        if patched == wsrc and block not in wsrc:
            print(f'⚠ {worker} markers not found — NOT patched')
        else:
            open(wpath, 'w', encoding='utf-8', newline='\n').write(patched)
            print('patched', wpath)

if __name__ == '__main__':
    main()
