# 🪩 THE RAVE'S OWN SPRITES — packed the way the wearables are (26 Sep 2026).
#
# The rave drew its conveyor items, its drinks, its fish and its jellies as inline SVG strings in
# src/scripts/banana-rave.js: a grid of <rect> elements, one per PIXEL this time, every x/y/width/height/fill
# spelled out. 40 of them came to about 90 KB of the rave's own script. The budget note of 24 Sep 2026 had
# named this as the next trim ("the rave's 36 rect-grid sprites pack byte-identically through wear-unpack"),
# and the social layer (src/lib/world-social.js) is what finally needed the room.
#
# It is tools/build-wearart.py with a one-pixel cell, and the same promise: the decoder reproduces every
# source string BYTE FOR BYTE, this tool refuses to write anything that does not, and tools/check-wearart.mjs
# proves it again on every build with the shipped decoder (src/lib/wear-unpack.js, unpackArt(p, 1)).
#
#   tools/raveart-source.js   the readable SVGs. NOT under src/, never bundled: edit a sprite here.
#   src/data/raveart.js       GENERATED, packed, and the only one that ships.
#
# A sprite whose rects are not row-major horizontal runs (the mitt's are vertical) does not pack; it stays
# inline in banana-rave.js, where it always was.
#
# Run: python tools/build-raveart.py
import importlib.util
import io
import os

SITE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(SITE, 'tools', 'raveart-source.js')
OUT = os.path.join(SITE, 'src', 'data', 'raveart.js')

spec = importlib.util.spec_from_file_location('wearart', os.path.join(SITE, 'tools', 'build-wearart.py'))
wa = importlib.util.module_from_spec(spec)
spec.loader.exec_module(wa)
CELL = 1


def main():
    src = io.open(SRC, encoding='utf-8').read()
    items = []
    for line in src.split('\n'):
        m = wa.ENT.match(line)
        if m:
            items.append((m.group(1), m.group(2)))
    assert items, 'no art found in ' + SRC
    packed = {}
    for k, v in items:
        p = wa.pack(v, CELL)
        assert p is not None, k + ' does not pack as a one-pixel grid: keep it inline in banana-rave.js instead'
        assert wa.unpack(p, CELL) == v, 'round trip broke for ' + k
        packed[k] = p
    pj = '{' + ','.join('%s:[%d,%d,%d,"%s","%s"]' % ((k,) + tuple(v)) for k, v in packed.items()) + '}'
    before = sum(len(v) for _, v in items)
    out = (
        "// \U0001FAA9 GENERATED by tools/build-raveart.py — DO NOT EDIT.\n"
        "// The readable art is tools/raveart-source.js; change a sprite there and re-run the tool.\n"
        "// Each is [headIndex, gridW, gridH, palette (6 hex digits per colour), cells] on a ONE-pixel grid,\n"
        "// decoded by unpackArt(p, 1) in src/lib/wear-unpack.js BYTE FOR BYTE (tools/check-wearart.mjs proves it):\n"
        "// %d B of art ships as %d B.\n"
        "export const RAVE_P = %s;\n"
    ) % (before, len(pj), pj)
    io.open(OUT, 'w', encoding='utf-8', newline='\n').write(out)
    print('  %d rave sprites packed, byte-exact' % len(packed))
    print('  art bytes:   %d -> %d  (%.1f%% smaller)' % (before, len(pj), 100.0 * (before - len(pj)) / before))
    print('  wrote %s (%d B)' % (os.path.relpath(OUT, SITE), len(out)))


if __name__ == '__main__':
    main()
