# -*- coding: utf-8 -*-
"""BANANA REMIX DATA — the dancing banana as native Forge pixel data.

The Forge's "Remix the banana" button must load the banana PIXEL-PERFECT,
not decode a scaled GIF render (averaging across the fat pixel blocks turns
the outline to mud — the 15 Jul "banana looks very broken" bug). Masters-era
doctrine: GENERATE from the 2000px masters.

Reads the 8 masters, reconstructs each frame's logical pixel grid (the
phase-aligned sampling proven in build-banana-voxel.py), crops all frames to
one COMMON bbox so the animation stays aligned, maps the authentic colors to
Forge indices (shared ink/white + the 1999 yellows/red as custom palette
entries riding the creation), and emits src/data/banana-remix.js.

Run:  python tools/build-banana-remix.py
"""
import base64
import os

import numpy as np
from PIL import Image

SITE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HIRES = os.path.join(SITE, 'public', 'assets', 'dancing-banana-highres')
OUT = os.path.join(SITE, 'src', 'data', 'banana-remix.js')
UNIT = 52  # master px per logical pixel (asset-pipeline fact)

PALETTE = [
    ('outline',   (0, 0, 0)),
    ('yellow',    (255, 255, 0)),
    ('white',     (255, 255, 255)),
    ('shade',     (206, 206, 0)),
    ('red',       (255, 0, 0)),
    ('deepshade', (156, 156, 0)),
]
# Forge mapping: outline/white use the shared palette; the four authentic
# 1999 colours ride as the creation's custom palette (cpal, indices 33+).
CPAL = ['#ffff00', '#cece00', '#9c9c00', '#ff0000']  # yellow, shade, deepshade, red
CODE_TO_FORGE = {1: 1, 2: 33, 3: 2, 4: 34, 5: 36, 6: 35}


def load_master(n):
    p = os.path.join(HIRES, 'dancing-banana-2000x2000-frame-%d.png' % n)
    a = np.asarray(Image.open(p).convert('RGBA')).copy()
    opaque = a[..., 3] >= 128
    a[~opaque] = 0
    a[opaque, 3] = 255
    rgb = a[..., :3].astype(np.int32)
    pal = np.array([c for _, c in PALETTE], dtype=np.int32)
    d = ((rgb[..., None, :] - pal[None, None, :, :]) ** 2).sum(-1)
    nearest = d.argmin(-1)
    a[..., :3] = np.where(opaque[..., None], pal[nearest].astype(np.uint8), 0)
    return a


def logical_grid_full(n):
    """Full-canvas logical grid (NO per-frame crop — frames must align)."""
    a = load_master(n)
    code = np.zeros(a.shape[:2], dtype=np.uint8)
    opaque = a[..., 3] == 255
    for i, (_, c) in enumerate(PALETTE):
        m = opaque & (a[..., 0] == c[0]) & (a[..., 1] == c[1]) & (a[..., 2] == c[2])
        code[m] = i + 1

    def phase(axis):
        d = (np.diff(code, axis=axis) != 0).sum(axis=1 - axis)
        scores = [d[p::UNIT].sum() for p in range(UNIT)]
        return (int(np.argmax(scores)) + 1) % UNIT

    oy, ox = phase(0), phase(1)
    ys = np.arange(oy + UNIT // 2, code.shape[0], UNIT)
    xs = np.arange(ox + UNIT // 2, code.shape[1], UNIT)
    grid = code[np.ix_(ys, xs)]
    yy = ((np.arange(code.shape[0]) - oy) // UNIT).clip(0, len(ys) - 1)
    xx = ((np.arange(code.shape[1]) - ox) // UNIT).clip(0, len(xs) - 1)
    acc = (grid[np.ix_(yy, xx)] == code).mean()
    print('  frame %d: %dx%d cells, reconstruction %.1f%%' % (n, grid.shape[1], grid.shape[0], acc * 100))
    if acc < 0.95:
        raise SystemExit('lattice drift too high on frame %d' % n)
    return grid


def main():
    grids = [logical_grid_full(n) for n in range(1, 9)]
    h = min(g.shape[0] for g in grids)
    w = min(g.shape[1] for g in grids)
    grids = [g[:h, :w] for g in grids]  # phase rounding can differ by one cell

    # one COMMON content bbox so the dance stays put frame to frame
    ys, xs = np.nonzero(np.stack(grids).any(0))
    y0, y1, x0, x1 = ys.min(), ys.max() + 1, xs.min(), xs.max() + 1
    grids = [g[y0:y1, x0:x1] for g in grids]
    H, W = grids[0].shape
    print('union sprite: %dx%d logical px' % (W, H))

    frames_b64 = []
    for g in grids:
        forge = np.zeros(g.shape, dtype=np.uint8)
        for code, idx in CODE_TO_FORGE.items():
            forge[g == code] = idx
        frames_b64.append(base64.b64encode(forge.tobytes()).decode())

    js = (
        '// GENERATED by tools/build-banana-remix.py — do not hand-edit.\n'
        '// The 1999 dancing banana as native Forge pixel data: %dx%d logical px,\n'
        '// 8 frames, authentic colours (outline/white shared; yellows/red as cpal\n'
        '// customs at indices 33+). The Forge\'s Remix button loads this directly —\n'
        '// pixel-perfect, no GIF decoding, no resampling.\n'
        'export const BANANA_REMIX = {\n'
        '  w: %d,\n'
        '  h: %d,\n'
        '  cpal: %s,\n'
        '  delays: [100, 100, 100, 100, 100, 100, 100, 100],\n'
        '  frames: [\n%s\n  ],\n'
        '};\n'
    ) % (W, H, W, H, str(CPAL).replace("'", "'"),
         ',\n'.join("    '%s'" % f for f in frames_b64))
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write(js)
    print('wrote', OUT)


if __name__ == '__main__':
    main()
