# -*- coding: utf-8 -*-
"""🗺️ ONE MAP PER AREA, baked from the area's OWN ground and props.

Trym, 20 Sep: "i think the info kiosk can open a nice interactive view of each area of banana world —
world maps of all areas, thumbnails first, and you can click and zoom around on a bigger version."

Every area in this world is a PLATE plus a list of OVERLAYS — the tall things that have to sort in
front of a banana. The plate alone is not the place: Banana Town's is bare cobbles and grass, because
every building in it is an overlay. So a map is the plate with the overlays composited back in draw
order, which is the very same painter's-algorithm sort the game does, run once at build time.

⚠️ THE OVERLAY ROWS ARE NOT ONE SHAPE. Each area's geo file grew on its own day:
    park      ["ov-0.png", x, y, w, h, base]
    town      ["ov-0.png", x, y, w, h, base, key]
    beach     {"src": "ov-0.png", "x":…, "y":…, "w":…, "h":…, "base":…}
    homestead [] — the homestead has none, because the farm is the PLAYER's and its plate carries
              the land itself. Its map is the land, and the pins say what is on it.
Reading them is therefore per-area, and that is on purpose: a clever common shape here would be one
more thing to keep in step with four files that have no reason to agree.

Out: public/assets/world/map-<key>.png (the zoomable one) and map-<key>-thumb.png.
"""
import io
import json
import os
import subprocess
import sys

from PIL import Image

SITE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PUB = os.path.join(SITE, 'public', 'assets')
OUT = os.path.join(PUB, 'world')

# ⭐ WIDE ENOUGH TO READ A SHOPFRONT, SMALL ENOUGH TO SEND DOWN A PHONE. The town is 2200 px of world
# and a player pinching into it wants to see the STORE sign, so the map keeps most of the pixels; the
# thumbnail is a tile in a grid and never needs more than this.
MAP_W = 1400
THUMB_W = 460


def geo_of(geo, names=None):
    """a generated geo module's exports, read by the runtime that owns them (see overlays_of)"""
    js = ("import('file://' + process.argv[1]).then(m => { const o = {};"
          " for (const k of Object.keys(m)) { const v = m[k];"
          " if (v !== undefined && typeof v !== 'function') o[k] = v; }"
          " process.stdout.write(JSON.stringify(o)); })")
    path = os.path.join(SITE, 'src', 'scripts', geo).replace(os.sep, '/')
    r = subprocess.run(['node', '-e', js, path], capture_output=True, text=True)
    if r.returncode != 0:
        raise RuntimeError('%s: %s' % (geo, (r.stderr or '').strip()[:200]))
    out = json.loads(r.stdout or '{}')
    return {k: out[k] for k in names} if names else out


def overlays_of(geo, key):
    """the OVERLAYS array out of an area's generated geo module, as plain data.

    ⚠️ READ BY NODE, NOT BY A REGEX. Three of the four geo files are generated by three different
    builders on three different days: the park quotes its filenames with apostrophes, the town with
    double quotes, and the beach writes objects with UNQUOTED keys. Every one of them is valid
    JavaScript and none of them is valid JSON — so the honest reader is the one that speaks the
    language the files are written in.
    """
    js = ("import('file://' + process.argv[1]).then(m => "
          "process.stdout.write(JSON.stringify(m.OVERLAYS || [])))")
    path = os.path.join(SITE, 'src', 'scripts', geo).replace(os.sep, '/')
    r = subprocess.run(['node', '-e', js, path], capture_output=True, text=True)
    if r.returncode != 0:
        raise RuntimeError('%s: %s' % (geo, (r.stderr or '').strip()[:200]))
    rows = json.loads(r.stdout or '[]')
    out = []
    for r_ in rows:
        if isinstance(r_, dict):
            out.append((r_['src'], int(r_['x']), int(r_['y']), int(r_.get('base', r_['y'] + r_.get('h', 0)))))
        else:
            out.append((r_[0], int(r_[1]), int(r_[2]), int(r_[5])))
    return out


def extra(key):
    """🏡 what an area draws that is not in its OVERLAYS list.

    Only the homestead has any, and the reason is the whole point of the place: the farm is the
    PLAYER'S, so it has no baked props at all — the plate is bare meadow and everything on it comes
    out of a save file. A map of somebody else's farm would be fiction, so this map is of the LAND:
    the fence at its full extent, the gate it opens by, the sign and the mailbox. What is inside the
    fence is yours to put there, and the pins say so.
    """
    if key != 'homestead':
        return []
    g = geo_of('homestead-geo.js')
    t = g['FENCE_TIERS']['3']
    return [
        (t['yard'][0], t['yard'][1], t['yard'][2]),
        (t['south'][0], t['south'][1], t['south'][2]),
        ('m-sign.png', g['SIGN']['x'] - g['SIGN']['w'] // 2, g['SIGN']['y'] - g['SIGN']['h']),
        ('m-mail.png', g['MAILBOX']['x'] - g['MAILBOX']['w'] // 2, g['MAILBOX']['y'] - g['MAILBOX']['h']),
    ]


def bake(key, plate, folder, geo):
    p = os.path.join(PUB, plate)
    if not os.path.exists(p):
        print('  ! %s: no plate at %s' % (key, plate))
        return None
    im = Image.open(p).convert('RGBA')
    n = 0
    # ⚠️ SORTED BY BASE, exactly like the game. Painting them in file order puts a lamp post in front
    # of the building it stands beside; the base (the foot's y) is what the world sorts on.
    for fn, x, y, base in sorted(overlays_of(geo, key), key=lambda o: o[3]):
        f = os.path.join(PUB, folder, fn)
        if not os.path.exists(f):
            continue
        im.alpha_composite(Image.open(f).convert('RGBA'), (x, y))
        n += 1
    for fn, x, y in extra(key):
        f = os.path.join(PUB, folder, fn)
        if not os.path.exists(f):
            print('  ! %s: no %s' % (key, fn))
            continue
        im.alpha_composite(Image.open(f).convert('RGBA'), (x, y))
        n += 1
    os.makedirs(OUT, exist_ok=True)
    big = im.convert('RGB')
    if big.width > MAP_W:
        big = big.resize((MAP_W, max(1, round(im.height * MAP_W / im.width))), Image.LANCZOS)
    big.save(os.path.join(OUT, 'map-%s.png' % key), optimize=True)
    th = im.convert('RGB').resize((THUMB_W, max(1, round(im.height * THUMB_W / im.width))), Image.LANCZOS)
    th.save(os.path.join(OUT, 'map-%s-thumb.png' % key), optimize=True)
    print('  map-%s.png %dx%d (%d props) + thumb %dx%d' % (key, big.width, big.height, n, th.width, th.height))
    return [key, im.width, im.height, big.width, big.height]


AREAS = [
    ('town', 'town/town.png', 'town', 'town-geo.js'),
    ('park', 'park/park.png', 'park', 'park-geo.js'),
    ('bay', 'beach/beach.png', 'beach', 'beach-geo.js'),
    ('homestead', 'homestead/homestead.png', 'homestead', 'homestead-geo.js'),
]

if __name__ == '__main__':
    print('area maps:')
    made = [bake(*a) for a in AREAS]
    if not all(made):
        sys.exit(1)
