"""🐚 THE SHELL ATLAS — bakes the ShoreThings pack into ONE game asset.

⚠️ LICENCE. ShoreThings is PURCHASED and says: "You may NOT resell or
redistribute this pack as is OR transformed/manipulated." The repo is public
and deploys live, so the raw pack lives in public/assets/_packs/ (gitignored)
and only this derived atlas ships. Same doctrine as the fishing pack.

WHY THIS REPLACED THE OLD SHELLS: the previous 29 "shells" were generated by
FORMULA in build-beach-scene.py — a swirl equation, an ellipse, a five-point
star, in 7 colour families x 3 shapes. Nothing was ever drawn, which is exactly
why Trym read them as low quality. These are real, named, hand-drawn species.

⚠️ 6 of the pack's 9 starfish ship only as .clip (Clip Studio source), not PNG.
Only astropecten / blue / common exported, so the starfish tier is small until
those are exported.

Run:  python tools/build-shell-atlas.py
"""
import os
from PIL import Image

SITE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PACK = os.path.join(SITE, 'public', 'assets', '_packs', 'ShoreThings_AssetPack_v1')
OUT = os.path.join(SITE, 'public', 'assets', 'beach')
T = 16

# ---- 🐚 THE BEACHCOMBING TABLE --------------------------------------------
# tier drives the odds AND how a find is dressed. Weight is per SPECIES, so a
# tier's real share is weight x how many species sit in it. Shells are the
# gentler cousin of the fish ledger: commons are very common, because the point
# of combing is a steady trickle you can do in 30 seconds, not a hunt.
#   file  = the sprite inside <pack>/shells/<folder>/ (or starfish/)
SHELLS = [
    # id,            display,          tier,        folder,       file
    ('periwinkle',   'Periwinkle',     'common',    'periwinkle', 'periwinkle_16x16'),
    ('coquinas',     'Coquinas',       'common',    'coquinas',   'coquinas_16x16'),
    ('mussel',       'Mussel',         'common',    'mussel',     'mussel_1_16x16'),
    ('clam',         'Clam',           'common',    'clam',       'clam_1_16x16'),
    ('oyster',       'Oyster',         'common',    'oyster',     'oyster_16x16'),
    ('slipper',      'Slipper Shell',  'common',    'slipper',    'slipper_16x16'),
    ('scallop',      'Scallop',        'common',    'scallop',    'scallop_1_16x16'),

    ('whelk',        'Whelk',          'uncommon',  'whelk',      'whelk_16x16'),
    ('auger',        'Auger',          'uncommon',  'auger',      'auger_16x16'),
    ('sharkeye',     'Shark Eye',      'uncommon',  'sharkEye',   'sharkEye_16x16'),
    ('comrie',       'Comrie',         'uncommon',  'comrie',     'comrie_16x16'),
    ('sundial',      'Sundial',        'uncommon',  'sundial',    'sundial_1_16x16'),
    ('tulip',        'Tulip Shell',    'uncommon',  'tulip',      'tulip_1_16x16'),
    ('angelwing',    'Angel Wing',     'uncommon',  'angelWing',  'angelWing_16x16'),

    ('conch',        'Conch',          'rare',      'conch',      'conch_1_16x16'),
    ('murex',        'Murex',          'rare',      'murex',      'murex_16x16'),
    ('triton',       'Triton',         'rare',      'triton',     'triton_16x16'),
    ('paua',         'Paua',           'rare',      'paua',       'paua_1_16x16'),
    ('kina',         'Kina Urchin',    'rare',      'kina',       'urchin_16x16'),

    ('nautilus',     'Nautilus',       'legendary', 'nautilus',   'nautilus_16x16'),
    ('junonia',      'Junonia',        'legendary', 'junonia',    'junonia_16x16'),
]

# the three starfish that actually exported as PNG
STARS = [
    ('star_common',  'Common Starfish', 'common',   'common',      'common_16x16'),
    ('star_blue',    'Blue Starfish',   'uncommon', 'blue',        'blue_16x16'),
    ('star_astro',   'Astropecten',     'rare',     'astropecten', 'astropecten_1_16x16'),
]

# ⚠️ softer tail than the FISH table on purpose. Fishing is a sit-down hunt, so
# a 1-in-200 legendary is a chase you opt into. Combing is a 30-second pass on
# the way past, so its grails have to be findable or nobody ever sees one.
WEIGHT = {'common': 100, 'uncommon': 34, 'rare': 14, 'legendary': 6}


def load(kind, folder, file):
    p = os.path.join(PACK, kind, folder, file + '.png')
    if not os.path.isfile(p):
        raise SystemExit('MISSING sprite: %s' % p)
    return Image.open(p).convert('RGBA')


def main():
    if not os.path.isdir(PACK):
        raise SystemExit('Pack not found at %s\n(gitignored — keep it local)' % PACK)
    rows = list(SHELLS) + list(STARS)
    tiles = []
    for i, (sid, disp, tier, folder, file) in enumerate(rows):
        kind = 'starfish' if sid.startswith('star_') else 'shells'
        im = load(kind, folder, file)
        if im.size != (T, T):
            im = im.resize((T, T), Image.NEAREST)
        tiles.append(im)

    atlas = Image.new('RGBA', (T * len(tiles), T), (0, 0, 0, 0))
    for i, im in enumerate(tiles):
        atlas.alpha_composite(im, (i * T, 0))
    atlas.save(os.path.join(OUT, 'shells.png'), optimize=True)
    print('wrote shells.png  %d tiles (%d shells + %d starfish)  %dx%d'
          % (len(tiles), len(SHELLS), len(STARS), atlas.width, atlas.height))

    body = []
    for i, (sid, disp, tier, _f, _n) in enumerate(rows):
        body.append("  { id: '%s', name: '%s', tier: '%s', i: %d },"
                    % (sid, disp, tier, i))

    js = '''// ⚠️⚠️ GENERATED FILE — DO NOT EDIT BY HAND. ⚠️⚠️
// Written by tools/build-shell-atlas.py. Re-run after changing the table:
//     python tools/build-shell-atlas.py
//
// Art = the PURCHASED ShoreThings pack, baked to public/assets/beach/shells.png
// (only the species we use). The raw pack is gitignored — its licence forbids
// redistributing it "as is OR transformed".
//
// These replaced 29 shells that were generated by FORMULA (a swirl equation and
// an ellipse), which is why they read as blobs. Real named species now.
//
// `i` indexes the atlas: %d tiles in one row, so tile i sits at
// background-position-x: i/(n-1) x 100%%.
export const SHELL_TILES = %d;

// tier → odds + dressing. Shells are the GENTLER cousin of the fish ledger:
// commons are very common, because combing should pay in 30 seconds.
export const SHELL_TIERS = {
  common:    { w: %d, label: 'common',    color: '#cfd8e3', stars: 1 },
  uncommon:  { w: %d, label: 'uncommon',  color: '#6ee7a0', stars: 2 },
  rare:      { w: %d, label: 'RARE',      color: '#5cc8ff', stars: 3 },
  legendary: { w: %d, label: 'LEGENDARY', color: '#ffd54a', stars: 4 },
};

export const SHELLS = [
%s
];
''' % (len(tiles), len(tiles), WEIGHT['common'], WEIGHT['uncommon'],
       WEIGHT['rare'], WEIGHT['legendary'], '\n'.join(body))
    p = os.path.join(SITE, 'src', 'scripts', 'shell-data.js')
    with open(p, 'w', encoding='utf-8') as f:
        f.write(js)
    print('wrote src/scripts/shell-data.js')

    tot = sum(WEIGHT[r[2]] for r in rows)
    for t in ('common', 'uncommon', 'rare', 'legendary'):
        k = [r for r in rows if r[2] == t]
        if not k:
            continue
        print('  %-10s %2d species  %5.1f%% of finds  (1 in %.0f per species)'
              % (t, len(k), 100.0 * len(k) * WEIGHT[t] / tot, tot / float(WEIGHT[t])))


if __name__ == '__main__':
    main()
