// 💰 WHAT EVERY LIVE VARIANT ACTUALLY EARNS — measured, not assumed.
//
// Joins three sources nothing else joins:
//   worker /pf          every Shopify variant -> its Printful CATALOG variant
//                       (v2 API; v1 refuses platform-connected stores)
//   Printful catalog    that catalog variant's blank cost (public, no auth)
//   tools/shop-slate.js the one rule: (2.00 + blank + 0.30) / 0.971 -> .99
//
// Until this existed nobody could see the official line's costs, which is how
// the mug shipped as the $12.25 enamel one and a flat-priced tee lost money on
// 5XL. Run it before reviving anything and after every price change.
//
//   node tools/shop-margins.js              every product
//   node tools/shop-margins.js hoodie crop  only matching names
//   node tools/shop-margins.js --list …     write print-files/REPRICE-LIST.md
//
// ⚠️ --list groups by SIZE and prices off the DEAREST blank in that size, not
// per colour. Printful charges a little more for some colourways (Military
// Green 5XL is $30.19 against $28.25), and one price per size that covers the
// worst case is both safe and something a human can actually bulk-edit. The
// alternative — a price per colour+size — is 80 rows and how the flat $23.99
// hoodie came to lose $7.20 a sale in the first place.

import { priceFor, marginAt, MIN_MARGIN, LABEL } from './shop-slate.js';

const WORKER = 'https://banana-sticker.trymstene.workers.dev/pf';
const only = process.argv.slice(2).map((s) => s.toLowerCase());

const get = (u) => fetch(u).then((r) => r.json());

// catalog variant id -> blank cost, resolved a PRODUCT at a time. One lookup
// per variant would be ~100 calls and Printful rate-limits at 120/min.
const costCache = new Map();
const productCache = new Map();

async function blankCost(variantId) {
  if (costCache.has(variantId)) return costCache.get(variantId);
  const v = await get(`https://api.printful.com/products/variant/${variantId}`);
  const pid = v.result && v.result.product && v.result.product.id;
  if (!pid) { costCache.set(variantId, null); return null; }
  if (!productCache.has(pid)) {
    const p = await get(`https://api.printful.com/products/${pid}`);
    productCache.set(pid, p.result && p.result.variants ? p.result.variants : []);
    for (const x of productCache.get(pid)) costCache.set(x.id, parseFloat(x.price));
  }
  return costCache.get(variantId) != null ? costCache.get(variantId) : null;
}

// "Maroon / 2XL" -> "2XL";  "8″×10″" -> itself;  "Default Title" -> "One size"
const sizeOf = (label) => {
  const tail = label.split('/').pop().trim();
  return /^default title$/i.test(tail) ? 'One size' : tail;
};
const SIZE_RANK = { XS: 0, S: 1, M: 2, L: 3, XL: 4, '2XL': 5, '3XL': 6, '4XL': 7, '5XL': 8 };

async function collect(name, rows) {
  const vs = [];
  for (const r of rows) {
    const m = /^(.*) :: catalog (\d+) :: retail ([\d.]+)$/.exec(r);
    if (!m) continue;
    const label = m[1].replace(/^\s*\/\s*/, '').trim();
    vs.push({ label, size: sizeOf(label), cost: await blankCost(+m[2]), retail: parseFloat(m[3]) });
  }
  // one band per size, priced off the DEAREST blank wearing it
  const bands = new Map();
  for (const v of vs) {
    if (v.cost == null) continue;
    const b = bands.get(v.size) || { size: v.size, cost: 0, retails: new Set(), n: 0 };
    b.cost = Math.max(b.cost, v.cost);
    b.retails.add(v.retail);
    b.n += 1;
    bands.set(v.size, b);
  }
  return [...bands.values()].sort((a, b) =>
    (SIZE_RANK[a.size] ?? 99) - (SIZE_RANK[b.size] ?? 99) || a.cost - b.cost);
}

const pf = await get(WORKER);
const wantList = only.includes('--list');
const wantJson = only.includes('--json');
// --label  the product carries the neck label; its $0.99 is part of the cost
// --exact  set EVERY band to the rule, not only the ones sitting under it.
//          A product Printful just created carries Printful's suggested retail,
//          which is neither our rule nor consistent between sizes — "already
//          clears the rule" is the wrong answer for a brand-new product.
const withLabel = only.includes('--label');
const exact = only.includes('--exact');
const FLAGS = ['--list', '--json', '--label', '--exact'];
const names = only.filter((o) => !FLAGS.includes(o));
const costWith = (blank) => blank + (withLabel ? LABEL.cost : 0);
// product NAME -> { size: price } for the worker to apply. Computed here, where
// the numbers can be read and checked, rather than derived server-side.
const payload = {};
const doc = ['# Reprice list — the archived line, brought back', '',
  'Generated by `node tools/shop-margins.js --list`. Blank costs are live from',
  "Printful, joined to Shopify through the catalog variant behind each row.", '',
  '**One price per SIZE**, set from the dearest colourway in that size — safe on',
  'every colour and editable in one pass. Shopify: the product → *Edit prices* →',
  'sort by size.', ''];
let anyLoss = false;

for (const [name, rows] of Object.entries(pf)) {
  if (names.length && !names.some((o) => name.toLowerCase().includes(o))) continue;
  if (!Array.isArray(rows)) { console.log(`\n${name}: ${rows}`); continue; }
  const bands = await collect(name, rows);
  const needs = bands.filter((b) => exact || Math.min(...b.retails) < priceFor(costWith(b.cost)));
  console.log(`\n${name}  (${rows.length} variants, ${bands.length} size bands)`);
  if (wantList) {
    doc.push(`### ${name}`, '');
    // header and separator must be ADJACENT lines or the table renders as text
    if (needs.length) doc.push('| Size | Variants | Blank | Now | **Set to** | You keep |',
      '|---|---|---|---|---|---|');
    else doc.push('✅ Already clears the rule — nothing to change.', '');
  }
  for (const b of bands) {
    const now = [...b.retails].sort((x, y) => x - y);
    const cost = costWith(b.cost);
    const want = priceFor(cost);
    const keepsNow = marginAt(now[0], cost);
    const ok = exact ? (now.length === 1 && now[0] === want) : now[0] >= want;
    if (!ok) anyLoss = true;
    console.log(`   ${(ok ? '✅' : keepsNow < 0 ? '💀' : '⚠️ ').padEnd(3)} ${b.size.padEnd(10)}` +
      `${String(b.n).padStart(3)}v  cost $${cost.toFixed(2).padStart(6)}  now $${now[0].toFixed(2).padStart(6)}` +
      (ok ? `  keeps $${keepsNow.toFixed(2)}` : `  → $${want.toFixed(2)}  (keeps $${marginAt(want, cost).toFixed(2)})`));
    if (wantList && !ok) {
      doc.push(`| ${b.size} | ${b.n} | $${cost.toFixed(2)} | $${now[0].toFixed(2)} | ` +
        `**$${want.toFixed(2)}** | $${marginAt(want, cost).toFixed(2)} |`);
    }
    if (!ok) {
      (payload[name] = payload[name] || {})[b.size] = want.toFixed(2);
    }
  }
  if (wantList) doc.push('');
}

if (wantList) {
  const fs = await import('node:fs');
  const dir = new URL('../print-files/', import.meta.url);
  fs.mkdirSync(dir, { recursive: true });
  doc.push('---', '',
    'Every row keeps at least $2.00 after Shopify\'s 2.9% + $0.30, with shipping',
    'charged at checkout. After repricing: set the product ACTIVE, publish it to',
    '**Online Store + Dancing Banana Official Headless** (the site reads the',
    'second one) plus Google & YouTube and Facebook & Instagram, then check',
    '`/health?buyable=1` — a product can look perfect and still refuse to sell.', '');
  const p = new URL('REPRICE-LIST.md', dir);
  fs.writeFileSync(p, doc.join('\n'));
  console.log('\nwrote print-files/REPRICE-LIST.md');
}
if (wantJson) {
  const fs = await import('node:fs');
  const p = new URL('../print-files/reprice-payload.json', import.meta.url);
  fs.writeFileSync(p, JSON.stringify(payload, null, 1));
  const rows = Object.values(payload).reduce((n, o) => n + Object.keys(o).length, 0);
  console.log(`\nwrote print-files/reprice-payload.json — ${Object.keys(payload).length} products, ${rows} size bands`);
}
console.log(anyLoss ? '⚠️  rows marked above are under the $2 rule'
  : '✅ every variant clears the $2 rule');
